### ISSUE TITLE
Kubeflow Local Example --> Metadata TypeError

### ISSUE THREAD

**Issue by rummens** [tensorflow/tfx#1002]
I experience a TypeError with the Taxi Kubeflow Local Example ([link](https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi_pipeline/taxi_pipeline_kubeflow_local.py)).

I run into the following error of the csvexamplegen component: 
```
Traceback (most recent call last):
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 321, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 295, in main
    connection_config = _get_metadata_connection_config(kubeflow_metadata_config)
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 71, in _get_metadata_connection_config
    kubeflow_metadata_config.mysql_db_service_host)
TypeError: None has type NoneType, but expected one of: bytes, unicode
```

As far as I can see, the example configures a metadata-config, so I dont understand why it doesn't work. 
Is there anything special I need to deploy in addition or maybe I am using the wrong version of the libaries (tfx==0.15.0, kfp==0.1.36)?

Thanks
Marcel

**Comment by neuromage** [comment]
Hi @rummens,

That error happens when it's unable to find the configuration in the cluster. It uses the service name for mysql deployment that is default in KFP's lightweight deployment [1], which is called 'MYSQL', hence all pods have the environment variable MYSQL_SERVICE_HOST. Did you deploy KFP using Kubeflow? In which case the name of the mysql service in the cluster may be different, and you'll have to update the metadata config accordingly so the values point to the service in your cluster configuration. You can see how metadata config is set up in [2]

[1] https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize
[2] https://github.com/tensorflow/tfx/blob/a380346e5f81bd7c3b441bfb5ef13b82eca1871f/tfx/orchestration/kubeflow/kubeflow_dag_runner.py#L124

**Comment by rummens** [comment]
Hi @neuromage,

Thanks for the answer. It seems the corresponding environment variables (`mysql_host `etc.) are not even injected into the pod. As you can see below only `WORKFLOW_ID`, `KFP_POD_NAME `and `KFP_NAMESPACE `are injected.
Do I have to do this manually (e.g. using `add_env_from `) or does it happen automatically? 

I should be able to get all relevant data from the [default config](https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize/base/metadata). 

For reference I am trying to deploy the [local tfx example](https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi_pipeline/taxi_pipeline_kubeflow_local.py), as a fully non GCP TFX example with metadata support is still pending. 

**YAML of Pod:**
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    workflows.argoproj.io/node-name: chicago-taxi-pipeline-kubeflow-local-94kr5.csvexamplegen
    workflows.argoproj.io/outputs: '{"artifacts":[{"name":"mlpipeline-ui-metadata","path":"/mlpipeline-ui-metadata.json","optional":true}]}'
    workflows.argoproj.io/template: '{"name":"csvexamplegen","inputs":{"parameters":[{"name":"pipeline-root","value":"/mnt/pipelines/tfx/chicago_taxi_pipeline_kubeflow_local"}]},"outputs":{"artifacts":[{"name":"mlpipeline-ui-metadata","path":"/mlpipeline-ui-metadata.json","optional":true}]},"metadata":{"labels":{"add-pod-env":"true"}},"container":{"name":"","image":"tensorflow/tfx:0.15.0","command":["python","/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py"],"args":["--pipeline_name","chicago_taxi_pipeline_kubeflow_local","--pipeline_root","/mnt/pipelines/tfx/chicago_taxi_pipeline_kubeflow_local","--kubeflow_metadata_config","{\n  \"mysqlDbServiceHost\":
      {\n    \"environmentVariable\": \"mysql_host\"\n  },\n  \"mysqlDbServicePort\":
      {\n    \"environmentVariable\": \"mysql_port\"\n  },\n  \"mysqlDbName\": {\n    \"environmentVariable\":
      \"mysql_database\"\n  },\n  \"mysqlDbUser\": {\n    \"environmentVariable\":
      \"username\"\n  },\n  \"mysqlDbPassword\": {\n    \"environmentVariable\": \"password\"\n  }\n}","--beam_pipeline_args","[\"--direct_num_workers=0\"]","--additional_pipeline_args","{}","--component_launcher_class_path","tfx.orchestration.launcher.in_process_component_launcher.InProcessComponentLauncher","--serialized_component","{\"__class__\":
      \"NodeWrapper\", \"__module__\": \"tfx.orchestration.kubeflow.node_wrapper\",
      \"__tfx_object_type__\": \"jsonable\", \"_exec_properties\": {\"custom_config\":
      null, \"input_config\": \"{\\n  \\\"splits\\\": [\\n    {\\n      \\\"name\\\":
      \\\"single_split\\\",\\n      \\\"pattern\\\": \\\"*\\\"\\n    }\\n  ]\\n}\",
      \"output_config\": \"{\\n  \\\"splitConfig\\\": {\\n    \\\"splits\\\": [\\n      {\\n        \\\"hashBuckets\\\":
      2,\\n        \\\"name\\\": \\\"train\\\"\\n      },\\n      {\\n        \\\"hashBuckets\\\":
      1,\\n        \\\"name\\\": \\\"eval\\\"\\n      }\\n    ]\\n  }\\n}\"}, \"_id\":
      \"CsvExampleGen\", \"_inputs\": {\"__class__\": \"_PropertyDictWrapper\", \"__module__\":
      \"tfx.types.node_common\", \"__tfx_object_type__\": \"jsonable\", \"_compat_aliases\":
      {\"input\": \"input_base\"}, \"_data\": {\"input_base\": {\"__class__\": \"Channel\",
      \"__module__\": \"tfx.types.channel\", \"__tfx_object_type__\": \"jsonable\",
      \"_artifacts\": [{\"__class__\": \"ExternalArtifact\", \"__module__\": \"tfx.types.standard_artifacts\",
      \"__tfx_object_type__\": \"jsonable\", \"artifact\": {\"properties\": {\"split\":
      {\"stringValue\": \"\"}, \"type_name\": {\"stringValue\": \"ExternalPath\"}},
      \"uri\": \"/mnt/tfx/data/simple\"}, \"artifact_type\": {\"name\": \"ExternalPath\",
      \"properties\": {\"name\": \"STRING\", \"pipeline_name\": \"STRING\", \"producer_component\":
      \"STRING\", \"span\": \"INT\", \"split\": \"STRING\", \"state\": \"STRING\",
      \"type_name\": \"STRING\"}}}], \"type_name\": \"ExternalPath\"}}}, \"_outputs\":
      {\"__class__\": \"_PropertyDictWrapper\", \"__module__\": \"tfx.types.node_common\",
      \"__tfx_object_type__\": \"jsonable\", \"_compat_aliases\": {}, \"_data\": {\"examples\":
      {\"__class__\": \"Channel\", \"__module__\": \"tfx.types.channel\", \"__tfx_object_type__\":
      \"jsonable\", \"_artifacts\": [{\"__class__\": \"Examples\", \"__module__\":
      \"tfx.types.standard_artifacts\", \"__tfx_object_type__\": \"jsonable\", \"artifact\":
      {\"properties\": {\"name\": {\"stringValue\": \"examples\"}, \"pipeline_name\":
      {\"stringValue\": \"chicago_taxi_pipeline_kubeflow_local\"}, \"producer_component\":
      {\"stringValue\": \"CsvExampleGen\"}, \"split\": {\"stringValue\": \"train\"},
      \"type_name\": {\"stringValue\": \"ExamplesPath\"}}}, \"artifact_type\": {\"name\":
      \"ExamplesPath\", \"properties\": {\"name\": \"STRING\", \"pipeline_name\":
      \"STRING\", \"producer_component\": \"STRING\", \"span\": \"INT\", \"split\":
      \"STRING\", \"state\": \"STRING\", \"type_name\": \"STRING\"}}}, {\"__class__\":
      \"Examples\", \"__module__\": \"tfx.types.standard_artifacts\", \"__tfx_object_type__\":
      \"jsonable\", \"artifact\": {\"properties\": {\"name\": {\"stringValue\": \"examples\"},
      \"pipeline_name\": {\"stringValue\": \"chicago_taxi_pipeline_kubeflow_local\"},
      \"producer_component\": {\"stringValue\": \"CsvExampleGen\"}, \"split\": {\"stringValue\":
      \"eval\"}, \"type_name\": {\"stringValue\": \"ExamplesPath\"}}}, \"artifact_type\":
      {\"name\": \"ExamplesPath\", \"properties\": {\"name\": \"STRING\", \"pipeline_name\":
      \"STRING\", \"producer_component\": \"STRING\", \"span\": \"INT\", \"split\":
      \"STRING\", \"state\": \"STRING\", \"type_name\": \"STRING\"}}}], \"type_name\":
      \"ExamplesPath\"}}}, \"_type\": \"tfx.components.example_gen.csv_example_gen.component.CsvExampleGen\",
      \"driver_class\": {\"__class__\": \"Driver\", \"__module__\": \"tfx.components.example_gen.driver\",
      \"__tfx_object_type__\": \"class\"}, \"executor_spec\": {\"__class__\": \"ExecutorClassSpec\",
      \"__module__\": \"tfx.components.base.executor_spec\", \"__tfx_object_type__\":
      \"jsonable\", \"executor_class\": {\"__class__\": \"Executor\", \"__module__\":
      \"tfx.components.example_gen.csv_example_gen.executor\", \"__tfx_object_type__\":
      \"class\"}}}","--component_config","null"],"env":[{"name":"WORKFLOW_ID","valueFrom":{"fieldRef":{"fieldPath":"metadata.labels[''workflows.argoproj.io/workflow'']"}}},{"name":"KFP_POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"KFP_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}}],"resources":{},"volumeMounts":[{"name":"my-pv","mountPath":"/mnt"}]},"volumes":[{"name":"my-pv","persistentVolumeClaim":{"claimName":"my-pvc2"}}],"archiveLocation":{"s3":{"endpoint":"minio-service.kubeflow:9000","bucket":"mlpipeline","insecure":true,"accessKeySecret":{"name":"mlpipeline-minio-artifact","key":"accesskey"},"secretKeySecret":{"name":"mlpipeline-minio-artifact","key":"secretkey"},"key":"artifacts/chicago-taxi-pipeline-kubeflow-local-94kr5/chicago-taxi-pipeline-kubeflow-local-94kr5-3026907125"}}}'
  creationTimestamp: "2019-12-06T16:24:13Z"
  labels:
    add-pod-env: "true"
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/workflow: chicago-taxi-pipeline-kubeflow-local-94kr5
  name: chicago-taxi-pipeline-kubeflow-local-94kr5-3026907125
  namespace: kubeflow
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Workflow
    name: chicago-taxi-pipeline-kubeflow-local-94kr5
    uid: d6a95d5a-1844-11ea-81b0-7e4299593466
  resourceVersion: "963313"
  selfLink: /api/v1/namespaces/kubeflow/pods/chicago-taxi-pipeline-kubeflow-local-94kr5-3026907125
  uid: d7163efa-1844-11ea-81b0-7e4299593466
spec:
  containers:
  - command:
    - argoexec
    - wait
    env:
    - name: ARGO_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    image: argoproj/argoexec:v2.3.0
    imagePullPolicy: IfNotPresent
    name: wait
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /argo/podmetadata
      name: podmetadata
    - mountPath: /var/run/docker.sock
      name: docker-sock
      readOnly: true
    - mountPath: /argo/secret/mlpipeline-minio-artifact
      name: mlpipeline-minio-artifact
      readOnly: true
    - mountPath: /mainctrfs/mnt
      name: my-pv
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: pipeline-runner-token-cds9l
      readOnly: true
  - args:
    - --pipeline_name
    - chicago_taxi_pipeline_kubeflow_local
    - --pipeline_root
    - /mnt/pipelines/tfx/chicago_taxi_pipeline_kubeflow_local
    - --kubeflow_metadata_config
    - |-
      {
        "mysqlDbServiceHost": {
          "environmentVariable": "mysql_host"
        },
        "mysqlDbServicePort": {
          "environmentVariable": "mysql_port"
        },
        "mysqlDbName": {
          "environmentVariable": "mysql_database"
        },
        "mysqlDbUser": {
          "environmentVariable": "username"
        },
        "mysqlDbPassword": {
          "environmentVariable": "password"
        }
      }
    - --beam_pipeline_args
    - '["--direct_num_workers=0"]'
    - --additional_pipeline_args
    - '{}'
    - --component_launcher_class_path
    - tfx.orchestration.launcher.in_process_component_launcher.InProcessComponentLauncher
    - --serialized_component
    - '{"__class__": "NodeWrapper", "__module__": "tfx.orchestration.kubeflow.node_wrapper",
      "__tfx_object_type__": "jsonable", "_exec_properties": {"custom_config": null,
      "input_config": "{\n  \"splits\": [\n    {\n      \"name\": \"single_split\",\n      \"pattern\":
      \"*\"\n    }\n  ]\n}", "output_config": "{\n  \"splitConfig\": {\n    \"splits\":
      [\n      {\n        \"hashBuckets\": 2,\n        \"name\": \"train\"\n      },\n      {\n        \"hashBuckets\":
      1,\n        \"name\": \"eval\"\n      }\n    ]\n  }\n}"}, "_id": "CsvExampleGen",
      "_inputs": {"__class__": "_PropertyDictWrapper", "__module__": "tfx.types.node_common",
      "__tfx_object_type__": "jsonable", "_compat_aliases": {"input": "input_base"},
      "_data": {"input_base": {"__class__": "Channel", "__module__": "tfx.types.channel",
      "__tfx_object_type__": "jsonable", "_artifacts": [{"__class__": "ExternalArtifact",
      "__module__": "tfx.types.standard_artifacts", "__tfx_object_type__": "jsonable",
      "artifact": {"properties": {"split": {"stringValue": ""}, "type_name": {"stringValue":
      "ExternalPath"}}, "uri": "/mnt/tfx/data/simple"}, "artifact_type": {"name":
      "ExternalPath", "properties": {"name": "STRING", "pipeline_name": "STRING",
      "producer_component": "STRING", "span": "INT", "split": "STRING", "state": "STRING",
      "type_name": "STRING"}}}], "type_name": "ExternalPath"}}}, "_outputs": {"__class__":
      "_PropertyDictWrapper", "__module__": "tfx.types.node_common", "__tfx_object_type__":
      "jsonable", "_compat_aliases": {}, "_data": {"examples": {"__class__": "Channel",
      "__module__": "tfx.types.channel", "__tfx_object_type__": "jsonable", "_artifacts":
      [{"__class__": "Examples", "__module__": "tfx.types.standard_artifacts", "__tfx_object_type__":
      "jsonable", "artifact": {"properties": {"name": {"stringValue": "examples"},
      "pipeline_name": {"stringValue": "chicago_taxi_pipeline_kubeflow_local"}, "producer_component":
      {"stringValue": "CsvExampleGen"}, "split": {"stringValue": "train"}, "type_name":
      {"stringValue": "ExamplesPath"}}}, "artifact_type": {"name": "ExamplesPath",
      "properties": {"name": "STRING", "pipeline_name": "STRING", "producer_component":
      "STRING", "span": "INT", "split": "STRING", "state": "STRING", "type_name":
      "STRING"}}}, {"__class__": "Examples", "__module__": "tfx.types.standard_artifacts",
      "__tfx_object_type__": "jsonable", "artifact": {"properties": {"name": {"stringValue":
      "examples"}, "pipeline_name": {"stringValue": "chicago_taxi_pipeline_kubeflow_local"},
      "producer_component": {"stringValue": "CsvExampleGen"}, "split": {"stringValue":
      "eval"}, "type_name": {"stringValue": "ExamplesPath"}}}, "artifact_type": {"name":
      "ExamplesPath", "properties": {"name": "STRING", "pipeline_name": "STRING",
      "producer_component": "STRING", "span": "INT", "split": "STRING", "state": "STRING",
      "type_name": "STRING"}}}], "type_name": "ExamplesPath"}}}, "_type": "tfx.components.example_gen.csv_example_gen.component.CsvExampleGen",
      "driver_class": {"__class__": "Driver", "__module__": "tfx.components.example_gen.driver",
      "__tfx_object_type__": "class"}, "executor_spec": {"__class__": "ExecutorClassSpec",
      "__module__": "tfx.components.base.executor_spec", "__tfx_object_type__": "jsonable",
      "executor_class": {"__class__": "Executor", "__module__": "tfx.components.example_gen.csv_example_gen.executor",
      "__tfx_object_type__": "class"}}}'
    - --component_config
    - "null"
    command:
    - python
    - /tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py
    env:
    - name: WORKFLOW_ID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels['workflows.argoproj.io/workflow']
    - name: KFP_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: KFP_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: tensorflow/tfx:0.15.0
    imagePullPolicy: IfNotPresent
    name: main
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt
      name: my-pv
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: pipeline-runner-token-cds9l
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: aks-agentpool-15265024-vmss000002
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: pipeline-runner
  serviceAccountName: pipeline-runner
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations
        path: annotations
    name: podmetadata
  - hostPath:
      path: /var/run/docker.sock
      type: Socket
    name: docker-sock
  - name: my-pv
    persistentVolumeClaim:
      claimName: my-pvc2
  - name: mlpipeline-minio-artifact
    secret:
      defaultMode: 420
      items:
      - key: accesskey
        path: accesskey
      - key: secretkey
        path: secretkey
      secretName: mlpipeline-minio-artifact
  - name: pipeline-runner-token-cds9l
    secret:
      defaultMode: 420
      secretName: pipeline-runner-token-cds9l
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-12-06T16:24:13Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-12-06T16:25:04Z"
    message: 'containers with unready status: [wait main]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-12-06T16:25:04Z"
    message: 'containers with unready status: [wait main]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-12-06T16:24:13Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://ff295cc0a0717d143e8e89b1f64250b331b726bf970968ae7baffd06c2daf337
    image: tensorflow/tfx:0.15.0
    imageID: docker-pullable://tensorflow/tfx@sha256:076d45d7f635d2db38f1e5eb58bb96efff5f2df4dd1e1a62ca892fe753d431dc
    lastState: {}
    name: main
    ready: false
    restartCount: 0
    state:
      terminated:
        containerID: docker://ff295cc0a0717d143e8e89b1f64250b331b726bf970968ae7baffd06c2daf337
        exitCode: 1
        finishedAt: "2019-12-06T16:25:04Z"
        reason: Error
        startedAt: "2019-12-06T16:24:34Z"
  - containerID: docker://dd1e0a79ca62f27bf4ed31f52b4150b327a32c6f1fbd4e385cf5334b947179b6
    image: argoproj/argoexec:v2.3.0
    imageID: docker-pullable://argoproj/argoexec@sha256:85132fc2c8bc373fca885df17637d5d35682a23de8d1390668a5e1c149f2f187
    lastState: {}
    name: wait
    ready: false
    restartCount: 0
    state:
      terminated:
        containerID: docker://dd1e0a79ca62f27bf4ed31f52b4150b327a32c6f1fbd4e385cf5334b947179b6
        exitCode: 0
        finishedAt: "2019-12-06T16:25:04Z"
        reason: Completed
        startedAt: "2019-12-06T16:24:34Z"
  hostIP: 10.240.0.6
  phase: Failed
  podIP: 10.244.1.67
  qosClass: BestEffort
  startTime: "2019-12-06T16:24:13Z"
```

**Comment by neuromage** [comment]
Kubernetes injects those environment variables if the service is called 'mysql':
https://kubernetes.io/docs/concepts/services-networking/service/#discovering-services

What's the service name for your mysql service? KFP deploys one called 'mysql', but your cluster may be set up differently?

**Comment by rummens** [comment]
I used the default settings as described in the Getting Started guide.

**Comment by numerology** [comment]
Hi @rummens ,

The problem with the local example is that it overrides the pipeline_operator_func [here](https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi_pipeline/taxi_pipeline_kubeflow_local.py#L161), where in the default we mount the secret for metadata etc.

I think a workaround here is to manually append the [default op_func](https://github.com/tensorflow/tfx/blob/64676bfd5aca91a849fc488f4377004a6d9f260f/tfx/orchestration/kubeflow/kubeflow_dag_runner.py#L105) to the list

**Comment by rummens** [comment]
Thanks @numerology. I will give this a try. Will the function fail if I don’t provide the GCP secret because I am outside GCP?
If so I will only add the MySQL configmap and secret.

**Comment by numerology** [comment]
Yes if you are outside GCP then skipping gcp_secret_op is necessary.

**Comment by rummens** [comment]
This indeed brought me a step closer. This is my runner config now:

```
runner_config = kubeflow_dag_runner.KubeflowDagRunnerConfig(
        kubeflow_metadata_config=metadata_config,
        # Specify custom docker image to use.
        tfx_image=tfx_image,
        pipeline_operator_funcs=(
            # If running on K8s Engine (GKE) on Google Cloud Platform (GCP),
            # kubeflow_dag_runner.get_default_pipeline_operator_funcs() provides
            # default configurations specifically for GKE on GCP, such as secrets.
            [onprem.mount_pvc(_persistent_volume_claim, _persistent_volume,
                             _persistent_volume_mount),
            _mount_config_map_op('metadata-db-configmap'),
            _mount_secret_op('metadata-db-secrets')]

        ))
```

I had to change the names of the default configmap and secret to match the ones deployed by the default kustomize. In addition I had to add the `mysql_host` key to the configmap as it was not present. 

Now I run into access denied problems, not sure if I simply used the wrong host address (although I tried the service name and the cluster IP), or if the credentials stored in the `metadata-db-secrets` are just wrong.

I will do some more investigates over the next few days and keep you posted. 
Thanks for your help so far.

**Comment by rummens** [comment]
@numerology: It kind of works now, there a still some problems but at least the mysql connection works. Here is what I did:
1. It seems the default [kustomize ](https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/base/metadata/metadata-mysql-secret.yaml)deploys the mysql service with an account _root_ but without PW. However somewhere during the deployment a PW (_test_) is injected into the secret.
2. I edited the PW in the secret to be blank (removing does not work as the pod expects a PW).

Questions: 
1. I have hardcoded the IP for the host now, is there a way to make use of the internal DNS? I tried some combinations of mysql and the namespace but did not succeed. 
2. Right now the transform step fails with `AttributeError: module 'tensorflow' has no attribute 'is_nan'`. I tried different versions of the [TFX Docker image](https://hub.docker.com/r/tensorflow/tfx) (0.14, 0.15, latest) but they share the same error with 0.14 not working at all. Any idea what goes wrong? Which version is the [example ](https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi_pipeline/taxi_pipeline_kubeflow_local.py)build against?
3. The more important question for me: I cannot see any artefacts in the store, although a few steps have ran producing artefacts. Did I [misunderstood something ](https://medium.com/kubeflow/kubeflow-v0-7-delivers-beta-functionality-in-the-leadup-to-v1-0-1e63036c07b8) and TFX is not integrated into the store yet?

Thanks for your help, really appreciate it.
Marcel

**Comment by numerology** [comment]
I might need to dig a little bit into Q1, @neuromage do you have any suggestion?

For Q2, it's mostly likely due to the module file you use. TF2.0 removed tf.is_nan and changed it to tf.math.is_nan, can you upgrade it with the [latest version](https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi_pipeline/taxi_utils.py)?

For Q3, that's surprising... TFX [driver](https://github.com/tensorflow/tfx/blob/master/tfx/components/base/base_driver.py) should write published metadata into metadata store. Just curious, in the KFP UI, when you click each step, can you read the execution properties/input/output under the artifacts tab?

**Comment by neuromage** [comment]
For Q1, if you're using the DNS (and not environment variable), then set the service name by value:

https://github.com/tensorflow/tfx/blob/96174ff676a9020cba79c5e8fa2e89dfc5ce8e2d/tfx/orchestration/kubeflow/proto/kubeflow.proto#L23

For example, if the service is called `mysql` and the namespace is `kubeflow`, this should work:
```
config.mysql_db_service_host.value = 'mysql.kubeflow'
```

For Q3, that is surprising. It sounds like it's not talking to the same db name. The default db name is `metadb`. Can you ssh into your mysql service and see what dbs and tables are being populated by the pipeline?

**Comment by rummens** [comment]
Thanks @numerology **Q2** was an easy fix, stupid mistake of mine. The utils file was 6 months old ^^

@neuromage: Reg. **Q1**: It seems to work like this, can you explain why it will not work if "mysql.kubeflow" is passed via an env variable?

For **Q3**: I can see the artefacts in the UI, also the logs show:
```
INFO:absl:Running driver for SchemaGen
INFO:absl:MetadataStore with DB connection initialized
[...]
INFO:absl:Running publisher for SchemaGen
INFO:absl:MetadataStore with DB connection initialized
```

### Possible Second SQL Server/Client
I have a hunch though. By accident I discovered that another sql server is running in the pod metadata-db (which seems to back the Metadata API). The log of this pod show that something on localhost is going on (not sure if this is just a leftover of the pod crashing or if something is wrong): 
```
2019-12-09T17:19:54.065460Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
2019-12-09T17:19:54.065497Z 0 [Note] IPv6 is available.
2019-12-09T17:19:54.065530Z 0 [Note]   - '::' resolves to '::';
2019-12-09T17:19:54.065609Z 0 [Note] Server socket created on IP: '::'.
2019-12-09T17:19:54.095954Z 0 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
2019-12-09T17:19:54.095994Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
2019-12-09T17:19:54.096007Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
2019-12-09T17:19:54.096030Z 0 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
2019-12-09T17:19:54.096042Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
2019-12-09T17:19:54.096084Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
2019-12-09T17:19:54.346355Z 0 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
2019-12-09T17:19:54.346384Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
2019-12-09T17:19:54.351612Z 4 [Note] Event Scheduler: scheduler thread started with id 4
2019-12-09T17:19:54.351669Z 0 [Note] /usr/sbin/mysqld: ready for connections. Version: '8.0.3-rc-log'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
```


### MySQL Export
I found these DBs and tables in mysql:
```
+---------------------+
| Database            |
+---------------------+
| information_schema  |
| #mysql50#lost+found |
| metadb              |
| mlpipeline          |
| mysql               |
| performance_schema  |
+---------------------+
```

**Tables in DB metadb**
```
mysql> SELECT table_name FROM information_schema.tables WHERE table_schema="metadb";
+-------------------+
| table_name        |
+-------------------+
| Artifact          |
| ArtifactProperty  |
| Association       |
| Attribution       |
| Context           |
| ContextProperty   |
| Event             |
| EventPath         |
| Execution         |
| ExecutionProperty |
| MLMDEnv           |
| Type              |
| TypeProperty      |
+-------------------+
```

**Tables in DB mlpipeline**
```
mysql> SELECT table_name FROM information_schema.tables WHERE table_schema="mlpipeline";
+---------------------+
| table_name          |
+---------------------+
| db_statuses         |
| default_experiments |
| experiments         |
| jobs                |
| pipelines           |
| resource_references |
| run_details         |
| run_metrics         |
+---------------------+
```

### ConfigMap Export
I can confirm that the pipeline should be writing into _metadb_, as this is the DB configured in the mounted configmap:
```
apiVersion: v1
data:
  mysql_database: metadb
  mysql_port: "3306"
kind: ConfigMap
```

**Comment by rummens** [comment]
@neuromage @numerology Any idea?

**Comment by valeriano-manassero** [comment]
I got the same issue and my workaround was to manually patch the configmap `metadata-db-configmap` adding `mysql_host: metadata-db.kubeflow`.

Then I was able to retrieve the config with
```
runner_config = kubeflow_dag_runner.KubeflowDagRunnerConfig(kubeflow_metadata_config=metadata_config,
                                                                tfx_image=tfx_image,
                                                                pipeline_operator_funcs=([
                                                                    onprem.mount_pvc(_persistent_volume_claim,
                                                                                     _persistent_volume,
                                                                                     _persistent_volume_mount),
                                                                    kubeflow_dag_runner._mount_config_map_op('metadata-db-configmap'),
                                                                    kubeflow_dag_runner._mount_secret_op('metadata-db-secrets')
                                                                ]
                                                                ))
```

Not elegant I know, but it worked. Pointing the connection to `mysql.kubernetes` will not work since this is not the metadata db.

**Comment by rummens** [comment]
@valeriano-manassero: Thanks for the hint, fixed it for me as well. Do you also have problem with the Date and workspace not being picked up? It tells me "Invalid Date" in the Artifact Store.

**Comment by valeriano-manassero** [comment]
> @valeriano-manassero: Thanks for the hint, fixed it for me as well. Do you also have problem with the Date and workspace not being picked up? It tells me "Invalid Date" in the Artifact Store.

@rummens I cannot reproduce issues with any kind of "Invalid Date", for me it works, sorry.

**Comment by tholop** [comment]
I was also missing other configuration values. In case it helps someone, the following worked for me on GCP:

``` metadata_config = kubeflow_dag_runner.get_default_kubeflow_metadata_config()

    metadata_config.mysql_db_service_host.value = 'mysql.kubeflow'
    metadata_config.mysql_db_service_port.value = "3306"
    metadata_config.mysql_db_name.value = "metadb"
    metadata_config.mysql_db_user.value = "root"
    metadata_config.mysql_db_password.value = ""

    runner_config = kubeflow_dag_runner.KubeflowDagRunnerConfig(
        kubeflow_metadata_config=metadata_config,
        tfx_image=_KUBEFLOW_TFX_IMAGE,
        pipeline_operator_funcs=kubeflow_dag_runner.get_default_pipeline_operator_funcs()
    )
```
