### ISSUE TITLE
Kubeflow Local Example--transform error

### ISSUE THREAD

**Issue by Mikedu1988** [tensorflow/tfx#1003]
GCP is not accessible in my region, so I have to download the data into the pv and run the taxi sample in local mode [taxi_pipeline_kubeflow_local.py](https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi_pipeline/taxi_pipeline_kubeflow_local.py)

But I got below error, any idea what might went wrong?

![image](https://user-images.githubusercontent.com/24424690/69849699-6706c200-12b8-11ea-931f-065a584f321a.png)

`INFO:absl:Running executor for Transform
INFO:absl:Nonempty beam arg setup_file already includes dependency
WARNING:tensorflow:From /tfx-src/tfx/components/transform/executor.py:447: Schema (from tensorflow_transform.tf_metadata.dataset_schema) is deprecated and will be removed in a future version.
Instructions for updating:
Schema is a deprecated, use schema_utils.schema_from_feature_spec to create a `Schema`
Traceback (most recent call last):
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 321, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 314, in main
    execution_info = launcher.launch()
  File "/tfx-src/tfx/orchestration/launcher/base_component_launcher.py", line 205, in launch
    execution_decision.exec_properties)
  File "/tfx-src/tfx/orchestration/launcher/in_process_component_launcher.py", line 66, in _run_executor
    executor.Do(input_dict, output_dict, exec_properties)
  File "/tfx-src/tfx/components/transform/executor.py", line 326, in Do
    self.Transform(label_inputs, label_outputs, status_file)
  File "/tfx-src/tfx/components/transform/executor.py", line 806, in Transform
    preprocessing_fn, feature_spec)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_transform/inspect_preprocessing_fn.py", line 56, in get_analyze_input_columns    feature_spec)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_transform/impl_helper.py", line 74, in feature_spec_as_batched_placeholders    spec.dtype, [None, None], name=scope_name)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 2714, in sparse_placeholder    shape = placeholder(dtypes.int64, shape=[rank], name=shape_name)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 2630, in placeholder    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 6671, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/opt/venv/lib/python3.6/site-ackages/tensorflow_core/python/framework/op_def_library.py", line 410, in _apply_op_helper
    with g.as_default(), ops.name_scope(name) as scope:
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 6349, in __enter__    return self._name_scope.__enter__()
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__    return next(self.gen)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 4132, 
in name_scope raise ValueError("'%s' is not a valid scope name" % name) ValueError: 'F_Payment Type/shape' is not a valid scope name`

**Comment by Mikedu1988** [comment]
after delete some unused column, I now get error:
Instructions for updating:
Schema is a deprecated, use schema_utils.schema_from_feature_spec to create a `Schema`
Traceback (most recent call last):
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 321, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 314, in main
    execution_info = launcher.launch()
  File "/tfx-src/tfx/orchestration/launcher/base_component_launcher.py", line 205, in launch
    execution_decision.exec_properties)
  File "/tfx-src/tfx/orchestration/launcher/in_process_component_launcher.py", line 66, in _run_executor
    executor.Do(input_dict, output_dict, exec_properties)
  File "/tfx-src/tfx/components/transform/executor.py", line 326, in Do
    self.Transform(label_inputs, label_outputs, status_file)
  File "/tfx-src/tfx/components/transform/executor.py", line 806, in Transform
    preprocessing_fn, feature_spec)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_transform/inspect_preprocessing_fn.py", line 57, in get_analyze_input_columns
    _ = preprocessing_fn(input_signature.copy())
  File "/home/jovyan/data/tfx/taxi_utils.py", line 138, in preprocessing_fn
    tf.is_nan(taxi_fare),
**AttributeError: module 'tensorflow' has no attribute 'is_nan'**

**Comment by rmothukuru** [comment]
@Mikedu1988,
Can you please specify which columns did you delete. Thanks!

**Comment by numerology** [comment]
Hi @Mikedu1988 
I think this problem is more related with the incompatibility of your taxi_utils.py and tf 2.0
Can you try update your taxi_utils.py to the [latest](https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi_pipeline/taxi_utils.py) or change `tf.is_nan` to `tf.math.is_nan`?

**Comment by rmothukuru** [comment]
@Mikedu1988,
Can you please respond to @numerology's comment. Thanks!

**Comment by Mikedu1988** [comment]
Sorry,  currently our test env is teared down. I'll try the solution later. But we can close this issue for now.  
Thanks for your support @numerology
