### ISSUE TITLE
AttributeError: module 'tfx.components.base.base_executor' has no attribute 'BaseExecutor'

### ISSUE THREAD

**Issue by HugoPu** [tensorflow/tfx#1100]
Environment:
* ubuntu 16.04
* virenv: Anaconda3 
* python:3.6.9  
* Tensorflow 2.0.0
* tfx 0.15.0

Description:
I tired to run [TFX Component Tutorial](https://www.tensorflow.org/tfx/tutorials/tfx/components) on my machine with python cmd, but I get the following error, I tried to debug the error and I found if I ran `from tfx.components.base.base_executor import BaseExecutor`  before `from tfx.components.evaluator.component import Evaluator`, the error won't appear, otherwise `tfx/components/base/executor_spec.py` can't get `BaseExecutor` from `tfx.components.base.base_executor`. But why? 

Error Message:
```pytb
Traceback (most recent call last):
  File "/home/phtadmin/.pycharm_helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/phtadmin/.pycharm_helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/phtadmin/.pycharm_helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/phtadmin/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/sdb/hugo/PythonWorkspace/test_tf/test.py", line 12, in <module>
    from tfx.components.example_gen.csv_example_gen.component import CsvExampleGen
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/tfx/components/__init__.py", line 19, in <module>
    from tfx.components.bulk_inferrer.component import BulkInferrer
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/tfx/components/bulk_inferrer/component.py", line 23, in <module>
    from tfx.components.base import base_component
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/tfx/components/base/base_component.py", line 29, in <module>
    from tfx.components.base import base_node
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/tfx/components/base/base_node.py", line 28, in <module>
    from tfx.components.base import base_executor
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/tfx/components/base/base_executor.py", line 26, in <module>
    import apache_beam as beam
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/apache_beam/__init__.py", line 97, in <module>
    from apache_beam import coders
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/apache_beam/coders/__init__.py", line 19, in <module>
    from apache_beam.coders.coders import *
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/apache_beam/coders/coders.py", line 30, in <module>
    from future.moves import pickle
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/future/moves/__init__.py", line 8, in <module>
    import_top_level_modules()
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/future/standard_library/__init__.py", line 810, in import_top_level_modules
    with exclude_local_folder_imports(*TOP_LEVEL_MODULES):
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/future/standard_library/__init__.py", line 781, in __enter__
    module = __import__(m, level=0)
  File "/sdb/hugo/PythonWorkspace/test_tf/test.py", line 12, in <module>
    from tfx.components.example_gen.csv_example_gen.component import CsvExampleGen
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/tfx/components/example_gen/csv_example_gen/component.py", line 23, in <module>
    from tfx.components.base import executor_spec
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/tfx/components/base/executor_spec.py", line 36, in <module>
    class ExecutorClassSpec(ExecutorSpec):
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/tfx/components/base/executor_spec.py", line 44, in ExecutorClassSpec
    def __init__(self, executor_class: Type[base_executor.BaseExecutor]):
AttributeError: module 'tfx.components.base.base_executor' has no attribute 'BaseExecutor'
```

Successful code for me:

```python
import os
import pprint
import tempfile
import urllib

import tensorflow as tf
tf.get_logger().propagate = False
pp = pprint.PrettyPrinter()

import tfx
from tfx.components.base.base_executor import BaseExecutor
from tfx.components.evaluator.component import Evaluator
from tfx.components.example_gen.csv_example_gen.component import CsvExampleGen
from tfx.components.example_validator.component import ExampleValidator
from tfx.components.model_validator.component import ModelValidator
from tfx.components.pusher.component import Pusher
from tfx.components.schema_gen.component import SchemaGen
from tfx.components.statistics_gen.component import StatisticsGen
from tfx.components.trainer.component import Trainer
from tfx.components.transform.component import Transform
from tfx.orchestration import metadata, pipeline
from tfx.orchestration.experimental.interactive.interactive_context import InteractiveContext
from tfx.proto import evaluator_pb2, pusher_pb2, trainer_pb2
from tfx.proto.evaluator_pb2 import SingleSlicingSpec
from tfx.utils.dsl_utils import csv_input
from tensorflow.core.example import example_pb2

print('TensorFlow version: {}'.format(tf.__version__))
print('TFX version: {}'.format(tfx.__version__))
```

Unsuccessful code for me:

```python
import os
import pprint
import tempfile
import urllib

import tensorflow as tf
tf.get_logger().propagate = False
pp = pprint.PrettyPrinter()

import tfx
# from tfx.components.base.base_executor import BaseExecutor
from tfx.components.evaluator.component import Evaluator
from tfx.components.example_gen.csv_example_gen.component import CsvExampleGen
from tfx.components.example_validator.component import ExampleValidator
from tfx.components.model_validator.component import ModelValidator
from tfx.components.pusher.component import Pusher
from tfx.components.schema_gen.component import SchemaGen
from tfx.components.statistics_gen.component import StatisticsGen
from tfx.components.trainer.component import Trainer
from tfx.components.transform.component import Transform
from tfx.orchestration import metadata, pipeline
from tfx.orchestration.experimental.interactive.interactive_context import InteractiveContext
from tfx.proto import evaluator_pb2, pusher_pb2, trainer_pb2
from tfx.proto.evaluator_pb2 import SingleSlicingSpec
from tfx.utils.dsl_utils import csv_input
from tensorflow.core.example import example_pb2

print('TensorFlow version: {}'.format(tf.__version__))
print('TFX version: {}'.format(tfx.__version__))
```

**Comment by chongkong** [comment]
Unfortunately this is not reproduced in my machine.

In your stack trace, I found something weird:

```pytb
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/future/standard_library/__init__.py", line 781, in __enter__
    module = __import__(m, level=0)
  File "/sdb/hugo/PythonWorkspace/test_tf/test.py", line 12, in <module>
    from tfx.components.example_gen.csv_example_gen.component import CsvExampleGen
```
In the [source code](https://github.com/PythonCharmers/python-future/blob/master/src/future/standard_library/__init__.py#L781) `__import__` is called with one of [`TOP_LEVEL_MODULES`](https://github.com/PythonCharmers/python-future/blob/master/src/future/standard_library/__init__.py#L793) values, which should not continue to the next line in your stack trace. Re-entering to your source code is the direct cause of the AttributeError, since it introduces cyclic import to `BaseExecutor`.

As you're using a PyCharm, would you attach a debugger and see what `future/standard_library/__init__.py line 781` is trying to import? (i.e. `m` value)

**Comment by HugoPu** [comment]
Sorry, it's my fault to copy the wrong stack trace, since that time I trid to find out if the error only appeared in `from tfx.components.evaluator.component import Evaluator` and commented it, if I don't comment `from tfx.components.evaluator.component import Evaluator`. The stack trace is as follow:
```
Traceback (most recent call last):
  File "/home/phtadmin/.pycharm_helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/phtadmin/.pycharm_helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/phtadmin/.pycharm_helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/phtadmin/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/sdb/hugo/PythonWorkspace/test_tf/test.py", line 12, in <module>
    from tfx.components.evaluator.component import Evaluator
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/tfx/components/__init__.py", line 19, in <module>
    from tfx.components.bulk_inferrer.component import BulkInferrer
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/tfx/components/bulk_inferrer/component.py", line 23, in <module>
    from tfx.components.base import base_component
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/tfx/components/base/base_component.py", line 29, in <module>
    from tfx.components.base import base_node
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/tfx/components/base/base_node.py", line 28, in <module>
    from tfx.components.base import base_executor
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/tfx/components/base/base_executor.py", line 26, in <module>
    import apache_beam as beam
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/apache_beam/__init__.py", line 97, in <module>
    from apache_beam import coders
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/apache_beam/coders/__init__.py", line 19, in <module>
    from apache_beam.coders.coders import *
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/apache_beam/coders/coders.py", line 30, in <module>
    from future.moves import pickle
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/future/moves/__init__.py", line 8, in <module>
    import_top_level_modules()
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/future/standard_library/__init__.py", line 810, in import_top_level_modules
    with exclude_local_folder_imports(*TOP_LEVEL_MODULES):
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/future/standard_library/__init__.py", line 781, in __enter__
    module = __import__(m, level=0)
  File "/sdb/hugo/PythonWorkspace/test_tf/test.py", line 12, in <module>
    from tfx.components.evaluator.component import Evaluator
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/tfx/components/evaluator/component.py", line 24, in <module>
    from tfx.components.base import executor_spec
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/tfx/components/base/executor_spec.py", line 36, in <module>
    class ExecutorClassSpec(ExecutorSpec):
  File "/home/phtadmin/.conda/envs/tf_2.0/lib/python3.6/site-packages/tfx/components/base/executor_spec.py", line 44, in ExecutorClassSpec
    def __init__(self, executor_class: Type[base_executor.BaseExecutor]):
AttributeError: module 'tfx.components.base.base_executor' has no attribute 'BaseExecutor'
```

The value in `self.modules_names` is `<class 'tuple'>: ('builtins', 'copyreg', 'html', 'http', 'queue', 'reprlib', 'socketserver', 'test', 'tkinter', 'winreg', 'xmlrpc', '_dummy_thread', '_markupbase', '_thread')`, after `m = test`(my py file's name) , the error appeared

**Comment by HugoPu** [comment]
Oh, I got it! If I change my py file's name from `test.py` to `XXXX.py`(except the value in `self.modules_names`, like `testaaa.py`), the error won't appear. So the `future`  module think `test` is the local module, and read it again and again, right?

**Comment by chongkong** [comment]
Yeap I think you got the issue :)

FYI, `tfx/components` reexport all the components it has therefore aforementioned code can be simplified as

```python
import os
import pprint
import tempfile
import urllib

import tensorflow as tf
tf.get_logger().propagate = False
pp = pprint.PrettyPrinter()

import tfx
from tfx.components import Evaluator
from tfx.components import CsvExampleGen
from tfx.components import ExampleValidator
from tfx.components import ModelValidator
from tfx.components import Pusher
from tfx.components import SchemaGen
from tfx.components import StatisticsGen
from tfx.components import Trainer
from tfx.components import Transform
from tfx.orchestration import metadata, pipeline
from tfx.orchestration.experimental.interactive.interactive_context import InteractiveContext
from tfx.proto import evaluator_pb2, pusher_pb2, trainer_pb2
from tfx.proto.evaluator_pb2 import SingleSlicingSpec
from tfx.utils.dsl_utils import csv_input
from tensorflow.core.example import example_pb2
```
