### ISSUE TITLE
airflow initdb is giving error - "undefined symbol" in tfx_bsl_extension.so

### ISSUE THREAD

**Issue by srikanthjoshi** [tensorflow/tfx#1283]
Hi,

I am trying to run this project on IBM ppc64 POWER architecture. I have installed tensorflow, tfx, apache-airflow and now starting aiflow initdb, it is giving below error : 

```shell
(srikanth) [root@brazossrik01 ~]# airflow initdb
DB: sqlite:////root/airflow/airflow.db
[2020-02-14 05:44:12,258] {db.py:368} INFO - Creating tables
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
WARNI [airflow.utils.log.logging_mixin.LoggingMixin] cryptography not found - values will not be stored encrypted.
WARNING: Logging before flag parsing goes to stderr.
E0214 05:44:16.277226 140736382387456 dagbag.py:246] Failed to import: /root/airflow/dags/taxi_pipeline_simple.py
Traceback (most recent call last):
  File "/root/anaconda3/envs/srikanth/lib/python3.6/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/root/anaconda3/envs/srikanth/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/airflow/dags/taxi_pipeline_simple.py", line 23, in <module>
    from tfx.components import CsvExampleGen
  File "/root/anaconda3/envs/srikanth/lib/python3.6/site-packages/tfx/components/__init__.py", line 28, in <module>
    from tfx.components.example_validator.component import ExampleValidator
  File "/root/anaconda3/envs/srikanth/lib/python3.6/site-packages/tfx/components/example_validator/component.py", line 27, in <module>
    from tfx.components.example_validator import executor
  File "/root/anaconda3/envs/srikanth/lib/python3.6/site-packages/tfx/components/example_validator/executor.py", line 25, in <module>
    import tensorflow_data_validation as tfdv
  File "/root/anaconda3/envs/srikanth/lib/python3.6/site-packages/tensorflow_data_validation/__init__.py", line 24, in <module>
    from tensorflow_data_validation.api.stats_api import GenerateStatistics
  File "/root/anaconda3/envs/srikanth/lib/python3.6/site-packages/tensorflow_data_validation/api/stats_api.py", line 52, in <module>
    from tensorflow_data_validation.statistics import stats_impl
  File "/root/anaconda3/envs/srikanth/lib/python3.6/site-packages/tensorflow_data_validation/statistics/stats_impl.py", line 32, in <module>
    from tensorflow_data_validation.arrow import arrow_util
  File "/root/anaconda3/envs/srikanth/lib/python3.6/site-packages/tensorflow_data_validation/arrow/arrow_util.py", line 24, in <module>
    from tfx_bsl.arrow import array_util
  File "/root/anaconda3/envs/srikanth/lib/python3.6/site-packages/tfx_bsl/arrow/array_util.py", line 17, in <module>
    from tfx_bsl.cc.tfx_bsl_extension.arrow.array_util import *
ImportError: /root/anaconda3/envs/srikanth/lib/python3.6/site-packages/tfx_bsl/cc/tfx_bsl_extension.so: undefined symbol: _ZNK5arrow8DataType26ComputeMetadataFingerprintEv
Done.
(srikanth) [root@brazossrik01 ~]#
```

Below are the versions:

```shell
(srikanth) [root@brazossrik01 cc]# python -m pip list |grep tfx
tfx                        0.21.0             
tfx-bsl                    0.21.0             
(srikanth) [root@brazossrik01 cc]# python -m pip list |grep "tfx"
tfx                        0.21.0             
tfx-bsl                    0.21.0             
(srikanth) [root@brazossrik01 cc]# python -m pip list |grep tensorflow
tensorflow                 1.15.0             
tensorflow-data-validation 0.21.0             
tensorflow-estimator       1.15.1             
tensorflow-metadata        0.21.1             
tensorflow-model-analysis  0.21.1             
tensorflow-serving-api     1.15.0             
tensorflow-transform       0.21.0             
(srikanth) [root@brazossrik01 cc]# python -m pip list |grep apache-airflow
apache-airflow             1.10.9             
(srikanth) [root@brazossrik01 cc]# 
```

Please let me know how to resolve.

Thanks.

**Comment by 1025KB** [comment]
Hi, I start with a clean virtualenv, install tfx 0.21 and airflow 1.10.9

it works fine

could you try upgrade all tensorflow related packages?

**Comment by srikanthjoshi** [comment]
I got this resolved by building tfx-bsl without -c opt --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0. It worked fine and I am able to proceed futher.
