### ISSUE TITLE
Failure to launch TensorBoard in component tutorial

### ISSUE THREAD

**Issue by Ambiavi** [tensorflow/tfx#1422]
Running the component tutorial on jupyter notebook (with tfx==0.21.0 tensorflow==2.1 tensorboard==2.1 tensorflow-data-validation==0.21.1 ), I get up to the point of launching tensorboard (%tensorboard --logdir {model_dir}) and encounter this error. Seems I've somehow duplicated a tensorboard projector and I'm unsure how remove one. Details:

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
2020-03-05 21:13:25.633068: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-03-05 21:13:25.633234: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-03-05 21:13:25.633259: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
W0305 21:13:27.203562 139895620957952 plugin_event_accumulator.py:294] Found more than one graph event per run, or there was a metagraph containing a graph_def, as well as one or more graph events.  Overwriting the graph with the newest event.
W0305 21:13:27.204909 139895620957952 plugin_event_accumulator.py:302] Found more than one metagraph event per run. Overwriting the metagraph with the newest event.
Traceback (most recent call last):
  File "/home/ambi/.local/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/home/ambi/.local/lib/python3.6/site-packages/tensorboard/main.py", line 66, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/ambi/.local/lib/python3.6/site-packages/tensorboard/program.py", line 268, in main
    return runner(self.flags) or 0
  File "/home/ambi/.local/lib/python3.6/site-packages/tensorboard/program.py", line 282, in _run_serve_subcommand
    server = self._make_server()
  File "/home/ambi/.local/lib/python3.6/site-packages/tensorboard/program.py", line 361, in _make_server
    self.assets_zip_provider)
  File "/home/ambi/.local/lib/python3.6/site-packages/tensorboard/backend/application.py", line 165, in standard_tensorboard_wsgi
    flags, plugin_loaders, data_provider, assets_zip_provider, multiplexer)
  File "/home/ambi/.local/lib/python3.6/site-packages/tensorboard/backend/application.py", line 234, in TensorBoardWSGIApp
    return TensorBoardWSGI(tbplugins, flags.path_prefix)
  File "/home/ambi/.local/lib/python3.6/site-packages/tensorboard/backend/application.py", line 286, in __init__
    raise ValueError('Duplicate plugins for name %s' % plugin.plugin_name)
ValueError: Duplicate plugins for name projector

**Comment by Ambiavi** [comment]
That's correct. There were 2 versions of tensorboard installed. Deleting one as recommended in the link resolved the issue.

**Comment by Tanuveer** [comment]
Make sure you have the latest TensorBoard installed:
pip install -U tensorboard


This works for me.

**Comment by venu608** [comment]
when i am using tensor board its shows the error

Reusing TensorBoard on port 6008 (pid 659), started 0:44:54 ago. (Use '!kill 659' to kill it.)
