### ISSUE TITLE
"No module named 'numpy.core._multiarray_umath" during install

### ISSUE THREAD

**Issue by cfregly** [tensorflow/tfx#146]
python 3.6.5, tf 1.13.1, tfx 1.13.0 

following these workshop instructions:  https://github.com/tensorflow/tfx/tree/master/tfx/examples/workshop

error during install:

```
/Users/cfregly/miniconda3/lib/python3.6/site-packages/apache_beam/__init__.py:84: UserWarning: Running the Apache Beam SDK on Python 3 is not yet fully supported. You may encounter buggy behavior or missing features.
  'Running the Apache Beam SDK on Python 3 is not yet fully supported. '
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
2019-05-16 15:12:00.602984: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr
./setup_demo.sh: line 39:  3128 Abort trap: 6           jupyter nbextension install --py --symlink --sys-prefix tensorflow_model_analysis
/Users/cfregly/miniconda3/lib/python3.6/site-packages/apache_beam/__init__.py:84: UserWarning: Running the Apache Beam SDK on Python 3 is not yet fully supported. You may encounter buggy behavior or missing features.
  'Running the Apache Beam SDK on Python 3 is not yet fully supported. '
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
2019-05-16 15:12:02.106813: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr
./setup_demo.sh: line 40:  3131 Abort trap: 6           jupyter nbextension enable --py --sys-prefix tensorflow_model_analysis
```

error during runtime:
```
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
```

I upgraded to numpy==1.16 seemed to get me further per https://github.com/alpacahq/pylivetrader/issues/73#issuecomment-455901124

**Comment by ruoyu90** [comment]
@cfregly Does `pip install tfx==0.13.0` give you the same error in a clean env?

**Comment by gowtham-kp** [comment]
@cfregly Closing this issue as it has been inactive for more than a week. Please add additional comments and we can open this issue again. Thanks!
