### ISSUE TITLE
Output 0 of type variant does not match declared output type int64 for node node IteratorGetNext

### ISSUE THREAD

**Issue by tordsae** [tensorflow/tfx#1495]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Standard setup for gcp kubeflow and notebook as in https://www.tensorflow.org/tfx/tutorials/tfx/cloud-ai-platform-pipelines

Trying a pipeline with keras model to estimator method. Similar to the one in https://github.com/tensorflow/tfx/blob/r0.21/tfx/examples/iris/iris_utils.py, but for a simple autoencoder for 1 feature.

**Current behavior**
When the pipeline tries to save checkpoint I get the error:
https://github.com/tensorflow/tfx/blob/r0.21/tfx/examples/iris/iris_utils.py

Output 0 of type variant does not match declared output type int64 for node node IteratorGetNext

**Comment by jiyongjung0** [comment]
Thank you for raising this issue.
But there is not sufficient information to investigate at this moment.
Can you provide more context, full error messages and/or model definition?

**Comment by tordsae** [comment]
Sure, it might also be worth mentioning that I had to rewrite the dataset in input_fn to be a TensorSpec with shape [batchsize,1] from shape [batchsize,None]. Otherwise I get two other errors: 
- Last element in shape must be defined
- `TypeError: Failed to convert object of type <class 'tensorflow.python.framework.sparse_tensor.SparseTensor'> to Tensor. Contents: SparseTensor(indices=Tensor("DeserializeSparse_1:0", shape=(None, 2), dtype=int64), values=Tensor("metrics/mse/Cast:0", shape=(None,), dtype=float32), dense_shape=Tensor("shape_1:0", shape=(2,), dtype=int64)). Consider casting elements to a supported type.`


Model code:
`def _keras_model_builder(act_func="relu"):
    l = tf.keras.layers
    opt = tf.keras.optimizers
    inputs = [tf.keras.Input(shape=(1,), name=f) for f in features.transformed_name(features.DATA_VALUES)]
    if len(inputs) == 1:
        input_layer = inputs[0]
    else:
        input_layer = l.concatenate(inputs)
    d1 = l.Dense(16, activation='relu')(input_layer)
    d2 = l.Dense(8, activation=act_func)(d1)
    d3 = l.Dense(2, activation=act_func)(d2)
    d4 = l.Dense(8, activation=act_func)(d3)
    d5 = l.Dense(16, activation=act_func)(d4)
    output = l.Dense(len(inputs))(d5)
    model = tf.keras.Model(inputs=inputs, outputs=output)
    model.compile(
        loss='mse',
        optimizer=opt.Adam(),
        metrics=[tf.keras.metrics.MeanSquaredError(name="mse")])
    return model`

It is turned into an estimator by:
`    estimator = tf.keras.estimator.model_to_estimator(
        keras_model=_keras_model_builder(), config=run_config)`



Full error message:
`Traceback (most recent call last):
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1367, in _do_call
    return fn(*args)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1352, in _run_fn
    target_list, run_metadata)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1445, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Output 0 of type variant does not match declared output type int64 for node {{node IteratorGetNext}}
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 378, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 371, in main
    execution_info = launcher.launch()
  File "/tfx-src/tfx/orchestration/launcher/base_component_launcher.py", line 205, in launch
    execution_decision.exec_properties)
  File "/tfx-src/tfx/orchestration/launcher/in_process_component_launcher.py", line 67, in _run_executor
    executor.Do(input_dict, output_dict, exec_properties)
  File "/tfx-src/tfx/components/trainer/executor.py", line 329, in Do
    training_spec['eval_spec'])
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py", line 473, in train_and_evaluate
    return executor.run()
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py", line 613, in run
    return self.run_local()
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py", line 714, in run_local
    saving_listeners=saving_listeners)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 374, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1164, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1198, in _train_model_default
    saving_listeners)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1497, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 778, in run
    run_metadata=run_metadata)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1283, in run
    run_metadata=run_metadata)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1384, in run
    raise six.reraise(*original_exc_info)
  File "/opt/venv/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1369, in run
    return self._sess.run(*args, **kwargs)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1442, in run
    run_metadata=run_metadata)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1200, in run
    return self._sess.run(*args, **kwargs)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 960, in run
    run_metadata_ptr)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1183, in _run
    feed_dict_tensor, options, run_metadata)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1361, in _do_run
    run_metadata)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1386, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Output 0 of type variant does not match declared output type int64 for node node IteratorGetNext (defined at opt/venv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/util.py:65) 
Errors may have originated from an input operation.
Input Source operations connected to node IteratorGetNext:
 IteratorV2 (defined at opt/venv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/util.py:63)`

**Comment by jiyongjung0** [comment]
Thank you for quick response.
It looks like an issue in the TF side. Especially about the type of the given input data. But still I cannot see the detail about what kind of input you gave.

Or you might be able to check the output of SchemaGen or ExampleValidator, whether it inferred all the field correctly. You can check the output from the run diagram in KFP dashboard.

**Comment by tordsae** [comment]
Is this what you needed?

- Schema output:
```
feature {
  name: "data"
  value_count {
    min: 1
    max: 1
  }
  type: INT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
feature {
  name: "y"
  value_count {
    min: 1
    max: 1
  }
  type: INT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
```

- Feature spec:
`{'data': VarLenFeature(dtype=tf.int64), 'y': VarLenFeature(dtype=tf.int64)}`

- Dataset:
`<PrefetchDataset shapes: {data: (100, None), y: (100, None)}, types: {data: tf.int64, y: tf.int64}>`

**Comment by jiyongjung0** [comment]
One question in above code. It looks like you have transformed your input data somehow from the part
`features.transformed_name(features.DATA_VALUES)`. However our iris example doesn't have any preprocessing, and there is not `Transform` component in the pipeline.
Can you explain how you transformed your input data?

I used your model code with iris pipeline example and it worked well with dummy data.

**Comment by tordsae** [comment]
I found the problem.
During the infer schema step of the pipeline infer_feature_shape was set to False. Changing it to True fixed it right away.

**Comment by jiyongjung0** [comment]
Thank you for sharing your experience. :smile: I'll close this issue.
