### ISSUE TITLE
ImportError: cannot import name 'CsvExampleGen' on r0.21. / python 3.6.9 / tf 1.14

### ISSUE THREAD

**Issue by jason-brian-anderson** [tensorflow/tfx#1497]
I'm hoping to deploy TFX in product at Garmin and am running into some issues with the [Airflow tutorial](https://www.tensorflow.org/tfx/tutorials/tfx/airflow_workshop) 

i'm wondering if my TF version is too old?  i just ran 

`/home/tfx/tfx/tfx/examples/airflow_workshop/setup/setup_demo.sh 
`

which runs:

`printf "${GREEN}Installing TensorFlow${NORMAL}\n"

pip install tensorflow==1.14.0`

And the `README.md` testing framework compatibility tables states that r 0.21.0 should use TF 1.15.0 / 2.1

Anyway, here's my env:

```
(tfx-env) tfx@lambda-quad:~/tfx$ which python
/home/tfx/tfx-env/bin/python

(tfx-env) tfx@lambda-quad:~/tfx$ python -V
Python 3.6.9
(tfx-env) tfx@lambda-quad:~/tfx$ 

(tfx-env) tfx@lambda-quad:~/tfx$ git status
HEAD detached at origin/r0.21
nothing to commit, working tree clean


(tfx-env) tfx@lambda-quad:~/tfx$ python -c 'import tensorflow as tf; print(tf.__version__)'
<excluded a bunch of warnings...>
1.14.0

(tfx-env) tfx@lambda-quad:~/tfx$ git checkout -f origin/r0.21
Previous HEAD position was 711a9d8 Pin versions of airflow, flask and Werkzeug in setup_demo.sh
HEAD is now at 8f5a13f Merge pull request #1279 from dhruvesh09/master
(tfx-env) tfx@lambda-quad:~/tfx$ airflow webserver -p 8080
[2020-03-16 13:28:56,928] {__init__.py:51} INFO - Using executor SequentialExecutor
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
[2020-03-16 13:28:57,185] {__init__.py:305} INFO - Filling up the DagBag from /home/tfx/airflow/dags
[2020-03-16 13:28:57,187] {__init__.py:416} ERROR - Failed to import: /home/tfx/airflow/dags/taxi_pipeline_solutio
n.py
Traceback (most recent call last):
  File "/home/tfx/tfx-env/lib/python3.6/site-packages/airflow/models/__init__.py", line 413, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/home/tfx/tfx-env/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/tfx/airflow/dags/taxi_pipeline_solution.py", line 24, in <module>
    from tfx.components import CsvExampleGen
ImportError: cannot import name 'CsvExampleGen'
[2020-03-16 13:28:57,188] {__init__.py:416} ERROR - Failed to import: /home/tfx/airflow/dags/taxi_pipeline.py
Traceback (most recent call last):
  File "/home/tfx/tfx-env/lib/python3.6/site-packages/airflow/models/__init__.py", line 413, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/home/tfx/tfx-env/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/tfx/airflow/dags/taxi_pipeline.py", line 30, in <module>
    from tfx.components import CsvExampleGen
ImportError: cannot import name 'CsvExampleGen'
```

**Comment by jason-brian-anderson** [comment]
I switched to master as of 3/17/2020 and this problem was resolved.

**Comment by nroberts1** [comment]
Can this be reopened? I had the same issue and removed the checkout step as suggested to resolve.

I additionally, to get step 2 working, had to change the SQLAlchemy version to 1.3.15 as per this issue https://github.com/puckel/docker-airflow/issues/535.

Suggest setup_demo.sh adds this also as it is very frustrating to run a getting started tutorial that doesn't work.
