### ISSUE TITLE
Big query runtime parameter

### ISSUE THREAD

**Issue by tordsae** [tensorflow/tfx#1520]
Hi, I am trying to add runtime parameters to my pipeline. I have added a runtime parameter as in [https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi_pipeline/taxi_pipeline_runtime_parameter.py](url). Unlike the example in the link I am using BigQueryExampleGen, but when I try to run I get the following error:
```
Traceback (most recent call last):
  File "kubeflow_dag_runner.py", line 75, in <module>
    run()
  File "kubeflow_dag_runner.py", line 69, in run
    beam_pipeline_args=configs.BIG_QUERY_BEAM_PIPELINE_ARGS,
  File "/home/jupyter/Pipelines/anomaly_detection/pipeline.py", line 64, in create_pipeline
    example_gen = BigQueryExampleGen(query=query)
  File "/opt/conda/lib/python3.7/site-packages/tfx/components/example_gen/big_query_example_gen/component.py", line 71, in __init__
    input_config = input_config or utils.make_default_input_config(query)
  File "/opt/conda/lib/python3.7/site-packages/tfx/components/example_gen/utils.py", line 150, in make_default_input_config
    example_gen_pb2.Input.Split(name='single_split', pattern=split_pattern)
TypeError: {"__class__": "RuntimeParameter", "__module__": "tfx.orchestration.data_types", "__tfx_object_type__ has type RuntimeParameter, but expected one of: bytes, unicode
```
For CsvExampleGen this works fine. Is it some detail I'm missing?

**Comment by tordsae** [comment]
Figured it out, the parameter should be given to an input config and not the query argument. Here is an example:

```
    query = RuntimeParameter(
        name="query",
        ptype=Text,
        default="""SELECT * FROM ...""",
    )
    
    input_config={
        "splits": 
        [
            {
                'name': 'single_split',
                'pattern': query
            },
        ]
    }

    components = []
    example_gen = BigQueryExampleGen(input_config = input_config)
    components.append(example_gen)
```

**Comment by gowthamkpr** [comment]
@tordsae Glad that it has been figured out and yes you should pass the parameters through input config.. Can you please close this issue as it has been resolved. Thanks!
