### ISSUE TITLE
Airflow retries fails as Driver finds already existing output URI 

### ISSUE THREAD

**Issue by casassg** [tensorflow/tfx#1754]
If a component executor fails during execution, Airflow retries will fail due to the Driver finding output URI already exists. 

Log from Airflow webserver:
```
[2020-05-07 23:19:49,878] {{base_task_runner.py:115}} INFO - Job 21752: Subtask DataRecordExampleGen RuntimeError: Output artifact uri hdfs://default/user/gcasassaez/tfx/DataRecordExampleGen/examples/1 already exists
[2020-05-07 23:19:51,786] {{logging_mixin.py:95}} INFO - [2020-05-07 23:19:51,784] {{local_task_job.py:105}} INFO - Task exited with return code 1
```

**Comment by 1025KB** [comment]
Is that happen when you rerun (click run again) the entire pipeline?

The expect behavior is
1. If previous run succeeds, the rerun should be cached
2. If previous run failed and artifact id (1 in your log) is already taken, the next run should get a new artifact id, so it will be a new path

**Comment by casassg** [comment]
This happens when component1 fails (namingly DataRecordExampleGen which is an internal components based on FileBasedExamplegen) and Airflow retries the task. I need to manually clean up tfx root path so that it can retry correctly. I would expect retry to not use an already existing artifact_id.

Is it possible that the artifact is added in MLMD by Publisher? maybe the Executor fails in a non-expected way and Publisher never gets executed.  That makes MLMD not have the artifact even though the path was created by the driver. Next retry when Driver checks for artifact ids it does not get the right number and when it tries to create the path it fails.

I'm seeing an increase on the artifact_id (I'm at artifact_id 8) but it does not correspond to the right amount of retries (around 15 retries). 

If it's any useful, the exception is launched from Beam (so far it was a bad HDFS configuration or a bad reading path)

**Comment by 1025KB** [comment]
sorry, my bad, it's [execution id](https://github.com/tensorflow/tfx/blob/master/tfx/components/base/base_driver.py#L194)

as long as the driver got rerun, it should either do caching without create new execution or a new execution.

can you reproduce it with BeamDagRunner? it might be Airflow retry only retry executor (beam code)?

**Comment by casassg** [comment]
I don't think Airflow retries the executor only. Looking at the Stacktrace the failure is actually on the driver. 

```
Traceback (most recent call last):
  File ".deps/apache_airflow-1.10.4+twtr10-py2.py3-none-any.whl/airflow/models/taskinstance.py", line 922, in _run_raw_task
    result = task_copy.execute(context=context)
  File ".deps/apache_airflow-1.10.4+twtr10-py2.py3-none-any.whl/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File ".deps/apache_airflow-1.10.4+twtr10-py2.py3-none-any.whl/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File ".deps/tfx-0.21.1-py3-none-any.whl/tfx/orchestration/airflow/airflow_component.py", line 78, in _airflow_component_launcher
    launcher.launch()
  File "twitter/ml/tfx/orchestration/launcher/in_process_component_launcher.py", line 27, in launch
    return super().launch()
  File ".deps/tfx-0.21.1-py3-none-any.whl/tfx/orchestration/launcher/base_component_launcher.py", line 197, in launch
    self._exec_properties)
  File ".deps/tfx-0.21.1-py3-none-any.whl/tfx/orchestration/launcher/base_component_launcher.py", line 166, in _run_driver
    component_info=self._component_info)
  File ".deps/tfx-0.21.1-py3-none-any.whl/tfx/components/base/base_driver.py", line 273, in pre_execution
    component_info=component_info)
  File ".deps/tfx-0.21.1-py3-none-any.whl/tfx/components/base/base_driver.py", line 190, in _prepare_output_artifacts
    _prepare_output_paths(artifact)
  File "deps/tfx-0.21.1-py3-none-any.whl/tfx/components/base/base_driver.py", line 44, in _prepare_output_paths
    raise RuntimeError(msg)
RuntimeError: Output artifact uri hdfs://default/user/gcasassaez/tfx/DataRecordExampleGen/examples/8 already exists

```
Not sure if BeamDagRunner does have a retry policy as Airflow does. Will need to check that as I'm not as familiar w that Runner.

**Comment by 1025KB** [comment]
Does this always or occasionally happen? Did you try rerun the entire pipeline (turn off airflow retry)?

The execution id is retrieved [here](https://github.com/tensorflow/tfx/blob/master/tfx/components/base/base_driver.py#L245), could you try a clean env, and print previous's run's execution id and current's run's execution id per component?

**Comment by ruoyu90** [comment]
@casassg Thanks for reporting this! We will have a fix for this.

**Comment by singhniraj08** [comment]
@casassg,

Are you still looking for a resolution? We are planning on prioritising the issues based on the community interests. Please let us know if this issue still persists with the latest TFX 1.13 release so that we can work on fixing it. Thank you for your contributions.
