### ISSUE TITLE
Eva

### ISSUE THREAD

**Issue by aniruddhachoudhury** [tensorflow/tfx#1960]
I am building the Kubeflow Pipeline at that time i am using the eval_config with threshold  and then i am creating the pipeline with kubeflowdagrunner and TFX Kubeflow image and running the pipeline in the Kubeflow pipeline UI. I am getting the below error
**CODE**
```

 accuracy_threshold = tfma.MetricThreshold(
                value_threshold=tfma.GenericValueThreshold(
                    lower_bound={'value': 0.5},
                    upper_bound={'value': 0.99}),
                change_threshold=tfma.GenericChangeThreshold(
                    absolute={'value': 0.0001},
                    direction=tfma.MetricDirection.HIGHER_IS_BETTER),
                )

    metrics_specs = tfma.MetricsSpec(
                   metrics = [
                       tfma.MetricConfig(class_name='SparseCategoricalAccuracy',
                           threshold=accuracy_threshold),
                       tfma.MetricConfig(class_name='ExampleCount')])

    eval_config = tfma.EvalConfig(
        model_specs=[tfma.ModelSpec(signature_name='eval')],
        metrics_specs=[metrics_specs],
        slicing_specs=[
            tfma.SlicingSpec(),
            tfma.SlicingSpec(feature_keys=['trip_start_hour'])
        ]
    )  

    model_analyzer = Evaluator(
          examples=example_gen.outputs['examples'],
          model=trainer.outputs['model'],
          #baseline_model=model_resolver.outputs['model'],
          eval_config=eval_config)
```

**ERROR**
```
---------------------------------------------------------------------------
ParseError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in _ConvertFieldValuePair(self, js, message)
    523                    message_descriptor.full_name, name,
--> 524                    [f.json_name for f in message_descriptor.fields]))
    525         if name in names:

ParseError: Message type "tensorflow_model_analysis.MetricConfig" has no field named "threshold".
 Available Fields(except extensions): ['className', 'module', 'config']

During handling of the above exception, another exception occurred:

ParseError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in _ConvertFieldValuePair(self, js, message)
    566                                  ' in a repeated field.')
--> 567               self.ConvertMessage(item, sub_message)
    568           else:

/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in ConvertMessage(self, value, message)
    480     else:
--> 481       self._ConvertFieldValuePair(value, message)
    482 

/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in _ConvertFieldValuePair(self, js, message)
    591         else:
--> 592           raise ParseError(str(e))
    593       except ValueError as e:

ParseError: Message type "tensorflow_model_analysis.MetricConfig" has no field named "threshold".
 Available Fields(except extensions): ['className', 'module', 'config']

During handling of the above exception, another exception occurred:

ParseError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in _ConvertFieldValuePair(self, js, message)
    566                                  ' in a repeated field.')
--> 567               self.ConvertMessage(item, sub_message)
    568           else:

/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in ConvertMessage(self, value, message)
    480     else:
--> 481       self._ConvertFieldValuePair(value, message)
    482 

/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in _ConvertFieldValuePair(self, js, message)
    589         if field and field.containing_oneof is None:
--> 590           raise ParseError('Failed to parse {0} field: {1}.'.format(name, e))
    591         else:

ParseError: Failed to parse metrics field: Message type "tensorflow_model_analysis.MetricConfig" has no field named "threshold".
 Available Fields(except extensions): ['className', 'module', 'config'].

During handling of the above exception, another exception occurred:

ParseError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in _ConvertFieldValuePair(self, js, message)
    581           sub_message.SetInParent()
--> 582           self.ConvertMessage(value, sub_message)
    583         else:

/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in ConvertMessage(self, value, message)
    480     else:
--> 481       self._ConvertFieldValuePair(value, message)
    482 

/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in _ConvertFieldValuePair(self, js, message)
    589         if field and field.containing_oneof is None:
--> 590           raise ParseError('Failed to parse {0} field: {1}.'.format(name, e))
    591         else:

ParseError: Failed to parse metricsSpecs field: Failed to parse metrics field: Message type "tensorflow_model_analysis.MetricConfig" has no field named "threshold".
 Available Fields(except extensions): ['className', 'module', 'config']..

During handling of the above exception, another exception occurred:

ParseError                                Traceback (most recent call last)
<ipython-input-642-58867e2c9c87> in <module>
     10 columns=[] if len(featureKeys) == 0 else featureKeys[0]['featureKeys']
     11 slicing_spec = tfma.slicer.SingleSliceSpec(columns=columns)
---> 12 eval_result = tfma.load_eval_result('gs://tfx-pipeline/tfx_taxi_simple/TFX_Pipelinecheckn3/Evaluator/evaluation/533')
     13 slicing_metrics_view = tfma.view.render_slicing_metrics(eval_result, slicing_spec=slicing_spec)
     14 view = io.StringIO()

/usr/local/lib/python3.6/dist-packages/tensorflow_model_analysis/api/model_eval_lib.py in load_eval_result(output_path, model_name)
    207   """Creates an EvalResult object for use with the visualization functions."""
    208   eval_config, data_location, file_format, model_locations = (
--> 209       _load_eval_run(output_path))
    210   metrics_proto_list = (
    211       metrics_and_plots_serialization.load_and_deserialize_metrics(

/usr/local/lib/python3.6/dist-packages/tensorflow_model_analysis/api/model_eval_lib.py in _load_eval_run(output_path)
     99   if tf.io.gfile.exists(path):
    100     with tf.io.gfile.GFile(path, 'r') as f:
--> 101       pb = json_format.Parse(f.read(), config_pb2.EvalRun())
    102       _check_version(pb.version, output_path)
    103       return (pb.eval_config, pb.data_location, pb.file_format,

/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in Parse(text, message, ignore_unknown_fields, descriptor_pool)
    428   except ValueError as e:
    429     raise ParseError('Failed to load JSON: {0}.'.format(str(e)))
--> 430   return ParseDict(js, message, ignore_unknown_fields, descriptor_pool)
    431 
    432 

/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in ParseDict(js_dict, message, ignore_unknown_fields, descriptor_pool)
    448   """
    449   parser = _Parser(ignore_unknown_fields, descriptor_pool)
--> 450   parser.ConvertMessage(js_dict, message)
    451   return message
    452 

/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in ConvertMessage(self, value, message)
    479       methodcaller(_WKTJSONMETHODS[full_name][1], value, message)(self)
    480     else:
--> 481       self._ConvertFieldValuePair(value, message)
    482 
    483   def _ConvertFieldValuePair(self, js, message):

/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in _ConvertFieldValuePair(self, js, message)
    588       except ParseError as e:
    589         if field and field.containing_oneof is None:
--> 590           raise ParseError('Failed to parse {0} field: {1}.'.format(name, e))
    591         else:
    592           raise ParseError(str(e))

ParseError: Failed to parse evalConfig field: Failed to parse metricsSpecs field: Failed to parse metrics field: Message type "tensorflow_model_analysis.MetricConfig" has no field named "threshold".
 Available Fields(except extensions): ['className', 'module', 'config']...
```

Please have a look. @rcrowe-google @hughmiao @ewilderj @BioGeek .Thanks in advance.

**Comment by rcrowe-google** [comment]
This really looks like a version issue.  Can you move to these versions?

tensorflow 2.1.0
tfx 21.4
tfma 0.21.5
kfp 0.4.0

**Comment by aniruddhachoudhury** [comment]
Hi i am getting a new error after changing the version. And i know i am getting this error when i am using **baseline_model**
When i am building the tar.gz file for Kubeflow TFX  pipeline i am using TFX  Docker Image **'gcr.io/tfx-oss-public/tfx:0.21.4'**, which i have shared above the code.

So its failing in the evaluator step, and my blessing model will not be pushed to Pusher component for serving if i remove the **baseline_model** attribute from the **model_analyzer component**


So the thing is that everything working in Jupyter Notebook and this two error one above which i have posted and one below i am getting in Kubeflow Pipeline UI.


 ```
   model_resolver = ResolverNode(
          instance_name='latest_blessed_model_resolver',
          resolver_class=latest_blessed_model_resolver.LatestBlessedModelResolver,
          model=Channel(type=Model),
          model_blessing=Channel(type=ModelBlessing))

   model_analyzer = Evaluator(
          examples=example_gen.outputs['examples'],
          model=trainer.outputs['model'],
          baseline_model=model_resolver.outputs['model'],
          eval_config=eval_config)
```

**ERROR2**

```
2020-06-11 07:37:38.178719: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib
2020-06-11 07:37:38.178874: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib
2020-06-11 07:37:38.178892: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
INFO:absl:Using setup_file '/tfx-src/setup.py' to capture TFX dependencies
INFO:absl:Running driver for Evaluator
INFO:absl:MetadataStore with gRPC connection initialized
Traceback (most recent call last):
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 382, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 375, in main
    execution_info = launcher.launch()
  File "/tfx-src/tfx/orchestration/launcher/base_component_launcher.py", line 197, in launch
    self._exec_properties)
  File "/tfx-src/tfx/orchestration/launcher/base_component_launcher.py", line 166, in _run_driver
    component_info=self._component_info)
  File "/tfx-src/tfx/components/base/base_driver.py", line 239, in pre_execution
    driver_args, pipeline_info)
  File "/tfx-src/tfx/components/base/base_driver.py", line 150, in resolve_input_artifacts
    producer_component_id=input_channel.producer_component_id)
  File "/tfx-src/tfx/orchestration/metadata.py", line 899, in search_artifacts
    producer_component_id))
RuntimeError: Cannot find matching execution with pipeline name TFX_Pipetensorf1,run id tfx-pipetensorf1-shpqk and component id None
```
Please help me out in this @rcrowe-google. Thanks alot for in advance for your contribution to TFX world & your brilliant  
sessions in oreilly.

**Comment by ruoyu90** [comment]
@aniruddhachoudhury Just to confirm, this only happens on KFP? Have you tried to run it locally in beam runner or airflow runner?

**Comment by numerology** [comment]
@aniruddhachoudhury 

Do you mind sharing your pipeline definition? From the error message I'm blindly guessing perhaps `model_resolver` was not picked by `pipeline.components`

**Comment by ruoyu90** [comment]
@numerology I think you're right. By looking at the code snippet below.

> ```
>     return example_gen, statistics_gen, infer_schema, example_validator, transform,trainer,model_analyzer, pusher
> ```

**Comment by aniruddhachoudhury** [comment]
> @aniruddhachoudhury Just to confirm, this only happens on KFP? Have you tried to run it locally in beam runner or airflow runner?
My Project is in Kubeflow actually.

**Comment by aniruddhachoudhury** [comment]
> @numerology I think you're right. By looking at the code snippet below.
> 
> > ```
> >     return example_gen, statistics_gen, infer_schema, example_validator, transform,trainer,model_analyzer, pusher
> > ```

I think you are right  I missed the resolver to pass at the pipeline components my second error is resolved. But my first error Still I am getting. I am attaching the full code and version.

**ERROR1**
```
---------------------------------------------------------------------------
ParseError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in _ConvertFieldValuePair(self, js, message)
    523                    message_descriptor.full_name, name,
--> 524                    [f.json_name for f in message_descriptor.fields]))
    525         if name in names:

ParseError: Message type "tensorflow_model_analysis.MetricConfig" has no field named "threshold".
 Available Fields(except extensions): ['className', 'module', 'config']

During handling of the above exception, another exception occurred:

ParseError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in _ConvertFieldValuePair(self, js, message)
    566                                  ' in a repeated field.')
--> 567               self.ConvertMessage(item, sub_message)
    568           else:

/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in ConvertMessage(self, value, message)
    480     else:
--> 481       self._ConvertFieldValuePair(value, message)
    482 

/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in _ConvertFieldValuePair(self, js, message)
    591         else:
--> 592           raise ParseError(str(e))
    593       except ValueError as e:

ParseError: Message type "tensorflow_model_analysis.MetricConfig" has no field named "threshold".
 Available Fields(except extensions): ['className', 'module', 'config']

During handling of the above exception, another exception occurred:

ParseError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in _ConvertFieldValuePair(self, js, message)
    566                                  ' in a repeated field.')
--> 567               self.ConvertMessage(item, sub_message)
    568           else:

/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in ConvertMessage(self, value, message)
    480     else:
--> 481       self._ConvertFieldValuePair(value, message)
    482 

/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in _ConvertFieldValuePair(self, js, message)
    589         if field and field.containing_oneof is None:
--> 590           raise ParseError('Failed to parse {0} field: {1}.'.format(name, e))
    591         else:

ParseError: Failed to parse metrics field: Message type "tensorflow_model_analysis.MetricConfig" has no field named "threshold".
 Available Fields(except extensions): ['className', 'module', 'config'].

During handling of the above exception, another exception occurred:

ParseError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in _ConvertFieldValuePair(self, js, message)
    581           sub_message.SetInParent()
--> 582           self.ConvertMessage(value, sub_message)
    583         else:

/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in ConvertMessage(self, value, message)
    480     else:
--> 481       self._ConvertFieldValuePair(value, message)
    482 

/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in _ConvertFieldValuePair(self, js, message)
    589         if field and field.containing_oneof is None:
--> 590           raise ParseError('Failed to parse {0} field: {1}.'.format(name, e))
    591         else:

ParseError: Failed to parse metricsSpecs field: Failed to parse metrics field: Message type "tensorflow_model_analysis.MetricConfig" has no field named "threshold".
 Available Fields(except extensions): ['className', 'module', 'config']..

During handling of the above exception, another exception occurred:

ParseError                                Traceback (most recent call last)
<ipython-input-642-58867e2c9c87> in <module>
     10 columns=[] if len(featureKeys) == 0 else featureKeys[0]['featureKeys']
     11 slicing_spec = tfma.slicer.SingleSliceSpec(columns=columns)
---> 12 eval_result = tfma.load_eval_result('gs://tfx-pipeline/tfx_taxi_simple/TFX_Pipelinecheckn3/Evaluator/evaluation/533')
     13 slicing_metrics_view = tfma.view.render_slicing_metrics(eval_result, slicing_spec=slicing_spec)
     14 view = io.StringIO()

/usr/local/lib/python3.6/dist-packages/tensorflow_model_analysis/api/model_eval_lib.py in load_eval_result(output_path, model_name)
    207   """Creates an EvalResult object for use with the visualization functions."""
    208   eval_config, data_location, file_format, model_locations = (
--> 209       _load_eval_run(output_path))
    210   metrics_proto_list = (
    211       metrics_and_plots_serialization.load_and_deserialize_metrics(

/usr/local/lib/python3.6/dist-packages/tensorflow_model_analysis/api/model_eval_lib.py in _load_eval_run(output_path)
     99   if tf.io.gfile.exists(path):
    100     with tf.io.gfile.GFile(path, 'r') as f:
--> 101       pb = json_format.Parse(f.read(), config_pb2.EvalRun())
    102       _check_version(pb.version, output_path)
    103       return (pb.eval_config, pb.data_location, pb.file_format,

/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in Parse(text, message, ignore_unknown_fields, descriptor_pool)
    428   except ValueError as e:
    429     raise ParseError('Failed to load JSON: {0}.'.format(str(e)))
--> 430   return ParseDict(js, message, ignore_unknown_fields, descriptor_pool)
    431 
    432 

/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in ParseDict(js_dict, message, ignore_unknown_fields, descriptor_pool)
    448   """
    449   parser = _Parser(ignore_unknown_fields, descriptor_pool)
--> 450   parser.ConvertMessage(js_dict, message)
    451   return message
    452 

/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in ConvertMessage(self, value, message)
    479       methodcaller(_WKTJSONMETHODS[full_name][1], value, message)(self)
    480     else:
--> 481       self._ConvertFieldValuePair(value, message)
    482 
    483   def _ConvertFieldValuePair(self, js, message):

/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in _ConvertFieldValuePair(self, js, message)
    588       except ParseError as e:
    589         if field and field.containing_oneof is None:
--> 590           raise ParseError('Failed to parse {0} field: {1}.'.format(name, e))
    591         else:
    592           raise ParseError(str(e))

ParseError: Failed to parse evalConfig field: Failed to parse metricsSpecs field: Failed to parse metrics field: Message type "tensorflow_model_analysis.MetricConfig" has no field named "threshold".
 Available Fields(except extensions): ['className', 'module', 'config']...
```

**Comment by aniruddhachoudhury** [comment]
Please find the code:

The version which I am using and the docker image 
**TensorFlow version: 2.1.1
TFX version: 0.21.4
TFMA version: 0.21.5
kfp                           0.4.0
kfp-server-api                0.3.0
Docker Image:gcr.io/tfx-oss-public/tfx:0.21.4**

And the util file[taxi_util.py]( https://github.com/kubeflow/pipelines/tree/master/samples/core/tfx-oss/utils)




```
import os
from typing import Text

import kfp
import tensorflow_model_analysis as tfma
from tfx.proto import pusher_pb2
from tfx.proto import trainer_pb2
from tfx.components import Evaluator
from tfx.components import CsvExampleGen
from tfx.components import ExampleValidator
from tfx.components import Pusher
from tfx.components import SchemaGen
from tfx.components import ResolverNode
from tfx.components import StatisticsGen
from tfx.components import Trainer
from tfx.components import Transform
from tfx.components.base import executor_spec
from tfx.components.trainer.executor import GenericExecutor
from tfx.dsl.experimental import latest_blessed_model_resolver
from tfx.orchestration import metadata
from tfx.orchestration.experimental.interactive.interactive_context import InteractiveContext
from tfx.types import Channel
from tfx.types.standard_artifacts import Model
from tfx.types.standard_artifacts import ModelBlessing
from tfx.utils.dsl_utils import external_input
from tfx.orchestration import data_types
from tfx.orchestration import pipeline as pipeline
import tfx as tfx
from tfx.orchestration.kubeflow import kubeflow_dag_runner
from tfx.proto import pusher_pb2
from tfx.utils.dsl_utils import external_input
import pprint
import tempfile
import urllib
import absl
import os
from typing import Text
import kfp.dsl as dsl

tf.get_logger().propagate = False
pp = pprint.PrettyPrinter()
%load_ext tfx.orchestration.experimental.interactive.notebook_extensions.skip

pipeline_name = 'Taxi_Pipe_final_kf'

#Step1
pipeline_root = os.path.join('gs://{{kfp-default-bucket}}','tfx_taxi_simple', pipeline_name)
print(pipeline_root)


#Step2 
data_root_param = data_types.RuntimeParameter(
    name='data-root',
    default='gs://tfx-pipeline/tfx_taxi_simple/data',
    ptype=Text,
)

#Step3
taxi_module_file_param = data_types.RuntimeParameter(
    name='module-file',
    default='gs://tfx-pipeline/tfx_taxi_simple/modules/taxi_utils.py',
    ptype=Text,
)


#Step4
train_steps = data_types.RuntimeParameter(
    name='train-steps',
    default=10,
    ptype=int,
)

#Step5
eval_steps = data_types.RuntimeParameter(
    name='eval-steps',
    default=5,
    ptype=int,
)

#Step6
_serving_model_dir='tfx_model/serving'

def create_pipeline():
    
    #Step1
    example_gen = CsvExampleGen(input=external_input(data_root_param))
    
    #Step2
    statistics_gen = StatisticsGen(examples=example_gen.outputs['examples'])

    #Step3
    infer_schema = SchemaGen(statistics=statistics_gen.outputs['statistics'], infer_feature_shape=False)
    
    #Step4
    example_validator = ExampleValidator(statistics=statistics_gen.outputs['statistics'],schema=infer_schema.outputs['schema'])
    

    #Step5
    transform = Transform(
      examples=example_gen.outputs['examples'],
      schema=infer_schema.outputs['schema'],
      module_file=taxi_module_file_param)

    #Step6 
    trainer = Trainer(
      module_file=taxi_module_file_param,
      transformed_examples=transform.outputs['transformed_examples'],
      schema=infer_schema.outputs['schema'],
      transform_graph=transform.outputs['transform_graph'],
      train_args={'num_steps': train_steps},
      eval_args={'num_steps': eval_steps})
    
    #Step7
    model_resolver = ResolverNode(
          instance_name='latest_blessed_model_resolver',
          resolver_class=latest_blessed_model_resolver.LatestBlessedModelResolver,
          model=Channel(type=Model),
          model_blessing=Channel(type=ModelBlessing))

    
    #Step8
    
    eval_config = tfma.EvalConfig(
        model_specs=[tfma.ModelSpec(signature_name='eval')],
        slicing_specs=[tfma.SlicingSpec(), 
          tfma.SlicingSpec(feature_keys=['trip_start_hour'])])
    '''
    accuracy_threshold = tfma.MetricThreshold(
                value_threshold=tfma.GenericValueThreshold(
                    lower_bound={'value': 0.5},
                    upper_bound={'value': 0.99}),
                change_threshold=tfma.GenericChangeThreshold(
                    absolute={'value': 0.0001},
                    direction=tfma.MetricDirection.HIGHER_IS_BETTER),
                )

    metrics_specs = tfma.MetricsSpec(
                       metrics = [
                           tfma.MetricConfig(class_name='SparseCategoricalAccuracy',
                               threshold=accuracy_threshold),
                           tfma.MetricConfig(class_name='ExampleCount')])

    eval_config = tfma.EvalConfig(
        model_specs=[tfma.ModelSpec(signature_name='eval')],
        metrics_specs=[metrics_specs],
        slicing_specs=[
            tfma.SlicingSpec(),
            tfma.SlicingSpec(feature_keys=['trip_start_hour'])])
 '''
    model_analyzer = Evaluator(
          examples=example_gen.outputs['examples'],
          model=trainer.outputs['model'],
          baseline_model=model_resolver.outputs['model'],
          eval_config=eval_config,
      )
    

    #Step9
    pusher = Pusher(
          model=trainer.outputs['model'],
          model_blessing=model_analyzer.outputs['blessing'],
          push_destination=pusher_pb2.PushDestination(
              filesystem=pusher_pb2.PushDestination.Filesystem(
                 base_directory= _serving_model_dir
              )
          ),
      )
    
    return example_gen, statistics_gen, infer_schema, example_validator, transform,trainer,model_resolver,model_analyzer, pusher

example_gen, statistics_gen, schema_gen, example_validator, transform,trainer,model_resolver, evaluator, pusher=create_pipeline()

if __name__ == '__main__':
    
    #Step1
    dsl_pipeline = pipeline.Pipeline(
          pipeline_name=pipeline_name,
          pipeline_root=pipeline_root,
          components=[example_gen, statistics_gen, schema_gen, example_validator, transform,trainer,model_resolver, evaluator, pusher],
          enable_cache=True,
          beam_pipeline_args=['--direct_num_workers=%d' % 0])
    
    #Step2 
    #tfx_image = os.environ.get('KUBEFLOW_TFX_IMAGE', None)
    tfx_image = 'gcr.io/tfx-oss-public/tfx:0.21.4'
    
    #Step3
    metadata_config = kubeflow_dag_runner.get_default_kubeflow_metadata_config()
    
    #Step4
    config = kubeflow_dag_runner.KubeflowDagRunnerConfig(kubeflow_metadata_config=metadata_config,tfx_image=tfx_image)
    kubeflow_dag_runner.KubeflowDagRunner(config=config).run(dsl_pipeline)
```

**Comment by nikelite** [comment]
The error looks from threshold in tfma.MetricConfig.
0.21.5 tfma is supposed to have this. 

I'm wondering if can check the TFMA version again, and "tfma.MetricConfig.threshold"
`tfma.version.VERSION_STRING`
`type(tfma.MetricConfig.threshold)`

  Thanks.

**Comment by aniruddhachoudhury** [comment]
> The error looks from threshold in tfma.MetricConfig.
> 0.21.5 tfma is supposed to have this.
> 
> I'm wondering if can check the TFMA version again, and "tfma.MetricConfig.threshold"
> `tfma.version.VERSION_STRING`
> `type(tfma.MetricConfig.threshold)`
> 
> Thanks.
