### ISSUE TITLE
Evaluator runs into AttributeError: _shared_handle

### ISSUE THREAD

**Issue by yantriks-edi-bice** [tensorflow/tfx#2058]
Merged an older taxi template pipeline with latest template changes, deployed and ran (multiple times, changing and uploading as a new pipeline version with cache enabled) on Kubeflow 1.0

Evaluator component runs into the following error

INFO:apache_beam.runners.dataflow.dataflow_runner:2020-06-26T16:42:41.544Z: JOB_MESSAGE_ERROR: Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 1004, in apache_beam.runners.common.DoFnRunner._invoke_lifecycle_method
  File "apache_beam/runners/common.py", line 488, in apache_beam.runners.common.DoFnInvoker.invoke_setup
  File "/usr/local/lib/python3.6/site-packages/tensorflow_model_analysis/model_util.py", line 369, in setup
    model_load_time_callback=self._set_model_load_seconds)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_model_analysis/types.py", line 155, in load
    return self._shared_handle.acquire(construct_fn)
AttributeError: _shared_handle

Local package versions

tensorboard==2.1.1
tensorboard-plugin-wit==1.6.0.post3
tensorflow==2.2.0
tensorflow-data-validation==0.22.0
tensorflow-estimator==2.1.0
tensorflow-metadata==0.22.0
tensorflow-model-analysis==0.22.1
tensorflow-serving-api==2.1.0
tensorflow-transform==0.22.0

Evaluator code

    eval_config = tfma.EvalConfig(
        model_specs=[tfma.ModelSpec(label_key=features.LABEL_KEY)], # 'big_tipper')],
        slicing_specs=[tfma.SlicingSpec()],
        metrics_specs=[
            tfma.MetricsSpec(metrics=[
                tfma.MetricConfig(
                    class_name='BinaryAccuracy',
                    threshold=tfma.MetricThreshold(
                        value_threshold=tfma.GenericValueThreshold(
                            lower_bound={'value': eval_accuracy_threshold}),
                        change_threshold=tfma.GenericChangeThreshold(
                            direction=tfma.MetricDirection.HIGHER_IS_BETTER,
                            absolute={'value': -1e-10})))
            ])
        ])
    evaluator = Evaluator(
        examples=example_gen.outputs['examples'],
        model=trainer.outputs['model'],
        baseline_model=model_resolver.outputs['model'],
        # Change threshold will be ignored if there is no baseline (first run).
        eval_config=eval_config)
    # TODO(step 6): Uncomment here to add Evaluator to the pipeline.
    components.append(evaluator)

**Comment by yantriks-edi-bice** [comment]
This is now working.

I should mention I'm using a custom image as my code is in multiple modules - here's my Dockerfile

FROM tensorflow/tfx:0.22.0
WORKDIR /pipeline
COPY ./ ./
RUN pip install .
ENTRYPOINT []
CMD ["python3.6", "/tfx-src/tfx/scripts/run_executor.py"]

Changed setup.py, adding tensorflow-model-analysis and requiring latest version as there seem to have been changes to the load method which were committed recently 

import setuptools

setuptools.setup(
    name='markdowns-tfx-pipeline',
    version='0.3',
    install_requires=['tfx', 'tensorflow-model-analysis>=0.22.2'],
    packages=setuptools.find_packages(exclude=["*.output", "data"]),
)

**Comment by AlirezaSadeghi** [comment]
> This is now working.
> 
> I should mention I'm using a custom image as my code is in multiple modules - here's my Dockerfile
> 
> FROM tensorflow/tfx:0.22.0
> WORKDIR /pipeline
> COPY ./ ./
> RUN pip install .
> ENTRYPOINT []
> CMD ["python3.6", "/tfx-src/tfx/scripts/run_executor.py"]
> 
> Changed setup.py, adding tensorflow-model-analysis and requiring latest version as there seem to have been changes to the load method which were committed recently
> 
> import setuptools
> 
> setuptools.setup(
> name='markdowns-tfx-pipeline',
> version='0.3',
> install_requires=['tfx', 'tensorflow-model-analysis>=0.22.2'],
> packages=setuptools.find_packages(exclude=["*.output", "data"]),
> )

Hey,

I also am facing the same issue, not for the taxi example but on my own pipeline, and setting the TFMA version in `setup.py` (`tensorflow-model-analysis>=0.22.2`) didn't resolve this issue for me.

Do you have any extra insights about what exactly fixed your problem ?

Full error log of the evaluator component:

```bash
INFO:apache_beam.runners.dataflow.dataflow_runner:Job $JOBID is in state JOB_STATE_FAILED
Traceback (most recent call last):
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 360, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 353, in main
    execution_info = launcher.launch()
  File "/tfx-src/tfx/orchestration/launcher/base_component_launcher.py", line 205, in launch
    execution_decision.exec_properties)
  File "/tfx-src/tfx/orchestration/launcher/in_process_component_launcher.py", line 67, in _run_executor
    executor.Do(input_dict, output_dict, exec_properties)
  File "/tfx-src/tfx/components/evaluator/executor.py", line 224, in Do
    slice_spec=slice_spec))
  File "/opt/venv/lib/python3.6/site-packages/apache_beam/pipeline.py", line 547, in __exit__
    self.run().wait_until_finish()
  File "/opt/venv/lib/python3.6/site-packages/apache_beam/runners/dataflow/dataflow_runner.py", line 1643, in wait_until_finish
    self)
apache_beam.runners.dataflow.dataflow_runner.DataflowRuntimeException: Dataflow pipeline failed. State: FAILED, Error:
Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 1004, in apache_beam.runners.common.DoFnRunner._invoke_lifecycle_method
  File "apache_beam/runners/common.py", line 488, in apache_beam.runners.common.DoFnInvoker.invoke_setup
  File "/usr/local/lib/python3.6/site-packages/tensorflow_model_analysis/model_util.py", line 369, in setup
    model_load_time_callback=self._set_model_load_seconds)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_model_analysis/types.py", line 155, in load
    return self._shared_handle.acquire(construct_fn)
AttributeError: _shared_handle
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/dataflow_worker/batchworker.py", line 647, in do_work
    work_executor.execute()
  File "/usr/local/lib/python3.6/site-packages/dataflow_worker/executor.py", line 179, in execute
    op.start()
  File "apache_beam/runners/worker/operations.py", line 662, in apache_beam.runners.worker.operations.DoOperation.start
  File "apache_beam/runners/worker/operations.py", line 664, in apache_beam.runners.worker.operations.DoOperation.start
  File "apache_beam/runners/worker/operations.py", line 665, in apache_beam.runners.worker.operations.DoOperation.start
  File "apache_beam/runners/worker/operations.py", line 284, in apache_beam.runners.worker.operations.Operation.start
  File "apache_beam/runners/worker/operations.py", line 290, in apache_beam.runners.worker.operations.Operation.start
  File "apache_beam/runners/worker/operations.py", line 611, in apache_beam.runners.worker.operations.DoOperation.setup
  File "apache_beam/runners/worker/operations.py", line 660, in apache_beam.runners.worker.operations.DoOperation.setup
  File "apache_beam/runners/common.py", line 1010, in apache_beam.runners.common.DoFnRunner.setup
  File "apache_beam/runners/common.py", line 1006, in apache_beam.runners.common.DoFnRunner._invoke_lifecycle_method
  File "apache_beam/runners/common.py", line 1045, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "/usr/local/lib/python3.6/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "apache_beam/runners/common.py", line 1004, in apache_beam.runners.common.DoFnRunner._invoke_lifecycle_method
  File "apache_beam/runners/common.py", line 488, in apache_beam.runners.common.DoFnInvoker.invoke_setup
  File "/usr/local/lib/python3.6/site-packages/tensorflow_model_analysis/model_util.py", line 369, in setup
    model_load_time_callback=self._set_model_load_seconds)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_model_analysis/types.py", line 155, in load
    return self._shared_handle.acquire(construct_fn)
AttributeError: _shared_handle [while running 'ExtractEvaluateAndWriteResults/ExtractAndEvaluate/EvaluateMetricsAndPlots/ComputeMetricsAndPlots/ComputePerSliceMetrics/ComputeUnsampledMetrics/LoadModel']
```

**Comment by ruoyu90** [comment]
@mdreves any idea of what might be the cause?

**Comment by mdreves** [comment]
This is caused when the code used at pipeline construction time is a newer than the code that runs on the workers. There are a few suggestions (1) double check that all your containers are up to date and (2) failing that try forcing the version to 0.22.1 since it looks like that is the version used on the workers.
