### ISSUE TITLE
kerastuner "model-building function did not return a valid Keras Model instance, found estimator.canned ..."

### ISSUE THREAD

**Issue by yantriks-edi-bice** [tensorflow/tfx#2105]
Can estimators be tuned with the new Tuner component and how?

Traceback (most recent call last):
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 360, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 353, in main
    execution_info = launcher.launch()
  File "/tfx-src/tfx/orchestration/launcher/base_component_launcher.py", line 205, in launch
    execution_decision.exec_properties)
  File "/tfx-src/tfx/orchestration/launcher/in_process_component_launcher.py", line 67, in _run_executor
    executor.Do(input_dict, output_dict, exec_properties)
  File "/tfx-src/tfx/components/tuner/executor.py", line 55, in Do
    tuner_fn_result = tuner_fn(fn_args)
  File "/opt/venv/lib/python3.6/site-packages/models/estimator/model.py", line 399, in tuner_fn
    project_name='markdown_tuning')
  File "/opt/venv/lib/python3.6/site-packages/kerastuner/tuners/randomsearch.py", line 175, in __init__
    **kwargs)
  File "/opt/venv/lib/python3.6/site-packages/kerastuner/engine/multi_execution_tuner.py", line 58, in __init__
    oracle, hypermodel, **kwargs)
  File "/opt/venv/lib/python3.6/site-packages/kerastuner/engine/tuner.py", line 103, in __init__
    overwrite=overwrite)
  File "/opt/venv/lib/python3.6/site-packages/kerastuner/engine/base_tuner.py", line 91, in __init__
    self._populate_initial_space()
  File "/opt/venv/lib/python3.6/site-packages/kerastuner/engine/base_tuner.py", line 106, in _populate_initial_space
    self.hypermodel.build(hp)
  File "/opt/venv/lib/python3.6/site-packages/kerastuner/engine/hypermodel.py", line 65, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/opt/venv/lib/python3.6/site-packages/kerastuner/engine/hypermodel.py", line 122, in build
    'a valid Keras Model instance, found {}'.format(model))
RuntimeError: Model-building function did not return a valid Keras Model instance, found <tensorflow_estimator.python.estimator.canned.boosted_trees.BoostedTreesClassifier object at 0x7f9b0efea908>

**Comment by rmothukuru** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Also, please provide the TFX Version that you are using. Thanks!

**Comment by yantriks-edi-bice** [comment]
tfx==0.22.0

`
def _build_boosted_estimator(hparams: kerastuner.HyperParameters):
    ...
    return tf.estimator.BoostedTreesClassifier(...)

def tuner_fn(fn_args: FnArgs) -> TunerFnResult:
...
    tuner = kerastuner.RandomSearch(
        _build_boosted_estimator,
        hyperparameters=_get_boosting_hyperparameters(),
        ...)
`

**Comment by yantriks-edi-bice** [comment]
I believe the Tuner component does not support Estimators - line below shows keras-tuner expects keras.models.Model

https://github.com/keras-team/keras-tuner/blob/eaa4968d3cbcfc161752cd7425b0245379ac51f4/kerastuner/engine/hypermodel.py#L117

I know there's a Keras model to estimator path but am not aware of how to go the other way

**Comment by 1025KB** [comment]
current tuners provided by KerasTuner library don't support Estimator,
you need to implement your own Tuners inherited from kerastuner.BaseTuner (which is framework agnostic)

**Comment by yantriks-edi-bice** [comment]
Okay, thanks. Should I leave this open as a feature request or close?

**Comment by 1025KB** [comment]
This might be a feature request for KerasTuner repo, but I'm not sure if estimator is on their roadmap.

custom Tuner inherited from kerastuner.BaseTuner might be the preferred way

**Comment by yantriks-edi-bice** [comment]
Okay, thanks, closing then.
