### ISSUE TITLE
modelvalidator fails with KeyError 

### ISSUE THREAD

**Issue by rummens** [tensorflow/tfx#212]
Hello,

I am running the taxi_simple example on Kubeflow Pipelines. All components run fine, except for the modelvalidator. It fails with a KeyError (s. log). I looked into the file but I can't even find the line that fails (line 137 points to the comment section in executor.py). 

The intressting thing is that everything works fine locally on AirFlow.
Can you give me any hint what to look for?

# Log
Here is the log:
```
INFO:root:Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
INFO:root:Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
INFO:tensorflow:Using workflow id chicago-taxi-simple-9jxqj
INFO:tensorflow:Using workflow id chicago-taxi-simple-9jxqj
INFO:tensorflow:Starting Executor execution.
INFO:tensorflow:Starting Executor execution.
INFO:tensorflow:Inputs for Executor is: {"model": [{"artifact_type": {"name": "ModelExportPath", "properties": {"state": "STRING", "type_name": "STRING", "span": "INT", "name": "STRING", "split": "STRING"}}, "artifact": {"uri": "/pipeline_shared_data/pipelines/chicago_taxi_simple/trainer/output/chicago-taxi-simple-9jxqj/", "properties": {"type_name": {"stringValue": "ModelExportPath"}, "span": {"intValue": "1"}, "split": {"stringValue": ""}}}}], "examples": [{"artifact_type": {"name": "ExamplesPath", "properties": {"state": "STRING", "type_name": "STRING", "span": "INT", "name": "STRING", "split": "STRING"}}, "artifact": {"uri": "/pipeline_shared_data/pipelines/chicago_taxi_simple/csv_example_gen/examples/chicago-taxi-simple-9jxqj/train/", "properties": {"type_name": {"stringValue": "ExamplesPath"}, "span": {"intValue": "1"}, "split": {"stringValue": "train"}}}}, {"artifact_type": {"name": "ExamplesPath", "properties": {"state": "STRING", "type_name": "STRING", "span": "INT", "split": "STRING", "name": "STRING"}}, "artifact": {"uri": "/pipeline_shared_data/pipelines/chicago_taxi_simple/csv_example_gen/examples/chicago-taxi-simple-9jxqj/eval/", "properties": {"type_name": {"stringValue": "ExamplesPath"}, "span": {"intValue": "1"}, "split": {"stringValue": "eval"}}}}]}
INFO:tensorflow:Inputs for Executor is: {"model": [{"artifact_type": {"name": "ModelExportPath", "properties": {"state": "STRING", "type_name": "STRING", "span": "INT", "name": "STRING", "split": "STRING"}}, "artifact": {"uri": "/pipeline_shared_data/pipelines/chicago_taxi_simple/trainer/output/chicago-taxi-simple-9jxqj/", "properties": {"type_name": {"stringValue": "ModelExportPath"}, "span": {"intValue": "1"}, "split": {"stringValue": ""}}}}], "examples": [{"artifact_type": {"name": "ExamplesPath", "properties": {"state": "STRING", "type_name": "STRING", "span": "INT", "name": "STRING", "split": "STRING"}}, "artifact": {"uri": "/pipeline_shared_data/pipelines/chicago_taxi_simple/csv_example_gen/examples/chicago-taxi-simple-9jxqj/train/", "properties": {"type_name": {"stringValue": "ExamplesPath"}, "span": {"intValue": "1"}, "split": {"stringValue": "train"}}}}, {"artifact_type": {"name": "ExamplesPath", "properties": {"state": "STRING", "type_name": "STRING", "span": "INT", "split": "STRING", "name": "STRING"}}, "artifact": {"uri": "/pipeline_shared_data/pipelines/chicago_taxi_simple/csv_example_gen/examples/chicago-taxi-simple-9jxqj/eval/", "properties": {"type_name": {"stringValue": "ExamplesPath"}, "span": {"intValue": "1"}, "split": {"stringValue": "eval"}}}}]}
INFO:tensorflow:Outputs for Executor is: {"blessing": [{"artifact_type": {"name": "ModelBlessingPath", "properties": {"state": "STRING", "type_name": "STRING", "span": "INT", "split": "STRING", "name": "STRING"}}, "artifact": {"uri": "/pipeline_shared_data/pipelines/chicago_taxi_simple/model_validator/blessing/chicago-taxi-simple-9jxqj/", "properties": {"type_name": {"stringValue": "ModelBlessingPath"}, "span": {"intValue": "1"}, "split": {"stringValue": ""}}}}]}
INFO:tensorflow:Outputs for Executor is: {"blessing": [{"artifact_type": {"name": "ModelBlessingPath", "properties": {"state": "STRING", "type_name": "STRING", "span": "INT", "split": "STRING", "name": "STRING"}}, "artifact": {"uri": "/pipeline_shared_data/pipelines/chicago_taxi_simple/model_validator/blessing/chicago-taxi-simple-9jxqj/", "properties": {"type_name": {"stringValue": "ModelBlessingPath"}, "span": {"intValue": "1"}, "split": {"stringValue": ""}}}}]}
INFO:tensorflow:Execution properties for Executor is: {"log_root": "/pipeline_shared_data/pipelines/logs", "blessed_model_id": null, "latest_blessed_model_id": null, "blessed_model": null, "latest_blessed_model": null, "output_dir": "/pipeline_shared_data/pipelines/chicago_taxi_simple"}
INFO:tensorflow:Execution properties for Executor is: {"log_root": "/pipeline_shared_data/pipelines/logs", "blessed_model_id": null, "latest_blessed_model_id": null, "blessed_model": null, "latest_blessed_model": null, "output_dir": "/pipeline_shared_data/pipelines/chicago_taxi_simple"}
Traceback (most recent call last):
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 102, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 98, in main
    runner.run()
  File "/tfx-src/tfx/orchestration/kubeflow/container_runners.py", line 103, in run
    self._exec_properties)
  File "/tfx-src/tfx/components/model_validator/executor.py", line 137, in Do
    types.get_single_uri(output_dict['results']), '.temp')
KeyError: 'results'
```

# Inputs
csvexamplegen-examples:
`[{"artifact_type": {"name": "ExamplesPath", "properties": {"state": "STRING", "type_name": "STRING", "span": "INT", "split": "STRING", "name": "STRING"}}, "artifact": {"uri": "/pipeline_shared_data/pipelines/chicago_taxi_simple/csv_example_gen/examples/chicago-taxi-simple-9jxqj/train/", "properties": {"type_name": {"stringValue": "ExamplesPath"}, "span": {"intValue": "1"}, "split": {"stringValue": "train"}}}}, {"artifact_type": {"name": "ExamplesPath", "properties": {"state": "STRING", "type_name": "STRING", "span": "INT", "name": "STRING", "split": "STRING"}}, "artifact": {"uri": "/pipeline_shared_data/pipelines/chicago_taxi_simple/csv_example_gen/examples/chicago-taxi-simple-9jxqj/eval/", "properties": {"type_name": {"stringValue": "ExamplesPath"}, "span": {"intValue": "1"}, "split": {"stringValue": "eval"}}}}]`

trainer-output:
`[{"artifact_type": {"name": "ModelExportPath", "properties": {"state": "STRING", "type_name": "STRING", "span": "INT", "split": "STRING", "name": "STRING"}}, "artifact": {"uri": "/pipeline_shared_data/pipelines/chicago_taxi_simple/trainer/output/chicago-taxi-simple-9jxqj/", "properties": {"type_name": {"stringValue": "ModelExportPath"}, "span": {"intValue": "1"}, "split": {"stringValue": ""}}}}]`

**Comment by rummens** [comment]
Additional information, the pipeline data is shared via PV since this seems to be only way to share stuff outside of GCP because of the [Beam Limatation](https://issues.apache.org/jira/browse/BEAM-2572).

**Comment by 1025KB** [comment]
Hi, we recently deleted 'results' from modelvalidator, could you check if your code are synced to same version

**Comment by rummens** [comment]
I had the same idea yesterday and started a [docker build](https://github.com/tensorflow/tfx/tree/master/tfx/tools/docker) from the master. It fixed the issue, this means however that the current release on pip for 1.13.0 does not work propably. 

Also I had to remove the license script from the docker build becaused it failed, missing some licenes for third party software. Nothing terrible, just for your information.

**Comment by zhitaoli** [comment]
Thanks for the info. We recently added a continuous build for the image building process. If the license script fails more frequently, we'll look into alternative ways to do that.

cc + @neuromage
