### ISSUE TITLE
Broken pipe using Trainer on AI Platform

### ISSUE THREAD

**Issue by ColinCampbell-GBI** [tensorflow/tfx#2182]
When running the Trainer component using the AI Platform executor I occasionally get a `BrokenPipeError` when it's polling for job status. I've only noticed it happening when the job was successful on the backend, but that may be a coincidence. 

This is using tfx 0.22.0

```
Traceback (most recent call last):
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 360, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 353, in main
    execution_info = launcher.launch()
  File "/usr/local/lib/python3.6/dist-packages/tfx/orchestration/launcher/base_component_launcher.py", line 205, in launch
    execution_decision.exec_properties)
  File "/usr/local/lib/python3.6/dist-packages/tfx/orchestration/launcher/in_process_component_launcher.py", line 67, in _run_executor
    executor.Do(input_dict, output_dict, exec_properties)
  File "/usr/local/lib/python3.6/dist-packages/tfx/extensions/google_cloud_ai_platform/trainer/executor.py", line 86, in Do
    job_id)
  File "/usr/local/lib/python3.6/dist-packages/tfx/extensions/google_cloud_ai_platform/runner.py", line 181, in start_aip_training
    response = request.execute()
  File "/usr/local/lib/python3.6/dist-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/googleapiclient/http.py", line 901, in execute
    headers=self.headers,
  File "/usr/local/lib/python3.6/dist-packages/googleapiclient/http.py", line 204, in _retry_request
    raise exception
  File "/usr/local/lib/python3.6/dist-packages/googleapiclient/http.py", line 177, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/google_auth_httplib2.py", line 190, in request
    self._request, method, uri, request_headers)
  File "/usr/local/lib/python3.6/dist-packages/google/auth/credentials.py", line 124, in before_request
    self.refresh(request)
  File "/usr/local/lib/python3.6/dist-packages/google/auth/compute_engine/credentials.py", line 96, in refresh
    self._retrieve_info(request)
  File "/usr/local/lib/python3.6/dist-packages/google/auth/compute_engine/credentials.py", line 77, in _retrieve_info
    request, service_account=self._service_account_email
  File "/usr/local/lib/python3.6/dist-packages/google/auth/compute_engine/_metadata.py", line 226, in get_service_account_info
    recursive=True,
  File "/usr/local/lib/python3.6/dist-packages/google/auth/compute_engine/_metadata.py", line 144, in get
    response = request(url=url, method="GET", headers=_METADATA_HEADERS)
  File "/usr/local/lib/python3.6/dist-packages/google_auth_httplib2.py", line 117, in __call__
    url, method=method, body=body, headers=headers, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/httplib2/__init__.py", line 1994, in request
    cachekey,
  File "/usr/local/lib/python3.6/dist-packages/httplib2/__init__.py", line 1651, in _request
    conn, request_uri, method, body, headers
  File "/usr/local/lib/python3.6/dist-packages/httplib2/__init__.py", line 1558, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib/python3.6/http/client.py", line 1264, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1310, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1259, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 998, in send
    self.sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe
```

It seems like the google api client used by the Executor supports setting a number of retries, so I would suggest making it possible to set the retry count through the custom_config.

**Comment by wihanbooyse** [comment]
This seems to happen consistently on long-running training jobs using TFX 0.22.1 + AI Platform Training on GCP AI Platform Pipelines.

**Comment by mustafaghaliUnity** [comment]
any update on this ? the issue still occur in my side when I have a relatively long-running training job

**Comment by numerology** [comment]
@1025KB Do you mind taking a look and routing to proper people? Looks like this flakiness is still happening

**Comment by mustafaghaliUnity** [comment]
I think I was able to resolve the issue by applying K8s secret to authenticate the component where this failure happens using kfp gcp extension 
`task_op.apply(gcp.use_gcp_secret("your-K8s-secret")) `

**Comment by gowthamkpr** [comment]
@ColinCampbell-GBI Please use K8s secret to authenticate the component where this failure happens using kfp gcp extension as mentioned [above](https://github.com/tensorflow/tfx/issues/2182#issuecomment-833790105) and this should solve your issue. Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 2 weeks. Please reopen if you'd like to work on this further.
