### ISSUE TITLE
Changing preprocessing_fn does not invalidate Transform cache

### ISSUE THREAD

**Issue by yantriks-edi-bice** [tensorflow/tfx#2247]
I modified the preprocessing_fn used by the Transform component adding more keys/columns to the output.

Executing the pipeline on Kubeflow bypasses all components including Transform.

Downstream Tuner component now fails with the following error which I believe is due to the cached transform output which does not contain the newly added keys/columns:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.6/site-packages/kerastuner/engine/hypermodel.py", line 105, in build
    model = self.hypermodel.build(hp)
  File "/opt/venv/lib/python3.6/site-packages/models/keras/model.py", line 156, in _build_keras_model
    hparams=hparams,
  File "/opt/venv/lib/python3.6/site-packages/models/keras/model.py", line 184, in _wide_and_deep_classifier
    deep = tf.keras.layers.DenseFeatures(deep_columns)(input_layers)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 922, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 262, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 418, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 346, in _call_unconverted
    return f(*args, **kwargs)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow/python/feature_column/dense_features.py", line 145, in call
    self._state_manager)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow/python/feature_column/feature_column_v2.py", line 3276, in get_dense_tensor
    transformation_cache, state_manager)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow/python/feature_column/feature_column_v2.py", line 4260, in get_sparse_tensors
    transformation_cache.get(self, state_manager), None)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow/python/feature_column/feature_column_v2.py", line 2679, in get
    transformed = column.transform_feature(self, state_manager)
  File "/opt/venv/lib/python3.6/site-packages/tensorflow/python/feature_column/feature_column_v2.py", line 4206, in transform_feature
    feature_tensors.append(transformation_cache.get(key, state_manager))
  File "/opt/venv/lib/python3.6/site-packages/tensorflow/python/feature_column/feature_column_v2.py", line 2671, in get
    raise ValueError('Feature {} is not in features dictionary.'.format(key))
ValueError: Feature CLASS is not in features dictionary.

**Comment by gowthamkpr** [comment]
@yantriks-edi-bice Can you please share the reproducible code for us to reproduce this issue? Thanks!

**Comment by dataScientist11** [comment]
I'm having the same issue - how to solve?

**Comment by edi-bice-by** [comment]
@daikeshi change the function name and any references to it
