### ISSUE TITLE
CsvExampleGen with enable_cache=True causes MySql syntax error

### ISSUE THREAD

**Issue by johnnytshi** [tensorflow/tfx#2448]
Using MySQL image: gcr.io/ml-pipeline/mysql:5.6

Running the Taxi example with:

metadata.mysql_metadata_connection_config(
    host='addr', 
    port=3306, 
    database='mlmd', 
    username='root',
    password='ggnr')

Resutls in syntax error. NOTE: without enable_cache, everything works

*** Reading local file: /home/j/bin/airflow/logs/taxi/CsvExampleGen/2020-09-09T07:27:33.779458+00:00/1.log
[2020-09-09 00:27:40,787] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: taxi.CsvExampleGen 2020-09-09T07:27:33.779458+00:00 [queued]>
[2020-09-09 00:27:40,807] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: taxi.CsvExampleGen 2020-09-09T07:27:33.779458+00:00 [queued]>
[2020-09-09 00:27:40,807] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-09-09 00:27:40,807] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-09-09 00:27:40,807] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-09-09 00:27:40,821] {taskinstance.py:901} INFO - Executing <Task(AirflowComponent): CsvExampleGen> on 2020-09-09T07:27:33.779458+00:00
[2020-09-09 00:27:40,827] {standard_task_runner.py:54} INFO - Started process 431710 to run task
[2020-09-09 00:27:40,846] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'taxi', 'CsvExampleGen', '2020-09-09T07:27:33.779458+00:00', '--job_id', '5', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/taxi/taxi_pipeline.py', '--cfg_path', '/tmp/tmpr445jlgc']
[2020-09-09 00:27:40,846] {standard_task_runner.py:78} INFO - Job 5: Subtask CsvExampleGen
[2020-09-09 00:27:40,884] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: taxi.CsvExampleGen 2020-09-09T07:27:33.779458+00:00 [running]> j-server
[2020-09-09 00:27:40,914] {base_component_launcher.py:195} INFO - Running driver for CsvExampleGen
[2020-09-09 00:27:40,920] {metadata_store.py:66} INFO - MetadataStore with DB connection initialized
[2020-09-09 00:27:40,921] {utils.py:459} INFO - select span and version = (0, None)
[2020-09-09 00:27:40,921] {utils.py:468} INFO - latest span and version = (0, None)
[2020-09-09 00:27:40,939] {metadata_store.py:1183} WARNING - mlmd client InternalError: mysql_query failed: errno: 1064, error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1
[2020-09-09 00:27:40,939] {taskinstance.py:1150} ERROR - mysql_query failed: errno: 1064, error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1
Traceback (most recent call last):
  File "/home/j/bin/miniconda3/envs/tf2/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/j/bin/miniconda3/envs/tf2/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/j/bin/miniconda3/envs/tf2/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/j/bin/miniconda3/envs/tf2/lib/python3.7/site-packages/tfx/orchestration/airflow/airflow_component.py", line 79, in _airflow_component_launcher
    launcher.launch()
  File "/home/j/bin/miniconda3/envs/tf2/lib/python3.7/site-packages/tfx/orchestration/launcher/base_component_launcher.py", line 197, in launch
    self._exec_properties)
  File "/home/j/bin/miniconda3/envs/tf2/lib/python3.7/site-packages/tfx/orchestration/launcher/base_component_launcher.py", line 166, in _run_driver
    component_info=self._component_info)
  File "/home/j/bin/miniconda3/envs/tf2/lib/python3.7/site-packages/tfx/components/base/base_driver.py", line 298, in pre_execution
    component_info=component_info)
  File "/home/j/bin/miniconda3/envs/tf2/lib/python3.7/site-packages/tfx/orchestration/metadata.py", line 795, in get_cached_outputs
    list(set(itertools.chain.from_iterable(input_ids.values())))):
  File "/home/j/bin/miniconda3/envs/tf2/lib/python3.7/site-packages/ml_metadata/metadata_store/metadata_store.py", line 1129, in get_events_by_artifact_ids
    self._call('GetEventsByArtifactIDs', request, response)
  File "/home/j/bin/miniconda3/envs/tf2/lib/python3.7/site-packages/ml_metadata/metadata_store/metadata_store.py", line 140, in _call
    return self._call_method(method_name, request, response)
  File "/home/j/bin/miniconda3/envs/tf2/lib/python3.7/site-packages/ml_metadata/metadata_store/metadata_store.py", line 161, in _call_method
    self._swig_call(swig_method, request, response)
  File "/home/j/bin/miniconda3/envs/tf2/lib/python3.7/site-packages/ml_metadata/metadata_store/metadata_store.py", line 193, in _swig_call
    raise _make_exception(error_message.decode('utf-8'), status_code)
ml_metadata.errors.InternalError: mysql_query failed: errno: 1064, error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1
[2020-09-09 00:27:40,941] {taskinstance.py:1194} INFO - Marking task as FAILED. dag_id=taxi, task_id=CsvExampleGen, execution_date=20200909T072733, start_date=20200909T072740, end_date=20200909T072740
[2020-09-09 00:27:41,774] {local_task_job.py:102} INFO - Task exited with return code 1

**Comment by rmothukuru** [comment]
@johnnytshi, 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by johnnytshi** [comment]
@rmothukuru 
Thanks for the followup. Sure thing.

You can try with the **airflow_workshop** example:

https://github.com/tensorflow/tfx/blob/548ca2a98386fd7d81b4fe18671b00c3964adc53/tfx/examples/airflow_workshop/setup/dags/taxi_pipeline_solution.py#L183

In the example, it uses sqlite. I simply switched to mysql, e.g.:

metadata.mysql_metadata_connection_config(
  host='addr',
  port=3306,
  database='mlmd',
  username='root',
  password='ggnr')

After that, I ran into the above error, unless I remove "enable_cache=True" on line 182.

All the best!

Johnny

**Comment by gowthamkpr** [comment]
@johnnytshi Is this still an error. Can you explain the usecase where you are trying to use this. Please check with the latest version of tfx and tensorflow and let me know if the issue still persists. Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 2 weeks. Please reopen it if you have any updates. Thanks!!
