### ISSUE TITLE
Incompatible y_pred and y_true shapes with Categorical Accuracy within Evaluator (Op:Equal)

### ISSUE THREAD

**Issue by HarryDunham** [tensorflow/tfx#2614]
## Background
AirFlow pipeline based off Chicago Taxi workshop and BERT blogpost: [url](https://www.tensorflow.org/tfx/tutorials/tfx/airflow_workshop) and [url 2](https://blog.tensorflow.org/2020/03/part-1-fast-scalable-and-accurate-nlp-tensorflow-deploying-bert.html), however customized for an NLP task with a different dataset. The dataset comprises of two features `sample`, `sample_len`, with an associated string encoded `label`.  During the Transform step, the `label` is transformed from a string to a one-hot encoded tensor. This means the Evaluator must use `transform.outputs['transformed_examples']` rather than `examples=example_gen.outputs['examples']`, since the labels undergo preprocessing.

Additionally, since this is a BERT based model, the `samples` are converted to prototypical features `input_word_ids`, `input_type_ids`, `input_mask` during the transform step, following near identical steps as the blogpost, while `sample_len` features are untouched.

Versions:
```{txt}
tensorflow==2.3.0
tfx==0.24.0
tensorflow-hub
tensorflow-text==2.3.0
```

## Setup
```{python}
eval_config = tfma.EvalConfig(
    model_specs=[tfma.ModelSpec(label_key='label')],
    slicing_specs=[tfma.SlicingSpec()],
    metrics_specs=[
        tfma.MetricsSpec(metrics=[
            tfma.MetricConfig(
                class_name='CategoricalAccuracy',
                threshold=tfma.MetricThreshold(
                    value_threshold=tfma.GenericValueThreshold(
                        lower_bound={'value': 0.1}),
                    change_threshold=tfma.GenericChangeThreshold(
                        direction=tfma.MetricDirection.HIGHER_IS_BETTER,
                        absolute={'value': 0.01}))
                    )
        ])
    ]
)

model_analyzer = Evaluator(
    # cannot use example_gen's outputs
    # examples=example_gen.outputs['examples'],
    examples=transform.outputs['transformed_examples'],
    model=trainer.outputs['model'],
    baseline_model=model_resolver.outputs['model'],
    eval_config=eval_config
)
```

Here's the associated serving function/signature:
```{python}
def _get_serve_tf_examples_fn(model, tf_transform_output):
    """Returns a function that parses a serialized tf.Example and applies TFT."""

    @tf.function
    def serve_tf_examples_fn(serialized_tf_examples):
        """Returns the output to be used in the serving signature."""
        feature_spec = tf_transform_output.transformed_feature_spec()
        feature_spec.pop(_LABEL_KEY)

        parsed_features = tf.io.parse_example(serialized_tf_examples,
                                              feature_spec)


        return model(parsed_features)

    return serve_tf_examples_fn
```
Noting here, that I'm not including the transform steps and using `tf_transform_output.transformed_feature_spec()` since evaluation will require the preprocessed one-hot encoded labels rather than the string formatted labels.

And the `run_fn` that is called during training:
```{python}
def run_fn(fn_args: TrainerFnArgs):
    """Train the model based on given args.

    Args:
      fn_args: Holds args used to train the model as name/value pairs.
    """
    tf_transform_output = tft.TFTransformOutput(fn_args.transform_output)

    train_dataset = _input_fn(fn_args.train_files, tf_transform_output, 32)
    eval_dataset = _input_fn(fn_args.eval_files, tf_transform_output, 32)

    mirrored_strategy = tf.distribute.MirroredStrategy()
    with mirrored_strategy.scope():
        model = get_model(tf_transform_output=tf_transform_output)


    model.fit(
        train_dataset,
        steps_per_epoch=fn_args.train_steps,
        validation_data=eval_dataset,
        validation_steps=fn_args.eval_steps)

    signatures = {
        'serving_default':
            _get_serve_tf_examples_fn(model,
                                      tf_transform_output).get_concrete_function(
                tf.TensorSpec(
                    shape=[None],
                    dtype=tf.string,
                    name='examples')),
    }
    model.save(fn_args.serving_model_dir, save_format='tf',
               signatures=signatures)

```
The model trains without errors and boasts similar results to it's non-TFX counterpart.

## Error
This yields a `Op:Equal` error where the `y_pred` and `y_true` have differing dimensions during evaluation.
```
  File "/root/.local/lib/python3.7/site-packages/apache_beam/runners/worker/sdk_worker.py", line 256, in _execute
    response = task()
  File "/root/.local/lib/python3.7/site-packages/apache_beam/runners/worker/sdk_worker.py", line 313, in <lambda>
    lambda: self.create_worker().do_instruction(request), request)
  File "/root/.local/lib/python3.7/site-packages/apache_beam/runners/worker/sdk_worker.py", line 483, in do_instruction
    getattr(request, request_type), request.instruction_id)
  File "/root/.local/lib/python3.7/site-packages/apache_beam/runners/worker/sdk_worker.py", line 518, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/root/.local/lib/python3.7/site-packages/apache_beam/runners/worker/bundle_processor.py", line 988, in process_bundle
    op.finish()
  File "apache_beam/runners/worker/operations.py", line 999, in apache_beam.runners.worker.operations.PGBKCVOperation.finish
  File "apache_beam/runners/worker/operations.py", line 1002, in apache_beam.runners.worker.operations.PGBKCVOperation.finish
  File "apache_beam/runners/worker/operations.py", line 1010, in apache_beam.runners.worker.operations.PGBKCVOperation.output_key
  File "/root/.local/lib/python3.7/site-packages/tensorflow_model_analysis/evaluators/metrics_and_plots_evaluator_v2.py", line 349, in compact
    return super(_ComputationsCombineFn, self).compact(accumulator)
  File "/root/.local/lib/python3.7/site-packages/apache_beam/transforms/combiners.py", line 745, in compact
    return [c.compact(a) for c, a in zip(self._combiners, accumulator)]
  File "/root/.local/lib/python3.7/site-packages/apache_beam/transforms/combiners.py", line 745, in <listcomp>
    return [c.compact(a) for c, a in zip(self._combiners, accumulator)]
  File "/root/.local/lib/python3.7/site-packages/tensorflow_model_analysis/metrics/tf_metric_wrapper.py", line 588, in compact
    self._process_batch(accumulator)
  File "/root/.local/lib/python3.7/site-packages/tensorflow_model_analysis/metrics/tf_metric_wrapper.py", line 548, in _process_batch
    metric.update_state(*inputs)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/metrics_utils.py", line 90, in decorated
    update_op = update_state_fn(*args, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/keras/metrics.py", line 176, in update_state_fn
    return ag_update_state(*args, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 255, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 532, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 339, in _call_unconverted
    return f(*args, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/keras/metrics.py", line 612, in update_state
    matches = ag_fn(y_true, y_pred, **self._fn_kwargs)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/keras/metrics.py", line 3267, in categorical_accuracy
    math_ops.argmax(y_true, axis=-1), math_ops.argmax(y_pred, axis=-1)),
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py", line 1614, in equal
    return gen_math_ops.equal(x, y, name=name)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 3209, in equal
    _ops.raise_from_not_ok_status(e, name)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [161] vs. [161,128] [Op:Equal]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/root/.local/lib/python3.7/site-packages/tfx/orchestration/airflow/airflow_component.py", line 79, in _airflow_component_launcher
    launcher.launch()
  File "/root/.local/lib/python3.7/site-packages/tfx/orchestration/launcher/base_component_launcher.py", line 205, in launch
    execution_decision.exec_properties)
  File "/root/.local/lib/python3.7/site-packages/tfx/orchestration/launcher/in_process_component_launcher.py", line 67, in _run_executor
    executor.Do(input_dict, output_dict, exec_properties)
  File "/root/.local/lib/python3.7/site-packages/tfx/components/evaluator/executor.py", line 260, in Do
    tensor_adapter_config=tensor_adapter_config))
  File "/root/.local/lib/python3.7/site-packages/apache_beam/pipeline.py", line 555, in __exit__
    self.result = self.run()
  File "/root/.local/lib/python3.7/site-packages/apache_beam/pipeline.py", line 534, in run
    return self.runner.run_pipeline(self, self._options)
  File "/root/.local/lib/python3.7/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 176, in run_pipeline
    pipeline.to_runner_api(default_environment=self._default_environment))
  File "/root/.local/lib/python3.7/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 186, in run_via_runner_api
    return self.run_stages(stage_context, stages)
  File "/root/.local/lib/python3.7/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 344, in run_stages
    bundle_context_manager,
  File "/root/.local/lib/python3.7/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 523, in _run_stage
    bundle_manager)
  File "/root/.local/lib/python3.7/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 561, in _run_bundle
    data_input, data_output, input_timers, expected_timer_output)
  File "/root/.local/lib/python3.7/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 945, in process_bundle
    timer_inputs)):
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/root/.local/lib/python3.7/site-packages/apache_beam/utils/thread_pool_executor.py", line 44, in run
    self._future.set_result(self._fn(*self._fn_args, **self._fn_kwargs))
  File "/root/.local/lib/python3.7/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 941, in execute
    dry_run)
  File "/root/.local/lib/python3.7/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 880, in process_bundle
    raise RuntimeError(result.error)
RuntimeError: Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/apache_beam/runners/worker/sdk_worker.py", line 256, in _execute
    response = task()
  File "/root/.local/lib/python3.7/site-packages/apache_beam/runners/worker/sdk_worker.py", line 313, in <lambda>
    lambda: self.create_worker().do_instruction(request), request)
  File "/root/.local/lib/python3.7/site-packages/apache_beam/runners/worker/sdk_worker.py", line 483, in do_instruction
    getattr(request, request_type), request.instruction_id)
  File "/root/.local/lib/python3.7/site-packages/apache_beam/runners/worker/sdk_worker.py", line 518, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/root/.local/lib/python3.7/site-packages/apache_beam/runners/worker/bundle_processor.py", line 988, in process_bundle
    op.finish()
  File "apache_beam/runners/worker/operations.py", line 999, in apache_beam.runners.worker.operations.PGBKCVOperation.finish
  File "apache_beam/runners/worker/operations.py", line 1002, in apache_beam.runners.worker.operations.PGBKCVOperation.finish
  File "apache_beam/runners/worker/operations.py", line 1010, in apache_beam.runners.worker.operations.PGBKCVOperation.output_key
  File "/root/.local/lib/python3.7/site-packages/tensorflow_model_analysis/evaluators/metrics_and_plots_evaluator_v2.py", line 349, in compact
    return super(_ComputationsCombineFn, self).compact(accumulator)
  File "/root/.local/lib/python3.7/site-packages/apache_beam/transforms/combiners.py", line 745, in compact
    return [c.compact(a) for c, a in zip(self._combiners, accumulator)]
  File "/root/.local/lib/python3.7/site-packages/apache_beam/transforms/combiners.py", line 745, in <listcomp>
    return [c.compact(a) for c, a in zip(self._combiners, accumulator)]
  File "/root/.local/lib/python3.7/site-packages/tensorflow_model_analysis/metrics/tf_metric_wrapper.py", line 588, in compact
    self._process_batch(accumulator)
  File "/root/.local/lib/python3.7/site-packages/tensorflow_model_analysis/metrics/tf_metric_wrapper.py", line 548, in _process_batch
    metric.update_state(*inputs)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/metrics_utils.py", line 90, in decorated
    update_op = update_state_fn(*args, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/keras/metrics.py", line 176, in update_state_fn
    return ag_update_state(*args, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 255, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 532, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 339, in _call_unconverted
    return f(*args, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/keras/metrics.py", line 612, in update_state
    matches = ag_fn(y_true, y_pred, **self._fn_kwargs)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/keras/metrics.py", line 3267, in categorical_accuracy
    math_ops.argmax(y_true, axis=-1), math_ops.argmax(y_pred, axis=-1)),
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py", line 1614, in equal
    return gen_math_ops.equal(x, y, name=name)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 3209, in equal
    _ops.raise_from_not_ok_status(e, name)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [161] vs. [161,128] [Op:Equal]
```

To confirm model predictive functionality:
```{python}
model = tf.saved_model.load(tf_trainer_model_dir)
predict_fn = model.signatures["serving_default"]
example = tf.train.Example(features=tf.train.Features(feature={'input_mask': _int64_feature(input_mask.numpy()), 'input_type_ids': _int64_feature(input_type_ids.numpy()), 'input_word_ids': _int64_feature(input_word_ids.numpy()), 'sample_len': _int64_feature([33])}))
serialized_example = example.SerializeToString()
predict_fn(tf.constant([serialized_example]))
Out[1]: 
{'output_0': <tf.Tensor: shape=(1, 128, 45), dtype=float32, numpy=
 array([[[6.15841508e-01, 4.20771772e-03, 1.97123252e-02, ...,
          7.54426350e-04, 6.01695734e-04, 1.96485620e-04],
         [7.56165922e-01, 1.99102634e-03, 1.47846062e-02, ...,
          1.06433974e-04, 1.21602083e-04, 8.47283954e-05],
         [6.98516786e-01, 2.70646694e-03, 1.29902167e-02, ...,
          1.52176988e-04, 1.58448180e-04, 1.17122974e-04],
         ...,
         [2.28035785e-02, 2.23874729e-02, 2.27023736e-02, ...,
          2.18944829e-02, 2.17889063e-02, 2.17460468e-02],
```
Which has the expected output shape of `(batch_size, sequence_length, num_classes)`

I also took it a step further by grabbing the corresponding label for that sample and defined it as y_true:
```{python}
y_true
Out[2]: 
<tf.Tensor: shape=(1, 128, 45), dtype=int64, numpy=
array([[[1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]])>
y_pred = predict_fn(tf.constant([serialized_example]))['output_0']
m = tf.keras.metrics.CategoricalAccuracy()
m.update_state(y_true, y_pred)
m.result().numpy()
Out[3]: 0.859375
```
 I'm honestly perplexed as I'm not even sure how tensors of shapes `(batch_size,)` or `(batch_size, sequence_length,)` were produced during evaluation since the error is complaining about shapes `(161,)` vs. `(161, 128)`...

`y_true` having shape `(161,)` would imply that the label isn't actually in it's transformed one-hot encoded format and still in its raw string format, however the examples passed into the Evaluator are `transform.outputs['transformed_examples']`, therefore I have relatively little idea what the issue is.

**Comment by HarryDunham** [comment]
Followed my inclination about transform producing the incorrect label and found the label shapes do not match from transform. Therefore, it is not a bug and instead transform issue and closing the issue.

**Comment by HarryDunham** [comment]
I may have closed this prematurely, as I thought it was related to the label's shape after the transform step. However, I'm actually unsure whether the issue is related to the shape/representation of the labels after the transform step.
Using the provided method from the blogpost:
```{python}
# Get the list of files in this directory (all compressed TFRecord files)
tfrecord_folders = [os.path.join(train_uri, name) for name in os.listdir(train_uri)]
tfrecord_filenames = []
for tfrecord_folder in tfrecord_folders:
    for name in os.listdir(tfrecord_folder):
        tfrecord_filenames.append(os.path.join(tfrecord_folder, name))


# Create a TFRecordDataset to read these files
dataset = tf.data.TFRecordDataset(tfrecord_filenames, compression_type="GZIP")

for tfrecord in dataset.take(1):
    serialized_example = tfrecord.numpy()
    example = ExampleToNumpyDict(serialized_example)
    pp.pprint(example)
```
yields:
```
{'input_mask': array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 'input_type_ids': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 'input_word_ids': array([  101,  1860,   112,  4702,  1106,  1103,  1735,  1913,   112,
       27431,  3914, 14651,   163,  1163,  1113,  9031, 11060,  1431,
        4417,  8892,  1121,  2182,  1168,  1190,  2855,  1235,  1103,
        3812,  5566,  1108, 27830,   102,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0]),
 'label': array([1, 0, 0, ..., 0, 0, 0]),
 'sample_len': array([30])}
```
Inpsecting label shows that it is in a flattened format (5760 = 128 * 45):
```
label_e = example["label"]
label_e.shape
Out[1]: (5760,)
label_r = tf.reshape(label_e, [128, 45])
label_r
Out[2]: 
<tf.Tensor: shape=(128, 45), dtype=int64, numpy=
array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])>
```
So I'm unsure whether the dimensionality issue is related to the fact that the label has been flattened after the transform step?
Inspecting the `schema.pbtxt` under the `transformed_metadata` directory shows the correct shape for the label:
```
feature {
  name: "input_mask"
  type: INT
  presence {
    min_fraction: 1.0
  }
  shape {
    dim {
      size: 128
    }
  }
}
feature {
  name: "input_type_ids"
  type: INT
  presence {
    min_fraction: 1.0
  }
  shape {
    dim {
      size: 128
    }
  }
}
feature {
  name: "input_word_ids"
  type: INT
  presence {
    min_fraction: 1.0
  }
  shape {
    dim {
      size: 128
    }
  }
}
feature {
  name: "label"
  type: INT
  presence {
    min_fraction: 1.0
  }
  shape {
    dim {
      size: 128
    }
    dim {
      size: 45
    }
  }
}
feature {
  name: "sample_len"
  type: INT
  presence {
    min_fraction: 1.0
  }
  shape {
  }
}
```

And using `tf.compat.v1.Print()` during the transform step, I was able to confirm that the labels which are returned with the `preprocessing_fn` are in the proper `(batch_size, sequence_length, num_classes)` representation.

So is the issue related to the flattened label which was seen through inspection via the provided code snippet from the BERT blogpost? If that is the issue, I have confirmed that the returned label from the transform step is not in a flattened representation. Or is there another unknown issue at play here that causes this incompatible shapes issue?

**Comment by HarryDunham** [comment]
Could [this](https://github.com/tensorflow/tfx/blob/40ef09c8946272cfadf181198f1a5830eb6432d4/tfx/components/evaluator/executor.py#L251) coupled with the fact that this is an LSTM model with return sequences enabled be the cause of the differing label dimensions in the categorical accuracy or something along those lines? This is purely speculative and an uneducated guess as I'm not entirely familiar with beam or the components involved. Or is this possibly a user error on my part?

**Comment by gowthamkpr** [comment]
@HarryDunham This is a user error not from tfx. Were you able to solve this issue?

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 2 weeks. Please reopen it if you have any updates. Thanks!!

**Comment by shayanzamani** [comment]
@HarryDunham 
Hi Harry,
Here you mentioned that:
>  During the Transform step, the label is transformed from a string to a one-hot encoded tensor. This means the Evaluator must use transform.outputs['transformed_examples'] rather than examples=example_gen.outputs['examples'], since the labels undergo preprocessing.
Doesn't Evaluator get to know about the transform function given the tranform_feature signature? I think there shouldn't be any problems passing the example_gen outputs.
