### ISSUE TITLE
Generating source sdist for TFX components in Kubeflow

### ISSUE THREAD

**Issue by casassg** [tensorflow/tfx#2839]
As a user, I would like to easily generate a python sdist package that can be used by all 
 Beam components (dependencies for portable runners in Dataflow/Spark/Flink) TFX components when running on Kubeflow.

Issue I have is generating the sdist locally then its not accessible by the worker pods. It needs to be embedded into the Kubeflow image.  A potential solution is to add the  source dist to the image and point `beam_pipeline_args` to the file in the image. 

I initially thought that uploading the sdist to GCS would allow me to avoid having to bake it into the image and just reference to `--extra_package=gs://some_bucket/workspaces/gcasassaez/tfx-tmp/tfx_ephemeral-0.24.1.tar.gz`, but it errors out:
```
INFO:apache_beam.runners.portability.stager:Downloading extra package: gs://some_bucket/workspaces/gcasassaez/tfx-tmp/tfx_ephemeral-0.24.1.tar.gz locally before staging
Traceback (most recent call last):
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 360, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 353, in main
    execution_info = launcher.launch()
  File "/tfx-src/tfx/orchestration/launcher/base_component_launcher.py", line 205, in launch
    execution_decision.exec_properties)
  File "/tfx-src/tfx/orchestration/launcher/in_process_component_launcher.py", line 67, in _run_executor
    executor.Do(input_dict, output_dict, exec_properties)
  File "/tfx-src/tfx/components/example_gen/base_example_gen_executor.py", line 303, in Do
    split_name)))
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/pipeline.py", line 555, in __exit__
    self.result = self.run()
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/pipeline.py", line 521, in run
    allow_proto_holders=True).run(False)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/pipeline.py", line 534, in run
    return self.runner.run_pipeline(self, self._options)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/dataflow/dataflow_runner.py", line 479, in run_pipeline
    artifacts=environments.python_sdk_dependencies(options)))
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/transforms/environments.py", line 613, in python_sdk_dependencies
    staged_name in stager.Stager.create_job_resources(options, tmp_dir))
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/portability/stager.py", line 197, in create_job_resources
    setup_options.extra_packages, temp_dir=temp_dir))
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/portability/stager.py", line 491, in _create_extra_packages
    Stager._download_file(package, local_file_path)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/portability/stager.py", line 386, in _download_file
    shutil.copyfile(from_url, to_path)
  File "/usr/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'gs://some_bucket/workspaces/gcasassaez/tfx-tmp/tfx_ephemeral-0.24.1.tar.gz'
```

Filing ticket here to see if there's any recommendation on how to do this.

**Comment by casassg** [comment]
This may be related and could potentially be a fix: https://issues.apache.org/jira/browse/BEAM-11275

**Comment by ferryvg** [comment]
I have some issue with Bean and Flink.

Flink taskexecutor log:
```
Java.io.FileNotFoundException: /tmp/beam-temp3g1emmsd/artifactsbv63p2is/a9d47b4ae5a1f4a0b5fddd51d2cd152583637e1353a615d5457aa19494051826/1-ref_Environment_default_e-tfx_ephemeral-0.27.0.tar.gz (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.apache.beam.sdk.io.LocalFileSystem.open(LocalFileSystem.java:127)
        at org.apache.beam.sdk.io.LocalFileSystem.open(LocalFileSystem.java:83)
        at org.apache.beam.sdk.io.FileSystems.open(FileSystems.java:256)
        at org.apache.beam.runners.fnexecution.artifact.ArtifactRetrievalService.getArtifact(ArtifactRetrievalService.java:124)
        at org.apache.beam.runners.fnexecution.artifact.ArtifactRetrievalService.getArtifact(ArtifactRetrievalService.java:99)
        at org.apache.beam.model.jobmanagement.v1.ArtifactRetrievalServiceGrpc$MethodHandlers.invoke(ArtifactRetrievalServiceGrpc.java:327)
        at org.apache.beam.vendor.grpc.v1p26p0.io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
        at org.apache.beam.vendor.grpc.v1p26p0.io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at org.apache.beam.vendor.grpc.v1p26p0.io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at org.apache.beam.vendor.grpc.v1p26p0.io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at org.apache.beam.vendor.grpc.v1p26p0.io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
        at org.apache.beam.vendor.grpc.v1p26p0.io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
        at org.apache.beam.vendor.grpc.v1p26p0.io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817)
        at org.apache.beam.vendor.grpc.v1p26p0.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at org.apache.beam.vendor.grpc.v1p26p0.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Beam worker pool log:
```
2021/02/10 12:28:10 Failed to retrieve staged files: failed to retrieve /tmp/staged in 3 attempts: failed to retrieve chunk for /tmp/staged/tfx_ephemeral-0.27.0.tar.gz
```

**Comment by casassg** [comment]
Implementing at Beam layer
