### ISSUE TITLE
Transform fails when input is multiple artifacts from a Resolver

### ISSUE THREAD

**Issue by ConverJens** [tensorflow/tfx#2889]
When feeding Transform with the output from a LatestArtifactsResolver  it fails with the following message:

INFO:absl:tensorflow_ranking is not available: No module named 'tensorflow_ranking'
INFO:absl:tensorflow_text is not available: No module named 'tensorflow_text'
INFO:absl:Running driver for Transform
INFO:absl:MetadataStore with gRPC connection initialized
INFO:absl:Adding KFP pod name trace-model-pipeline-rdtkz-1739953967 to execution
INFO:absl:Running executor for Transform
INFO:absl:Attempting to infer TFX Python dependency for beam
INFO:absl:Copying all content from install dir /tfx-src/tfx to temp dir /tmp/tmppjval1kd/build/tfx
INFO:absl:Generating a temp setup file at /tmp/tmppjval1kd/build/tfx/setup.py
INFO:absl:Creating temporary sdist package, logs available at /tmp/tmppjval1kd/build/tfx/setup.log
INFO:absl:Added --extra_package=/tmp/tmppjval1kd/build/tfx/dist/tfx_ephemeral-0.25.0.tar.gz to beam args
INFO:absl:Analyze the 'train' split and transform all splits when splits_config is not set.
WARNING:tensorflow:From /tfx-src/tfx/components/transform/executor.py:528: Schema (from tensorflow_transform.tf_metadata.dataset_schema) is deprecated and will be removed in a future version.
Instructions for updating:
Schema is a deprecated, use schema_utils.schema_from_feature_spec to create a `Schema`
WARNING:tensorflow:From /tfx-src/tfx/components/transform/executor.py:528: Schema (from tensorflow_transform.tf_metadata.dataset_schema) is deprecated and will be removed in a future version.
Instructions for updating:
Schema is a deprecated, use schema_utils.schema_from_feature_spec to create a `Schema`
Traceback (most recent call last):
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 360, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 353, in main
    execution_info = launcher.launch()
  File "/tfx-src/tfx/orchestration/launcher/base_component_launcher.py", line 209, in launch
    copy.deepcopy(execution_decision.exec_properties))
  File "/tfx-src/tfx/orchestration/launcher/in_process_component_launcher.py", line 72, in _run_executor
    copy.deepcopy(input_dict), output_dict, copy.deepcopy(exec_properties))
  File "/tfx-src/tfx/components/transform/executor.py", line 433, in Do
    self.Transform(label_inputs, label_outputs, status_file)
  File "/tfx-src/tfx/components/transform/executor.py", line 931, in Transform
    materialize_output_paths)
  File "/tfx-src/tfx/components/transform/executor.py", line 1337, in _MakeDatasetList
    assert len(file_patterns) == len(materialize_output_paths)
AssertionError

This was raised in the PR to introduce this logic: https://github.com/tensorflow/tfx/pull/2397

I might be mistaken here, but depending on how the multiple inputs/outputs is supposed to work I think the test for multiple artifacts might be flawed.

The test case defines the input examples AND the output examples explicitly, i.e. two examples in and two out. However, in a real-world scenario, it is more likely that the number of outputs needs to be dynamically determined from the number of inputs.

Please, let me know if I have misunderstood the functionality or if this logic is indeed missing.

Also, transformed_examples is an optional argument to Transform, but if a list of examples is provided it becomes necessary with the current logic.

**Comment by ConverJens** [comment]
I have created an identical flow in Colab based on the Keras taxi pipeline:
https://colab.research.google.com/drive/1lFWCuXk6yPUhfHx-3Zhz4ozZN7g_9SC4?usp=sharing

This runs as it should! I have made a custom Transform component which only adds logging and I have discovered a difference between the version running in Colab and the one failing in KFP.

From colab:

INFO:absl:data_uris
INFO:absl:['/tmp/tfx-interactive-2020-11-25T12_20_53.243643-0lrr_vp5/CsvExampleGen/examples/2/eval', '/tmp/tfx-interactive-2020-11-25T12_20_53.243643-0lrr_vp5/CsvExampleGen/examples/1/eval']
INFO:absl:transform_data_paths
INFO:absl:['/tmp/tfx-interactive-2020-11-25T12_20_53.243643-0lrr_vp5/CsvExampleGen/examples/2/train/*', '/tmp/tfx-interactive-2020-11-25T12_20_53.243643-0lrr_vp5/CsvExampleGen/examples/1/train/*', '/tmp/tfx-interactive-2020-11-25T12_20_53.243643-0lrr_vp5/CsvExampleGen/examples/2/eval/*', '/tmp/tfx-interactive-2020-11-25T12_20_53.243643-0lrr_vp5/CsvExampleGen/examples/1/eval/*']
INFO:absl:transformed_example_uris
INFO:absl:['/tmp/tfx-interactive-2020-11-25T12_20_53.243643-0lrr_vp5/TransformCustom/transformed_examples/8/0/eval', '/tmp/tfx-interactive-2020-11-25T12_20_53.243643-0lrr_vp5/TransformCustom/transformed_examples/8/1/eval']
INFO:absl:materialize_output_paths
INFO:absl:['/tmp/tfx-interactive-2020-11-25T12_20_53.243643-0lrr_vp5/TransformCustom/transformed_examples/8/0/train/transformed_examples', '/tmp/tfx-interactive-2020-11-25T12_20_53.243643-0lrr_vp5/TransformCustom/transformed_examples/8/1/train/transformed_examples', '/tmp/tfx-interactive-2020-11-25T12_20_53.243643-0lrr_vp5/TransformCustom/transformed_examples/8/0/eval/transformed_examples', '/tmp/tfx-interactive-2020-11-25T12_20_53.243643-0lrr_vp5/TransformCustom/transformed_examples/8/1/eval/transformed_examples']

And from KFP:
INFO:absl:data_uris
INFO:absl:['/mnt/pipelines/tfx/trace_data_ingester/FileBasedExampleGen/examples/1909/eval', '/mnt/pipelines/tfx/trace_data_ingester/FileBasedExampleGen/examples/1868/eval', '/mnt/pipelines/tfx/trace_data_ingester/FileBasedExampleGen/examples/1874/eval']
INFO:absl:transform_data_paths
INFO:absl:['/mnt/pipelines/tfx/trace_data_ingester/FileBasedExampleGen/examples/1909/train/*', '/mnt/pipelines/tfx/trace_data_ingester/FileBasedExampleGen/examples/1868/train/*', '/mnt/pipelines/tfx/trace_data_ingester/FileBasedExampleGen/examples/1874/train/*', '/mnt/pipelines/tfx/trace_data_ingester/FileBasedExampleGen/examples/1909/eval/*', '/mnt/pipelines/tfx/trace_data_ingester/FileBasedExampleGen/examples/1868/eval/*', '/mnt/pipelines/tfx/trace_data_ingester/FileBasedExampleGen/examples/1874/eval/*']
INFO:absl:transformed_example_uris
INFO:absl:['/mnt/pipelines/tfx/trace_model_pipeline/TransformCustom/transformed_examples/1925/eval']
INFO:absl:materialize_output_paths
INFO:absl:['/mnt/pipelines/tfx/trace_model_pipeline/TransformCustom/transformed_examples/1925/train/transformed_examples', '/mnt/pipelines/tfx/trace_model_pipeline/TransformCustom/transformed_examples/1925/eval/transformed_examples']

Note that the number of output artifacts differ
Colab:
INFO:absl:transformed_example_uris
INFO:absl:['/tmp/tfx-interactive-2020-11-25T12_20_53.243643-0lrr_vp5/TransformCustom/transformed_examples/8/0/eval', '/tmp/tfx-interactive-2020-11-25T12_20_53.243643-0lrr_vp5/TransformCustom/transformed_examples/8/1/eval']

vs KFP:
INFO:absl:transformed_example_uris
INFO:absl:['/mnt/pipelines/tfx/trace_model_pipeline/TransformCustom/transformed_examples/1925/eval']

We are running out TFX pipelines in KubeFlow on KFP and I'm starting to wonder if the error is due to MLMD in KF not being up to date. Can you confirm if this can be the root cause? If so, Transform  (or TFX) should probably check that MLMD backend has an appropriate version.

**Comment by 1025KB** [comment]
Here is an un-submitted [example](https://github.com/tensorflow/tfx/pull/2428/files?file-filters%5B%5D=.py#diff-2724da794d4f9ebd0731905e9dcbaf842812636b60bf043e90fdba457f249e01) shows how to use it, let me know if it helps

**Comment by ConverJens** [comment]
@1025KB Thanks for the example! This is pretty much  exactly the same, albeit smaller, setup that I'm using. When I'm running this setup in KubeFlow, it still fails with the same assert error.

For some reason the execution in KubeFlow generates the wrong number of output artifacts while it works correctly in Colab.

Any idea why this is or anything else I can supply to troubleshoot this?

**Comment by zhitaoli** [comment]
> For some reason the execution in KubeFlow generates the wrong number of output artifacts while it works correctly in Colab.
> 
> Any idea why this is or anything else I can supply to troubleshoot this?

@numerology @neuromage Can you comment on this? Do we have limitation on number of output artifacts between Kubeflow and TFX?

**Comment by numerology** [comment]
> @numerology @neuromage Can you comment on this? Do we have limitation on number of output artifacts between Kubeflow and TFX?

Not that I know of. Read from the implementation in https://github.com/tensorflow/tfx/pull/2397 it does not seem to rely on specific version of MLMD so I guess it should not be the culprit.

@ConverJens Do you mind sharing the following information to help up understand the problem?

- Version of TFX image used in KFP
- A compiled KFP yaml spec corresponding to the Transform component

Thanks!

**Comment by ConverJens** [comment]
@numerology 
Sorry for the late response!

We are using the official TFX 0.25.0 image with added custom components.

Below is the KFP yaml spec for the Transform component:

`- name: transform
    container:
      args:
      - --pipeline_name
      - trace_model_pipeline
      - --pipeline_root
      - '{{inputs.parameters.pipeline-root}}'
      - --kubeflow_metadata_config
      - |-
        {
          "grpc_config": {
            "grpc_service_host": {
              "value": "metadata-grpc-service.kubeflow"
            },
            "grpc_service_port": {
              "value": "8080"
            }
          }
        }
      - --beam_pipeline_args
      - '["--direct_running_mode=multi_processing", "--direct_num_workers=4"]'
      - --additional_pipeline_args
      - '{}'
      - --component_launcher_class_path
      - tfx.orchestration.launcher.in_process_component_launcher.InProcessComponentLauncher
      - --serialized_component
      - '{"__class__": "NodeWrapper", "__module__": "tfx.orchestration.kubeflow.node_wrapper",
        "__tfx_object_type__": "jsonable", "_exec_properties": {"custom_config": "null",
        "module_file": null, "preprocessing_fn": "kubeflow.model.preprocessing.transform.preprocessing_fn",
        "splits_config": null}, "_id": "Transform", "_inputs": {"__class__": "_PropertyDictWrapper",
        "__module__": "tfx.types.node_common", "__tfx_object_type__": "jsonable",
        "_compat_aliases": {"input_data": "examples"}, "_data": {"examples": {"__class__":
        "Channel", "__module__": "tfx.types.channel", "__tfx_object_type__": "jsonable",
        "artifacts": [{"__artifact_class_module__": "tfx.types.standard_artifacts",
        "__artifact_class_name__": "Examples", "artifact": {}, "artifact_type": {"name":
        "Examples", "properties": {"span": "INT", "split_names": "STRING", "version":
        "INT"}}}], "output_key": "examples_in_date_range", "producer_component_id":
        "ResolverNode.date_range_examples_resolver", "type": {"name": "Examples",
        "properties": {"span": "INT", "split_names": "STRING", "version": "INT"}}},
        "schema": {"__class__": "Channel", "__module__": "tfx.types.channel", "__tfx_object_type__":
        "jsonable", "artifacts": [], "output_key": "schema", "producer_component_id":
        "SchemaGen.raw", "type": {"name": "Schema"}}}}, "_outputs": {"__class__":
        "_PropertyDictWrapper", "__module__": "tfx.types.node_common", "__tfx_object_type__":
        "jsonable", "_compat_aliases": {"transform_output": "transform_graph"}, "_data":
        {"transform_graph": {"__class__": "Channel", "__module__": "tfx.types.channel",
        "__tfx_object_type__": "jsonable", "artifacts": [], "output_key": "transform_graph",
        "producer_component_id": "Transform", "type": {"name": "TransformGraph"}},
        "transformed_examples": {"__class__": "Channel", "__module__": "tfx.types.channel",
        "__tfx_object_type__": "jsonable", "artifacts": [], "output_key": "transformed_examples",
        "producer_component_id": "Transform", "type": {"name": "Examples", "properties":
        {"span": "INT", "split_names": "STRING", "version": "INT"}}}, "updated_analyzer_cache":
        {"__class__": "Channel", "__module__": "tfx.types.channel", "__tfx_object_type__":
        "jsonable", "artifacts": [], "output_key": "updated_analyzer_cache", "producer_component_id":
        "Transform", "type": {"name": "TransformCache"}}}}, "_type": "tfx.components.transform.component.Transform",
        "driver_class": {"__class__": "BaseDriver", "__module__": "tfx.dsl.components.base.base_driver",
        "__tfx_object_type__": "class"}, "executor_spec": {"__class__": "ExecutorClassSpec",
        "__module__": "tfx.dsl.components.base.executor_spec", "__tfx_object_type__":
        "jsonable", "executor_class": {"__class__": "Executor", "__module__": "tfx.components.transform.executor",
        "__tfx_object_type__": "class"}, "extra_flags": ["--direct_running_mode=multi_processing",
        "--direct_num_workers=4"]}}'
      - --component_config
      - 'null'
      - --enable_cache
      command: [python, /tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py]
      env:
      - name: WORKFLOW_ID
        valueFrom:
          fieldRef: {fieldPath: 'metadata.labels[''workflows.argoproj.io/workflow'']'}
      - {name: S3_ENDPOINT, value: 'http://minio-service.kubeflow:9000'}
      - {name: S3_USE_HTTPS, value: '0'}
      - {name: S3_VERIFY_SSL, value: '0'}
      - {name: AWS_ACCESS_KEY_ID, value: minio}
      - {name: AWS_SECRET_ACCESS_KEY, value: minio123}
      - name: KFP_POD_NAME
        valueFrom:
          fieldRef: {fieldPath: metadata.name}
      - name: KFP_NAMESPACE
        valueFrom:
          fieldRef: {fieldPath: metadata.namespace}
      image: <custom image based on official TFX 0.25.0>
      imagePullPolicy: Always
      resources:
        limits: {cpu: '4', ephemeral-storage: 4Gi}
        requests: {cpu: '4', ephemeral-storage: 100Mi}
      volumeMounts:
      - {mountPath: /mnt, name: pv-gluster}
    inputs:
      parameters:
      - {name: pipeline-root}
    outputs:
      artifacts:
      - {name: mlpipeline-ui-metadata, path: /mlpipeline-ui-metadata.json}
    metadata:
      labels:
        add-pod-env: "true"
        pipelines.kubeflow.org/pipeline-sdk-type: tfx
    volumes:
    - name: pv-gluster
      persistentVolumeClaim: {claimName: tfx-pvc-gluster}`

**Comment by ConverJens** [comment]
@numerology Any update on this? This remains an issue for me with TFX 0.26.0 as well.

**Comment by ConverJens** [comment]
Ping @numerology

**Comment by 1025KB** [comment]
QQ: is this only happens on Kubeflow?

Did you try local (follow above [example](https://github.com/tensorflow/tfx/pull/2428/files?file-filters%5B%5D=.py#diff-2724da794d4f9ebd0731905e9dcbaf842812636b60bf043e90fdba457f249e01)) to see if it works or not?

**Comment by ConverJens** [comment]
@1025KB @numerology @zhitaoli 
I have now tried running my own pipeline locally in an interactive environment using a sqlite db and that works as expected.

I also tried running Transform interactively from a notebook server within KubeFlow, connected to MLMD, fetching live data and schema using Resolvers  and feeding Transform, and this also succeeded.

That means that feeding EXACTLY the same input data and schema to Transform in interactive mode succeeds while running it as a KFP component fails!

The only conclusion I can draw from this is that it probably has to do with the execution (or compilation) in KubeFlow.

Does anyone else have the possibility of running the example posted by @1025KB in KubeFlow and verify?

**Comment by 1025KB** [comment]
This might be a bug, let me check

**Comment by ConverJens** [comment]
@1025KB Strange, why?

Multiple artifacts perchannel does work for other components than Transform though. I have written a few custom components that take multiple artifacts per channel as well as made a custom stats gen that does the same.

Any response from the team whats the reason behind this and when it will be fixed?

**Comment by 1025KB** [comment]
Currently Kubeflow doesn't support multiple artifact in output channel (in TFT, if input example channel contains multiple artifacts , the output example channel will be multiple artifacts too), we are still discussing the support for kubeflow

**Comment by ConverJens** [comment]
@1025KB But is this some kind of limitation in KubeFlow itself or is the limit on the TFX side.

**Comment by ConverJens** [comment]
@1025KB @hongye-sun @bobgy
Has there been any progress on this?

**Comment by 1025KB** [comment]
We have an [example](https://github.com/tensorflow/tfx/blob/master/tfx/examples/penguin/penguin_pipeline_local_e2e_test.py#L206) for local now,

The limitation is on the Kubeflow support for TFX, KubeflowDagRunner support is WIP (plan Q2), KubeflowDagRunner V2 is not planned yet

**Comment by 1025KB** [comment]
KubeflowDagRunner (V2) support most TFX functionality, but there are some feature gaps.

We are going to switch KubeflowDagRunner to new TFX underlying stack which should enable all features.
For KubeflowDagRunner v2, due to the backend difference, it uses a slightly different underlying stack, thus it currently has some limitations for some TFX features, we will fill the gaps in the future

**Comment by ConverJens** [comment]
@1025KB Right. So if I understand you correctly, this support will be implemented by TFX and is not a limitation of KFP per se?

Is it fair to believe that this will be available in the TFX 1.0.0 release?

**Comment by 1025KB** [comment]
KubeflowDagRunner support will be implemented and we are working on that.
KubeflowDagRunner v2 will need backend support from KFP.

1.0 release won't target for new feature support for current KFPDagRunner but mainly for stability.
We hope KubeflowDagRunner will support fully TFX features in Q2, stay tuned.

**Comment by ConverJens** [comment]
@1025KB Great, thanks for the clarification!

**Comment by ConverJens** [comment]
@1025KB Do you know if this functionality is now supported in both TFX and KFP?

**Comment by 1025KB** [comment]
Available on KFP but not KFPv2
