### ISSUE TITLE
RuntimeError: Split pattern gs://tfx-gcp-kubeflowpipelines-default/tfx-template/data/taxi/* does not match any files.

### ISSUE THREAD

**Issue by alanzablocki** [tensorflow/tfx#2909]
Hi there I am following a tutorial on [TFX in GCP ](https://www.tensorflow.org/tfx/tutorials/tfx/cloud-ai-platform-pipelines#4_launch_the_getting_started_notebook) and the example breaks on the very first step; CSV ExampleGen with the error 

**RuntimeError: Split pattern gs://tfx-gcp-kubeflowpipelines-default/tfx-template/data/taxi/* does not match any files.**

I will add I can see the DAG, but the run itself fails.

It seems that the csv file cannot be found and I think the pipeline is using a setting from kubeflow_dag_runner.py where

DATA_PATH = 'gs://{}/tfx-template/data/taxi/'.format(configs.GCS_BUCKET_NAME)

instead of pointing to something like ".../imported/my_pipeline/data/data.csv"

I tried these options

DATA_PATH = 'gs://{}/data/taxi/'.format(configs.GCS_BUCKET_NAME)
DATA_PATH = 'data'

with no luck. I am wondering if I should be using something like

DATA_PATH = 'gs://tfx-gcp-kubeflowpipelines-default/data/'.format(configs.GCS_BUCKET_NAME)

but this also errors out saying no matching files.

What am I missing here, how and where do I correct this to point to the data?
I am using the 2.1 TF notebook. 

Thanks for your help,
A

2020-12-02 03:31:00.848228: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib
2020-12-02 03:31:00.848312: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO:absl:tensorflow_ranking is not available: No module named 'tensorflow_ranking'
INFO:absl:tensorflow_text is not available: No module named 'tensorflow_text'
INFO:absl:Running driver for CsvExampleGen
INFO:absl:MetadataStore with gRPC connection initialized
INFO:absl:select span and version = (0, None)
INFO:absl:latest span and version = (0, None)
INFO:absl:Adding KFP pod name my-pipeline-4g648-3840511578 to execution
INFO:absl:Running executor for CsvExampleGen
INFO:absl:Generating examples.
INFO:absl:Processing input csv data gs://tfx-gcp-kubeflowpipelines-default/tfx-template/data/taxi/* to TFExample.
Traceback (most recent call last):
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 360, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 353, in main
    execution_info = launcher.launch()
  File "/tfx-src/tfx/orchestration/launcher/base_component_launcher.py", line 209, in launch
    copy.deepcopy(execution_decision.exec_properties))
  File "/tfx-src/tfx/orchestration/launcher/in_process_component_launcher.py", line 72, in _run_executor
    copy.deepcopy(input_dict), output_dict, copy.deepcopy(exec_properties))
  File "/tfx-src/tfx/components/example_gen/base_example_gen_executor.py", line 293, in Do
    example_splits = self.GenerateExamplesByBeam(pipeline, exec_properties)
  File "/tfx-src/tfx/components/example_gen/base_example_gen_executor.py", line 229, in GenerateExamplesByBeam
    | 'SplitData' >> beam.Partition(_PartitionFn, len(buckets), buckets,
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/transforms/ptransform.py", line 1028, in __ror__
    return self.transform.__ror__(pvalueish, self.label)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/transforms/ptransform.py", line 565, in __ror__
    result = p.apply(self, pvalueish, label)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/pipeline.py", line 634, in apply
    return self.apply(transform, pvalueish)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/pipeline.py", line 677, in apply
    pvalueish_result = self.runner.apply(transform, pvalueish, self._options)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/runner.py", line 198, in apply
    return m(transform, input, options)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/runner.py", line 228, in apply_PTransform
    return transform.expand(input)
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/transforms/ptransform.py", line 934, in expand
    return self._fn(pcoll, *args, **kwargs)
  File "/tfx-src/tfx/components/example_gen/csv_example_gen/executor.py", line 132, in _CsvToExample
    'Split pattern {} does not match any files.'.format(csv_pattern))
RuntimeError: Split pattern gs://tfx-gcp-kubeflowpipelines-default/tfx-template/data/taxi/* does not match any files.

**Comment by numerology** [comment]
/cc @jiyongjung0 as well

Thanks for reporting! In the latest version of [the tutorial](https://github.com/tensorflow/tfx/blob/master/docs/tutorials/tfx/template.ipynb) you'll need to first upload the data csv files to the GCS bucket by running:
```
!gsutil cp data/data.csv gs://{GOOGLE_CLOUD_PROJECT}-kubeflowpipelines-default/tfx-template/data/data.csv
```
Otherwise the examplegen will fail if running on Dataflow.

We should update the website as well.

**Comment by alanzablocki** [comment]
Thanks for the quick reply.

I was indeed just following the website and not the template.ipynb found under 
Getting Started ->Build your own pipeline with ->  TensorFlow Extended (TFX) SDK with end-to-end ML Pipeline Template (**Open TF 2.1 Notebook**)
