### ISSUE TITLE
StatisticsGen fails when using Flink runner for Apache Beam

### ISSUE THREAD

**Issue by ferryvg** [tensorflow/tfx#3251]
I have dataset with 10kk of tf example records. When i run my pipeline with Flink job manager for Beam i got and error while StatisticsGen component execution:

```
RuntimeError: Pipeline job-90240321-b263-4cd6-b3ff-898ca75bbf32 failed in state FAILED: java.lang.Exception: The data preparation for task 'GroupReduce (GroupReduce at GenerateStatistics[eval]/RunStatsGenerators/GenerateSlicedStatisticsImpl/RunCombinerStatsGenerators/CombinePerKey(PreCombineFn)/GroupByKey)' , caused an error: Error obtaining the sorted input: Thread 'SortMerger Reading Thread' terminated due to an exception: The record exceeds the maximum size of a sort buffer (current maximum: 89325568 bytes).
	at org.apache.flink.runtime.operators.BatchTask.run(BatchTask.java:480)
	at org.apache.flink.runtime.operators.BatchTask.invoke(BatchTask.java:369)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:708)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:533)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Error obtaining the sorted input: Thread 'SortMerger Reading Thread' terminated due to an exception: The record exceeds the maximum size of a sort buffer (current maximum: 89325568 bytes).
	at org.apache.flink.runtime.operators.sort.UnilateralSortMerger.getIterator(UnilateralSortMerger.java:650)
	at org.apache.flink.runtime.operators.BatchTask.getInput(BatchTask.java:1110)
	at org.apache.flink.runtime.operators.GroupReduceDriver.prepare(GroupReduceDriver.java:99)
	at org.apache.flink.runtime.operators.BatchTask.run(BatchTask.java:474)
	... 4 more
Caused by: java.io.IOException: Thread 'SortMerger Reading Thread' terminated due to an exception: The record exceeds the maximum size of a sort buffer (current maximum: 89325568 bytes).
	at org.apache.flink.runtime.operators.sort.UnilateralSortMerger$ThreadBase.run(UnilateralSortMerger.java:831)
Caused by: java.io.IOException: The record exceeds the maximum size of a sort buffer (current maximum: 89325568 bytes).
	at org.apache.flink.runtime.operators.sort.UnilateralSortMerger$ReadingThread.go(UnilateralSortMerger.java:986)
	at org.apache.flink.runtime.operators.sort.UnilateralSortMerger$ThreadBase.run(UnilateralSortMerger.java:827)
```

Python 3.8
TFX: 0.27.0
TFD: 0.27.0
Apache Beam: 0.28.0.dev

**Comment by ferryvg** [comment]
https://issues.apache.org/jira/browse/BEAM-6016
