### ISSUE TITLE
Getting ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6 in Python 3.5 Ubuntu 16.04

### ISSUE THREAD

**Issue by rajeshkumargp** [tensorflow/tfx#331]
I am trying to replicate Taxi Data Set Analysis using TFX as in https://github.com/tensorflow/tfx/tree/master/tfx/examples/chicago_taxi_pipeline. 

I am using Python3.5 in Ubuntu 16.04. 
My virtual environment base path is at `/home/user/Environments/tfx_py3 `

Here is the error log while running `airflow webserver -p 8080`

[2019-07-11 14:32:01,072] {__init__.py:305} INFO - Filling up the DagBag from /home/user/airflow/dags
[2019-07-11 14:32:01,855] {__init__.py:416} ERROR - Failed to import: /home/user/airflow/dags/taxi/taxi_pipeline_simple.py
Traceback (most recent call last):
  File "/home/user/Environments/tfx_py3/lib/python3.5/site-packages/airflow/models/__init__.py", line 413, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/home/user/Environments/tfx_py3/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/user/airflow/dags/taxi/taxi_pipeline_simple.py", line 22, in <module>
    from tfx.components.evaluator.component import Evaluator
  File "/home/user/Environments/tfx_py3/lib/python3.5/site-packages/tfx/components/evaluator/component.py", line 23, in <module>
    from tfx.components.base import base_driver
  File "/home/user/Environments/tfx_py3/lib/python3.5/site-packages/tfx/components/base/base_driver.py", line 25, in <module>
    from tfx.orchestration import metadata
  File "/home/user/Environments/tfx_py3/lib/python3.5/site-packages/tfx/orchestration/metadata.py", line 26, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/user/Environments/tfx_py3/lib/python3.5/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/user/Environments/tfx_py3/lib/python3.5/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/user/Environments/tfx_py3/lib/python3.5/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tf_metadata_store_serialized', fp, pathname, description)
  File "/home/user/Environments/tfx_py3/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/user/Environments/tfx_py3/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/user/Environments/tfx_py3/lib/python3.5/site-packages/ml_metadata/metadata_store/_pywrap_tf_metadata_store_serialized.so)
[2019-07-11 14:32:02 +0530] [23633] [INFO] Handling signal: ttou
[2019-07-11 14:32:02 +0530] [23835] [INFO] Worker exiting (pid: 23835)

Can you please guide further ?

**Comment by zhitaoli** [comment]
@hughmiao

**Comment by krazyhaas** [comment]
Hi rajeshkumargp.  You need to upgrade libstd.  Try the following commands and let me know if the issue gets resolved:

```
sudo apt-get update
sudo apt-get install gcc-4.9
sudo apt-get install --only-upgrade libstdc++6
```

**Comment by rajeshkumargp** [comment]
Tried these,
Still getting same error.

-->sudo apt-get install gcc-4.9
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc-4.9 is already the newest version (4.9.3-13ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 406 not upgraded.

--> sudo apt-get install --only-upgrade libstdc++6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libstdc++6 is already the newest version (5.4.0-6ubuntu1~16.04.11).
0 upgraded, 0 newly installed, 0 to remove and 406 not upgraded.

**Comment by gowtham-kp** [comment]
@rajeshkumargp Users have run into the similar issue while installing Tensorflow in the system. But there is a work around for this. Can you please refer to the following [issue](https://github.com/lhelontra/tensorflow-on-arm/issues/13) and let me know if it helps! This issues has a clear explanation and work arounds that will help you navigate through this error!

**Comment by rajeshkumargp** [comment]
I did reinstalled gcc-4.9, libstdc++6, It  resolves the issue. 
I did by using 

sudo apt-get install --reinstall gcc-4.9

**Comment by Chokerino** [comment]
apt-get is not available for me. How do i solve this? I install gcc suing conda but still get `ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/bhavay18384/.conda/envs/myenv/lib/python3.7/site-packages/sklearn/svm/_libsvm.cpython-37m-x86_64-linux-gnu.so)`

**Comment by JFishLover** [comment]
> ow do i solve this?

did you solved it?
