### ISSUE TITLE
TFX Local Pipeline Issue with LocalDAG, BeamDAG Runner

### ISSUE THREAD

**Issue by wlee192** [tensorflow/tfx#3331]
**System information** 
- Have I specified the code to reproduce the issue
(Yes/No): Yes

- Environment in which the code is executed (e.g., Local
(Linux/MacOS/Windows), Interactive Notebook, Google Cloud, etc): Local Windows 10 

- TensorFlow
version (you are using): 2.4.1

- TFX Version: 0.27.0

- Python version: 3.6.8

**Describe the current behavior**
I'm running the full tfx pipeline on my local windows machine, and i've run a test using samples from the taxi chicago example, for [LocalDAGRunner ](https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi_pipeline/taxi_pipeline_local.py)and [BeamDAGRunner](https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi_pipeline/taxi_pipeline_beam.py)

When i run the BeamDAGRunner example, it throws an error as shown below

```
WARNING:apache_beam.options.pipeline_options:Discarding unparseable args: ['--ip=127.0.0.1', '--stdin=9008', '--control=9006', '--hb=9005', '--Session.signature_scheme="hmac-sha256"', '--Session.key=b"1a0b1704-05f3-441d-8112-13f187ab7dd5"', '--shell=9007', '--transport="tcp"', '--iopub=9009', '--f=C:\\Users\\warre\\AppData\\Local\\Temp\\tmp-36003AKu4YxvGZyP.json']
INFO:absl:Attempting to infer TFX Python dependency for beam
INFO:absl:Copying all content from install dir c:\SentinelMlTfLocal\lib\site-packages\tfx to temp dir C:\Users\warre\AppData\Local\Temp\tmp6u7gnkl_\build\tfx
INFO:absl:Generating a temp setup file at C:\Users\warre\AppData\Local\Temp\tmp6u7gnkl_\build\tfx\setup.py
INFO:absl:Creating temporary sdist package, logs available at C:\Users\warre\AppData\Local\Temp\tmp6u7gnkl_\build\tfx\setup.log
INFO:absl:Added --extra_package=C:\Users\warre\AppData\Local\Temp\tmp6u7gnkl_\build\tfx\dist\tfx_ephemeral-0.27.0.tar.gz to beam args
INFO:absl:Generating examples.
usage: ipykernel_launcher [-h] [--dataflow_endpoint DATAFLOW_ENDPOINT]
                          [--project PROJECT] [--job_name JOB_NAME]
                          [--staging_location STAGING_LOCATION]
                          [--temp_location TEMP_LOCATION] [--region REGION]
                          [--service_account_email SERVICE_ACCOUNT_EMAIL]
                          [--no_auth] [--template_location TEMPLATE_LOCATION]
                          [--label LABELS] [--update]
                          [--transform_name_mapping TRANSFORM_NAME_MAPPING]
                          [--enable_streaming_engine]
                          [--dataflow_kms_key DATAFLOW_KMS_KEY]
                          [--flexrs_goal {COST_OPTIMIZED,SPEED_OPTIMIZED}]
ipykernel_launcher: error: argument --flexrs_goal: invalid choice: 'C:\\Users\\warre\\AppData\\Local\\Temp\\tmp-36003AKu4YxvGZyP.json' (choose from 'COST_OPTIMIZED', 'SPEED_OPTIMIZED')
INFO:absl:Cleaning up stateless execution info.
Output was trimmed for performance reasons.
To see the full output set the setting "jupyter.textOutputLimit" to 0.
...
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
c:\users\warre\appdata\local\programs\python\python36\lib\argparse.py in parse_known_args(self, args, namespace)
   1765         try:
-> 1766             namespace, args = self._parse_known_args(args, namespace)
   1767             if hasattr(namespace, _UNRECOGNIZED_ARGS_ATTR):

c:\users\warre\appdata\local\programs\python\python36\lib\argparse.py in _parse_known_args(self, arg_strings, namespace)
   1971             # consume the next optional and any arguments for it
-> 1972             start_index = consume_optional(start_index)
   1973 

c:\users\warre\appdata\local\programs\python\python36\lib\argparse.py in consume_optional(start_index)
   1911             for action, args, option_string in action_tuples:
-> 1912                 take_action(action, args, option_string)
   1913             return stop

c:\users\warre\appdata\local\programs\python\python36\lib\argparse.py in take_action(action, argument_strings, option_string)
   1823             seen_actions.add(action)
-> 1824             argument_values = self._get_values(action, argument_strings)
   1825 

c:\users\warre\appdata\local\programs\python\python36\lib\argparse.py in _get_values(self, action, arg_strings)
   2265             value = self._get_value(action, arg_string)
-> 2266             self._check_value(action, value)
   2267 

c:\users\warre\appdata\local\programs\python\python36\lib\argparse.py in _check_value(self, action, value)
   2317             msg = _('invalid choice: %(value)r (choose from %(choices)s)')
-> 2318             raise ArgumentError(action, msg % args)
   2319 

ArgumentError: argument --flexrs_goal: invalid choice: 'C:\\Users\\warre\\AppData\\Local\\Temp\\tmp-36003AKu4YxvGZyP.json' (choose from 'COST_OPTIMIZED', 'SPEED_OPTIMIZED')

During handling of the above exception, another exception occurred:

SystemExit                                Traceback (most recent call last)
c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\common.cp36-win_amd64.pyd in apache_beam.runners.common.DoFnRunner.process()

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\common.cp36-win_amd64.pyd in apache_beam.runners.common.SimpleInvoker.invoke_process()

c:\SentinelMlTfLocal\lib\site-packages\tfx\orchestration\beam\beam_dag_runner.py in process(self, element, *signals)
     87     logging.info('node %s is running.', self._node_id)
---> 88     self._run_component()
     89     logging.info('node %s is finished.', self._node_id)

c:\SentinelMlTfLocal\lib\site-packages\tfx\orchestration\beam\beam_dag_runner.py in _run_component(self)
    102         platform_config=platform_config,
--> 103         custom_driver_spec=self._custom_driver_spec).launch()
    104 

c:\SentinelMlTfLocal\lib\site-packages\tfx\orchestration\portable\launcher.py in launch(self)
    384       try:
--> 385         executor_output = self._run_executor(execution_info)
    386       except Exception:  # pylint: disable=broad-except

c:\SentinelMlTfLocal\lib\site-packages\tfx\orchestration\portable\launcher.py in _run_executor(self, execution_info)
    291     try:
--> 292       executor_output = self._executor_operator.run_executor(execution_info)
    293       code = executor_output.execution_result.code

c:\SentinelMlTfLocal\lib\site-packages\tfx\orchestration\portable\python_executor_operator.py in run_executor(self, execution_info)
    109     result = executor.Do(execution_info.input_dict, execution_info.output_dict,
--> 110                          execution_info.exec_properties)
    111     if not result:

c:\SentinelMlTfLocal\lib\site-packages\tfx\components\example_gen\base_example_gen_executor.py in Do(self, input_dict, output_dict, exec_properties)
    294     logging.info('Generating examples.')
--> 295     with self._make_beam_pipeline() as pipeline:
    296       example_splits = self.GenerateExamplesByBeam(pipeline, exec_properties)

c:\SentinelMlTfLocal\lib\site-packages\tfx\dsl\components\base\base_executor.py in _make_beam_pipeline(self)
    155     return beam.Pipeline(
--> 156         options=pipeline_options, runner=fn_api_runner.FnApiRunner())
    157 

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\pipeline.py in __init__(self, runner, options, argv)
    194     # Validate pipeline options
--> 195     errors = PipelineOptionsValidator(self._options, runner).validate()
    196     if errors:

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\options\pipeline_options_validator.py in validate(self)
    145       if 'validate' in cls.__dict__ and callable(cls.__dict__['validate']):
--> 146         errors.extend(self.options.view_as(cls).validate(self))
    147     return errors

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\options\pipeline_options.py in view_as(self, cls)
    358     """
--> 359     view = cls(self._flags)
    360     for option_name in view._visible_option_list():

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\options\pipeline_options.py in __init__(self, flags, **kwargs)
    207     # by the parser.
--> 208     self._visible_options, _ = parser.parse_known_args(flags)
    209 

c:\users\warre\appdata\local\programs\python\python36\lib\argparse.py in parse_known_args(self, args, namespace)
   1772             err = _sys.exc_info()[1]
-> 1773             self.error(str(err))
   1774 

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\options\pipeline_options.py in error(self, message)
    131       return
--> 132     super(_BeamArgumentParser, self).error(message)
    133 

c:\users\warre\appdata\local\programs\python\python36\lib\argparse.py in error(self, message)
   2392         args = {'prog': self.prog, 'message': message}
-> 2393         self.exit(2, _('%(prog)s: error: %(message)s\n') % args)

c:\users\warre\appdata\local\programs\python\python36\lib\argparse.py in exit(self, status, message)
   2379             self._print_message(message, _sys.stderr)
-> 2380         _sys.exit(status)
   2381 

SystemExit: 2

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
c:\SentinelMlTfLocal\Sourcecode\Pipeline\Sentinel_Pipeline_localDAG.py in 
    348       new_schema=True,
    349       enable_interactive=INTERACTIVE_RUN,
--> 350       beam_pipeline_args=_beam_pipeline_args))

c:\SentinelMlTfLocal\lib\site-packages\tfx\orchestration\beam\beam_dag_runner.py in run(self, pipeline)
    325                       deployment_config=deployment_config),
    326                   *[beam.pvalue.AsIter(s) for s in signals_to_wait]))
--> 327           logging.info('Node %s is scheduled.', node_id)

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\pipeline.py in __exit__(self, exc_type, exc_val, exc_tb)
    578     try:
    579       if not exc_type:
--> 580         self.result = self.run()
    581         self.result.wait_until_finish()
    582     finally:

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\pipeline.py in run(self, test_runner_api)
    557         finally:
    558           shutil.rmtree(tmpdir)
--> 559       return self.runner.run_pipeline(self, self._options)
    560     finally:
    561       shutil.rmtree(self.local_tempdir, ignore_errors=True)

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\direct\direct_runner.py in run_pipeline(self, pipeline, options)
    131       runner = BundleBasedDirectRunner()
    132 
--> 133     return runner.run_pipeline(pipeline, options)
    134 
    135 

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\portability\fn_api_runner\fn_runner.py in run_pipeline(self, pipeline, options)
    181 
    182     self._latest_run_result = self.run_via_runner_api(
--> 183         pipeline.to_runner_api(default_environment=self._default_environment))
    184     return self._latest_run_result
    185 

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\portability\fn_api_runner\fn_runner.py in run_via_runner_api(self, pipeline_proto)
    191     # TODO(pabloem, BEAM-7514): Create a watermark manager (that has access to
    192     #   the teststream (if any), and all the stages).
--> 193     return self.run_stages(stage_context, stages)
    194 
    195   @contextlib.contextmanager

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\portability\fn_api_runner\fn_runner.py in run_stages(self, stage_context, stages)
    357           stage_results = self._run_stage(
    358               runner_execution_context,
--> 359               bundle_context_manager,
    360           )
    361           monitoring_infos_by_stage[stage.name] = (

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\portability\fn_api_runner\fn_runner.py in _run_stage(self, runner_execution_context, bundle_context_manager)
    553               input_timers,
    554               expected_timer_output,
--> 555               bundle_manager)
    556 
    557       final_result = merge_results(last_result)

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\portability\fn_api_runner\fn_runner.py in _run_bundle(self, runner_execution_context, bundle_context_manager, data_input, data_output, input_timers, expected_timer_output, bundle_manager)
    593 
    594     result, splits = bundle_manager.process_bundle(
--> 595         data_input, data_output, input_timers, expected_timer_output)
    596     # Now we collect all the deferred inputs remaining from bundle execution.
    597     # Deferred inputs can be:

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\portability\fn_api_runner\fn_runner.py in process_bundle(self, inputs, expected_outputs, fired_timers, expected_output_timers, dry_run)
    894             process_bundle_descriptor.id,
    895             cache_tokens=[next(self._cache_token_generator)]))
--> 896     result_future = self._worker_handler.control_conn.push(process_bundle_req)
    897 
    898     split_results = []  # type: List[beam_fn_api_pb2.ProcessBundleSplitResponse]

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\portability\fn_api_runner\worker_handlers.py in push(self, request)
    378       self._uid_counter += 1
    379       request.instruction_id = 'control_%s' % self._uid_counter
--> 380     response = self.worker.do_instruction(request)
    381     return ControlFuture(request.instruction_id, response)
    382 

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\worker\sdk_worker.py in do_instruction(self, request)
    605       # E.g. if register is set, this will call self.register(request.register))
    606       return getattr(self, request_type)(
--> 607           getattr(request, request_type), request.instruction_id)
    608     else:
    609       raise NotImplementedError

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\worker\sdk_worker.py in process_bundle(self, request, instruction_id)
    642         with self.maybe_profile(instruction_id):
    643           delayed_applications, requests_finalization = (
--> 644               bundle_processor.process_bundle(instruction_id))
    645           monitoring_infos = bundle_processor.monitoring_infos()
    646           monitoring_infos.extend(self.state_cache_metrics_fn())

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\worker\bundle_processor.py in process_bundle(self, instruction_id)
    998           elif isinstance(element, beam_fn_api_pb2.Elements.Data):
    999             input_op_by_transform_id[element.transform_id].process_encoded(
-> 1000                 element.data)
   1001 
   1002       # Finish all operations.

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\worker\bundle_processor.py in process_encoded(self, encoded_windowed_values)
    226       decoded_value = self.windowed_coder_impl.decode_from_stream(
    227           input_stream, True)
--> 228       self.output(decoded_value)
    229 
    230   def monitoring_infos(self, transform_id, tag_to_pcollection_id):

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\worker\operations.cp36-win_amd64.pyd in apache_beam.runners.worker.operations.Operation.output()

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\worker\operations.cp36-win_amd64.pyd in apache_beam.runners.worker.operations.Operation.output()

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\worker\operations.cp36-win_amd64.pyd in apache_beam.runners.worker.operations.SingletonConsumerSet.receive()

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\worker\operations.cp36-win_amd64.pyd in apache_beam.runners.worker.operations.DoOperation.process()

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\worker\operations.cp36-win_amd64.pyd in apache_beam.runners.worker.operations.DoOperation.process()

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\common.cp36-win_amd64.pyd in apache_beam.runners.common.DoFnRunner.process()

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\common.cp36-win_amd64.pyd in apache_beam.runners.common.DoFnRunner._reraise_augmented()

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\common.cp36-win_amd64.pyd in apache_beam.runners.common.DoFnRunner.process()

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\common.cp36-win_amd64.pyd in apache_beam.runners.common.SimpleInvoker.invoke_process()

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\common.cp36-win_amd64.pyd in apache_beam.runners.common._OutputProcessor.process_outputs()

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\worker\operations.cp36-win_amd64.pyd in apache_beam.runners.worker.operations.SingletonConsumerSet.receive()

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\worker\operations.cp36-win_amd64.pyd in apache_beam.runners.worker.operations.DoOperation.process()

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\worker\operations.cp36-win_amd64.pyd in apache_beam.runners.worker.operations.DoOperation.process()

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\common.cp36-win_amd64.pyd in apache_beam.runners.common.DoFnRunner.process()

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\common.cp36-win_amd64.pyd in apache_beam.runners.common.DoFnRunner._reraise_augmented()

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\common.cp36-win_amd64.pyd in apache_beam.runners.common.DoFnRunner.process()

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\common.cp36-win_amd64.pyd in apache_beam.runners.common.SimpleInvoker.invoke_process()

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\common.cp36-win_amd64.pyd in apache_beam.runners.common._OutputProcessor.process_outputs()

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\worker\operations.cp36-win_amd64.pyd in apache_beam.runners.worker.operations.ConsumerSet.receive()

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\worker\operations.cp36-win_amd64.pyd in apache_beam.runners.worker.operations.DoOperation.process()

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\worker\operations.cp36-win_amd64.pyd in apache_beam.runners.worker.operations.DoOperation.process()

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\common.cp36-win_amd64.pyd in apache_beam.runners.common.DoFnRunner.process()

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\common.cp36-win_amd64.pyd in apache_beam.runners.common.DoFnRunner._reraise_augmented()

c:\SentinelMlTfLocal\lib\site-packages\future\utils\__init__.py in raise_with_traceback(exc, traceback)
    444         if traceback == Ellipsis:
    445             _, _, traceback = sys.exc_info()
--> 446         raise exc.with_traceback(traceback)
    447 
    448 else:

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\common.cp36-win_amd64.pyd in apache_beam.runners.common.DoFnRunner.process()

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\common.cp36-win_amd64.pyd in apache_beam.runners.common.SimpleInvoker.invoke_process()

c:\SentinelMlTfLocal\lib\site-packages\tfx\orchestration\beam\beam_dag_runner.py in process(self, element, *signals)
     86 
     87     logging.info('node %s is running.', self._node_id)
---> 88     self._run_component()
     89     logging.info('node %s is finished.', self._node_id)
     90 

c:\SentinelMlTfLocal\lib\site-packages\tfx\orchestration\beam\beam_dag_runner.py in _run_component(self)
    101         executor_spec=self._executor_spec,
    102         platform_config=platform_config,
--> 103         custom_driver_spec=self._custom_driver_spec).launch()
    104 
    105   def _extract_platform_config(

c:\SentinelMlTfLocal\lib\site-packages\tfx\orchestration\portable\launcher.py in launch(self)
    383     if is_execution_needed:
    384       try:
--> 385         executor_output = self._run_executor(execution_info)
    386       except Exception:  # pylint: disable=broad-except
    387         self._publish_failed_execution(execution_info.execution_id, contexts)

c:\SentinelMlTfLocal\lib\site-packages\tfx\orchestration\portable\launcher.py in _run_executor(self, execution_info)
    290     outputs_utils.make_output_dirs(execution_info.output_dict)
    291     try:
--> 292       executor_output = self._executor_operator.run_executor(execution_info)
    293       code = executor_output.execution_result.code
    294       if code != 0:

c:\SentinelMlTfLocal\lib\site-packages\tfx\orchestration\portable\python_executor_operator.py in run_executor(self, execution_info)
    108 
    109     result = executor.Do(execution_info.input_dict, execution_info.output_dict,
--> 110                          execution_info.exec_properties)
    111     if not result:
    112       # If result is not returned from the Do function, then try to

c:\SentinelMlTfLocal\lib\site-packages\tfx\components\example_gen\base_example_gen_executor.py in Do(self, input_dict, output_dict, exec_properties)
    293 
    294     logging.info('Generating examples.')
--> 295     with self._make_beam_pipeline() as pipeline:
    296       example_splits = self.GenerateExamplesByBeam(pipeline, exec_properties)
    297 

c:\SentinelMlTfLocal\lib\site-packages\tfx\dsl\components\base\base_executor.py in _make_beam_pipeline(self)
    154 
    155     return beam.Pipeline(
--> 156         options=pipeline_options, runner=fn_api_runner.FnApiRunner())
    157 
    158   def _get_tmp_dir(self) -> Text:

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\pipeline.py in __init__(self, runner, options, argv)
    193 
    194     # Validate pipeline options
--> 195     errors = PipelineOptionsValidator(self._options, runner).validate()
    196     if errors:
    197       raise ValueError(

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\options\pipeline_options_validator.py in validate(self)
    144     for cls in self.OPTIONS:
    145       if 'validate' in cls.__dict__ and callable(cls.__dict__['validate']):
--> 146         errors.extend(self.options.view_as(cls).validate(self))
    147     return errors
    148 

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\options\pipeline_options.py in view_as(self, cls)
    357 
    358     """
--> 359     view = cls(self._flags)
    360     for option_name in view._visible_option_list():
    361       # Initialize values of keys defined by a cls.

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\options\pipeline_options.py in __init__(self, flags, **kwargs)
    206     # The _visible_options attribute will contain options that were recognized
    207     # by the parser.
--> 208     self._visible_options, _ = parser.parse_known_args(flags)
    209 
    210     # self._all_options is initialized with overrides to flag values,

c:\users\warre\appdata\local\programs\python\python36\lib\argparse.py in parse_known_args(self, args, namespace)
   1771         except ArgumentError:
   1772             err = _sys.exc_info()[1]
-> 1773             self.error(str(err))
   1774 
   1775     def _parse_known_args(self, arg_strings, namespace):

c:\SentinelMlTfLocal\lib\site-packages\apache_beam\options\pipeline_options.py in error(self, message)
    130     if message.startswith('ambiguous option: '):
    131       return
--> 132     super(_BeamArgumentParser, self).error(message)
    133 
    134 

c:\users\warre\appdata\local\programs\python\python36\lib\argparse.py in error(self, message)
   2391         self.print_usage(_sys.stderr)
   2392         args = {'prog': self.prog, 'message': message}
-> 2393         self.exit(2, _('%(prog)s: error: %(message)s\n') % args)

c:\users\warre\appdata\local\programs\python\python36\lib\argparse.py in exit(self, status, message)
   2378         if message:
   2379             self._print_message(message, _sys.stderr)
-> 2380         _sys.exit(status)
   2381 
   2382     def error(self, message):

RuntimeError: SystemExit: 2 [while running 'Run[CsvExampleGen]']
```
When i then run the LocalDAGRunner example, it throws a different error as shown below

```
INFO:absl:Processing input csv data c:\SentinelMlTfLocal\Sourcecode\Data\Baseline 1\version-2\* to TFExample.
Exception in thread run_worker:
Traceback (most recent call last):
  File "c:\users\warre\appdata\local\programs\python\python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\users\warre\appdata\local\programs\python\python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\portability\local_job_service.py", line 214, in run
    p = subprocess.Popen(self._worker_command_line, shell=True, env=env_dict)
  File "c:\users\warre\appdata\local\programs\python\python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "c:\users\warre\appdata\local\programs\python\python36\lib\subprocess.py", line 991, in _execute_child
    args = list2cmdline(args)
  File "c:\users\warre\appdata\local\programs\python\python36\lib\subprocess.py", line 481, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'int' is not iterable
Exception in thread run_worker:
Traceback (most recent call last):
  File "c:\users\warre\appdata\local\programs\python\python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\users\warre\appdata\local\programs\python\python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\portability\local_job_service.py", line 214, in run
    p = subprocess.Popen(self._worker_command_line, shell=True, env=env_dict)
  File "c:\users\warre\appdata\local\programs\python\python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "c:\users\warre\appdata\local\programs\python\python36\lib\subprocess.py", line 991, in _execute_child
    args = list2cmdline(args)
  File "c:\users\warre\appdata\local\programs\python\python36\lib\subprocess.py", line 481, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'int' is not iterable
Exception in thread run_worker:
Traceback (most recent call last):
  File "c:\users\warre\appdata\local\programs\python\python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\users\warre\appdata\local\programs\python\python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\portability\local_job_service.py", line 214, in run
    p = subprocess.Popen(self._worker_command_line, shell=True, env=env_dict)
  File "c:\users\warre\appdata\local\programs\python\python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "c:\users\warre\appdata\local\programs\python\python36\lib\subprocess.py", line 991, in _execute_child
    args = list2cmdline(args)
  File "c:\users\warre\appdata\local\programs\python\python36\lib\subprocess.py", line 481, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'int' is not iterable


Exception in thread run_worker:
Traceback (most recent call last):
  File "c:\users\warre\appdata\local\programs\python\python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\users\warre\appdata\local\programs\python\python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\portability\local_job_service.py", line 214, in run
    p = subprocess.Popen(self._worker_command_line, shell=True, env=env_dict)
  File "c:\users\warre\appdata\local\programs\python\python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "c:\users\warre\appdata\local\programs\python\python36\lib\subprocess.py", line 991, in _execute_child
    args = list2cmdline(args)
  File "c:\users\warre\appdata\local\programs\python\python36\lib\subprocess.py", line 481, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'int' is not iterable
Exception in thread run_worker:
Traceback (most recent call last):
  File "c:\users\warre\appdata\local\programs\python\python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\users\warre\appdata\local\programs\python\python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\portability\local_job_service.py", line 214, in run
    p = subprocess.Popen(self._worker_command_line, shell=True, env=env_dict)
  File "c:\users\warre\appdata\local\programs\python\python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "c:\users\warre\appdata\local\programs\python\python36\lib\subprocess.py", line 991, in _execute_child
    args = list2cmdline(args)
  File "c:\users\warre\appdata\local\programs\python\python36\lib\subprocess.py", line 481, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'int' is not iterable

Exception in thread run_worker:
Traceback (most recent call last):
  File "c:\users\warre\appdata\local\programs\python\python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\users\warre\appdata\local\programs\python\python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\portability\local_job_service.py", line 214, in run
    p = subprocess.Popen(self._worker_command_line, shell=True, env=env_dict)
  File "c:\users\warre\appdata\local\programs\python\python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "c:\users\warre\appdata\local\programs\python\python36\lib\subprocess.py", line 991, in _execute_child
    args = list2cmdline(args)
  File "c:\users\warre\appdata\local\programs\python\python36\lib\subprocess.py", line 481, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'int' is not iterable
Exception in thread run_worker:
Traceback (most recent call last):
  File "c:\users\warre\appdata\local\programs\python\python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\users\warre\appdata\local\programs\python\python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\portability\local_job_service.py", line 214, in run
    p = subprocess.Popen(self._worker_command_line, shell=True, env=env_dict)
  File "c:\users\warre\appdata\local\programs\python\python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "c:\users\warre\appdata\local\programs\python\python36\lib\subprocess.py", line 991, in _execute_child
    args = list2cmdline(args)
  File "c:\users\warre\appdata\local\programs\python\python36\lib\subprocess.py", line 481, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'int' is not iterable
Exception in thread run_worker:
Traceback (most recent call last):
  File "c:\users\warre\appdata\local\programs\python\python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\users\warre\appdata\local\programs\python\python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\SentinelMlTfLocal\lib\site-packages\apache_beam\runners\portability\local_job_service.py", line 214, in run
    p = subprocess.Popen(self._worker_command_line, shell=True, env=env_dict)
  File "c:\users\warre\appdata\local\programs\python\python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "c:\users\warre\appdata\local\programs\python\python36\lib\subprocess.py", line 991, in _execute_child
    args = list2cmdline(args)
  File "c:\users\warre\appdata\local\programs\python\python36\lib\subprocess.py", line 481, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'int' is not iterable
```

However, what worked for me where the tfx pipeline runs fine, is in the LocalDAGRunner example, if i comment out the `beam_pipeline_args`  - so the pipeline looks like the below

```
def _create_pipeline(pipeline_name: Text, pipeline_root: Text, data_root: Text,
                     module_file: Text, serving_model_dir: Text,
                     metadata_path: Text) -> pipeline.Pipeline
                     #beam_pipeline_args: List[Text]) -> pipeline.Pipeline:
.....other code here
					 
  return pipeline.Pipeline(
      pipeline_name=pipeline_name,
      pipeline_root=pipeline_root,
      components=[
          example_gen,
          statistics_gen,
          schema_gen,
          example_validator,
          transform,
          trainer,
          model_resolver,
          evaluator,
          pusher,
      ],
      enable_cache=True,
      metadata_connection_config=metadata.sqlite_metadata_connection_config(
          metadata_path))
      #beam_pipeline_args=beam_pipeline_args)

.....other code here

 LocalDagRunner().run(
      _create_pipeline(
          pipeline_name=_pipeline_name,
          pipeline_root=_pipeline_root,
          data_root=_data_root,
          module_file=_module_file,
          serving_model_dir=_serving_model_dir,
          metadata_path=_metadata_path))
          #beam_pipeline_args=_beam_pipeline_args))
```

Is this a known issue for running on Windows machine? Or am i missing any dependencies that needs to be installed? (looking at the examples, i don't see any other dependencies to be installed separately as the Beam and LocalDAG components are purely imported from the tfx library?)

**Comment by arghyaganguly** [comment]
Not reproducible in linux. Seems like window specific issue.

**Comment by charlesccychen** [comment]
Hi @wlee192, could you give more details on how you are running the example? The error message seems to indicate you are running in a Jupyter notebook environment, but the files you linked are to (non-notebook) Python scripts (taxi_pipeline_{beam,local}.py).

**Comment by wlee192** [comment]
hi @charlesccychen ,

Sure thing, at first i was running the pipeline.py from visual studio code, which has a plugin to Jupyter Notebooks. 
However i've also ran the same pipeline.py script directly from the CMD using ~python pipeline.py and the same issue persist.
