### ISSUE TITLE
TFX taxi template skaffold build throws "invalid reference format" Error

### ISSUE THREAD

**Issue by priya170807** [tensorflow/tfx#3346]
I am just trying the getting started example of taxi data on GCP and trying to run the template. The skaffold is throwing error while building the container image. Tried multiple times but still getting the same error.

2021-03-09 02:39:35.168885: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/nccl2/lib:/usr/local/cuda/extras/CUPTI/lib64
2021-03-09 02:39:35.168934: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
CLI
Creating pipeline
Detected Kubeflow.
Use --engine flag if you intend to use a different orchestrator.
Reading build spec from build.yaml
Target image gcr.io/test-project-one-307022/tfx-pipeline is not used. If the build spec is provided, update the target image in the build spec file build.yaml.
Use skaffold to build the container image.
/home/jupyter/.local/bin/skaffold
Error response from daemon: invalid reference format. Docker build ran into internal error. Please retry.
If this keeps happening, please open an issue..
No container image is built.
Traceback (most recent call last):
  File "/opt/conda/bin/tfx", line 10, in <module>
    sys.exit(cli_group())
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tfx/tools/cli/commands/pipeline.py", line 117, in create_pipeline
    handler_factory.create_handler(ctx.flags_dict).create_pipeline()
  File "/opt/conda/lib/python3.7/site-packages/tfx/tools/cli/handler/kubeflow_handler.py", line 75, in create_pipeline
    skaffold_cmd)
  File "/opt/conda/lib/python3.7/site-packages/tfx/tools/cli/handler/kubeflow_handler.py", line 291, in _build_pipeline_image
    skaffold_cmd=skaffold_cmd).build()
  File "/opt/conda/lib/python3.7/site-packages/tfx/tools/cli/container_builder/builder.py", line 95, in build
    image_sha = skaffold_cli.build(buildspec_filename=self._buildspec.filename)
  File "/opt/conda/lib/python3.7/site-packages/tfx/tools/cli/container_builder/skaffold_cli.py", line 52, in build
    buildspec_filename
  File "/opt/conda/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/opt/conda/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['skaffold', 'build', '-q', '--output={{json .}}', '-f', 'build.yaml']' returned non-zero exit status 1.

**Comment by jiyongjung0** [comment]
Hi, thank you for the report.

Could you check [the answer in a similar issue](https://github.com/tensorflow/tfx/issues/3191#issuecomment-776428174)?

By the way, it would be helpful if you can provide the TFX version used and the content of the `build.yaml` file.

**Comment by priya170807** [comment]
Hi 
Thank you responding quickly.
Tried doing the following

`!skaffold version
!python3 -c "from tfx import version ; print('TFX version: {}'.format(version.__version__))"`

Output

`v1.20.0
TFX version: 0.21.5`

**Comment by jiyongjung0** [comment]
Thank you for the information. It seems that your TFX version is not compatible with latest skaffold.

There are two possible solutions here.
- Update `build.yaml` file manually: See the [linked answer](https://github.com/tensorflow/tfx/issues/3191#issuecomment-776428174)
- Update tfx to the latest version and delete `build.yaml` which will be regenerated when you run the pipeline next time.

Could you try one of above?

**Comment by priya170807** [comment]
yeah, I will try...

**Comment by priya170807** [comment]
Thank you!..it is fixed
