### ISSUE TITLE
BigQueryToElwcExampleGen fails with AssertionError

### ISSUE THREAD

**Issue by manger719** [tensorflow/tfx#3610]
**System information**

- Have I specified the code to reproduce the issue(Yes/No): Yes
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows),
  Interactive Notebook, Google Cloud, etc): Local MacOS
- TensorFlow version (you are using): 2.4.1
- TFX Version: 0.28.0
- Python version: 3.7.6

**Describe the current behavior**
I am trying to make a simple example of BigQueryToElwcExampleGen to understand how it works. However, it results in beam giving an AssertionError.

**Describe the expected behavior**
Records from BigQuery serialized and saved successfully in ELWC format.

**Standalone code to reproduce the issue**
```
import os

from tfx.extensions.google_cloud_big_query.experimental.elwc_example_gen.component.component import BigQueryToElwcExampleGen
from tfx.orchestration.local.local_dag_runner import LocalDagRunner
from tfx.extensions.google_cloud_big_query.experimental.elwc_example_gen.proto.elwc_config_pb2 import ElwcConfig

from tfx.orchestration import metadata, pipeline

GOOGLE_CLOUD_PROJECT = "my-project"  # Replace with your GCP project
GCS_BUCKET_NAME = "gs://my-bucket"  # Replace with your GCS bucket


query = """
    select 'a' as context, 1 as example
    union all select 'b', 2
    union all select 'b', 3"""

example_gen = BigQueryToElwcExampleGen(query=query, elwc_config=ElwcConfig(context_feature_fields=["context"]))
components = [example_gen]

pipeline = pipeline.Pipeline(
    pipeline_name="elwc_test",
    pipeline_root="elwc_test",
    components=components,
    metadata_connection_config=metadata.sqlite_metadata_connection_config(
        "elwc_test/metadata.db"),
    beam_pipeline_args=[
        '--project=' + GOOGLE_CLOUD_PROJECT,
        '--temp_location=' + os.path.join(GCS_BUCKET_NAME, 'tmp'),
    ],
)

LocalDagRunner().run(pipeline)
```

Trying to run this results in the following error:
```
Traceback (most recent call last):
  File "test.py", line 41, in <module>
    LocalDagRunner().run(pipeline)
  File "/Users/max.anger/.virtualenvs/sandbox/lib/python3.7/site-packages/tfx/orchestration/local/local_dag_runner.py", line 129, in run
    component_launcher.launch()
  File "/Users/max.anger/.virtualenvs/sandbox/lib/python3.7/site-packages/tfx/orchestration/portable/launcher.py", line 405, in launch
    executor_output = self._run_executor(execution_info)
  File "/Users/max.anger/.virtualenvs/sandbox/lib/python3.7/site-packages/tfx/orchestration/portable/launcher.py", line 306, in _run_executor
    executor_output = self._executor_operator.run_executor(execution_info)
  File "/Users/max.anger/.virtualenvs/sandbox/lib/python3.7/site-packages/tfx/orchestration/portable/python_executor_operator.py", line 110, in run_executor
    execution_info.exec_properties)
  File "/Users/max.anger/.virtualenvs/sandbox/lib/python3.7/site-packages/tfx/components/example_gen/base_example_gen_executor.py", line 324, in Do
    split_name)))
  File "/Users/max.anger/.virtualenvs/sandbox/lib/python3.7/site-packages/apache_beam/pipeline.py", line 580, in __exit__
    self.result = self.run()
  File "/Users/max.anger/.virtualenvs/sandbox/lib/python3.7/site-packages/apache_beam/pipeline.py", line 559, in run
    return self.runner.run_pipeline(self, self._options)
  File "/Users/max.anger/.virtualenvs/sandbox/lib/python3.7/site-packages/apache_beam/runners/direct/direct_runner.py", line 133, in run_pipeline
    return runner.run_pipeline(pipeline, options)
  File "/Users/max.anger/.virtualenvs/sandbox/lib/python3.7/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 183, in run_pipeline
    pipeline.to_runner_api(default_environment=self._default_environment))
  File "/Users/max.anger/.virtualenvs/sandbox/lib/python3.7/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 193, in run_via_runner_api
    return self.run_stages(stage_context, stages)
  File "/Users/max.anger/.virtualenvs/sandbox/lib/python3.7/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 359, in run_stages
    bundle_context_manager,
  File "/Users/max.anger/.virtualenvs/sandbox/lib/python3.7/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 555, in _run_stage
    bundle_manager)
  File "/Users/max.anger/.virtualenvs/sandbox/lib/python3.7/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 595, in _run_bundle
    data_input, data_output, input_timers, expected_timer_output)
  File "/Users/max.anger/.virtualenvs/sandbox/lib/python3.7/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 896, in process_bundle
    result_future = self._worker_handler.control_conn.push(process_bundle_req)
  File "/Users/max.anger/.virtualenvs/sandbox/lib/python3.7/site-packages/apache_beam/runners/portability/fn_api_runner/worker_handlers.py", line 380, in push
    response = self.worker.do_instruction(request)
  File "/Users/max.anger/.virtualenvs/sandbox/lib/python3.7/site-packages/apache_beam/runners/worker/sdk_worker.py", line 607, in do_instruction
    getattr(request, request_type), request.instruction_id)
  File "/Users/max.anger/.virtualenvs/sandbox/lib/python3.7/site-packages/apache_beam/runners/worker/sdk_worker.py", line 644, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/Users/max.anger/.virtualenvs/sandbox/lib/python3.7/site-packages/apache_beam/runners/worker/bundle_processor.py", line 1000, in process_bundle
    element.data)
  File "/Users/max.anger/.virtualenvs/sandbox/lib/python3.7/site-packages/apache_beam/runners/worker/bundle_processor.py", line 228, in process_encoded
    self.output(decoded_value)
  File "apache_beam/runners/worker/operations.py", line 357, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 359, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 221, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 718, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 719, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1241, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1306, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1239, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 587, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1401, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/worker/operations.py", line 221, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 718, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 719, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1241, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1306, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1239, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 587, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1401, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/worker/operations.py", line 221, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 718, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 719, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1241, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1306, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1239, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 768, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 891, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
  File "apache_beam/runners/common.py", line 1401, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/worker/operations.py", line 221, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 718, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 719, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1241, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1321, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "/Users/max.anger/.virtualenvs/sandbox/lib/python3.7/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "apache_beam/runners/common.py", line 1239, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 768, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 893, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
  File "/Users/max.anger/.virtualenvs/sandbox/lib/python3.7/site-packages/apache_beam/io/iobase.py", line 1132, in process
    self.writer.write(element)
  File "/Users/max.anger/.virtualenvs/sandbox/lib/python3.7/site-packages/apache_beam/io/filebasedsink.py", line 420, in write
    self.sink.write_record(self.temp_handle, value)
  File "/Users/max.anger/.virtualenvs/sandbox/lib/python3.7/site-packages/apache_beam/io/filebasedsink.py", line 146, in write_record
    self.write_encoded_record(file_handle, self.coder.encode(value))
  File "/Users/max.anger/.virtualenvs/sandbox/lib/python3.7/site-packages/apache_beam/coders/coders.py", line 464, in encode
    return self.get_impl().encode(value)
  File "apache_beam/coders/coder_impl.py", line 498, in apache_beam.coders.coder_impl.BytesCoderImpl.encode
  File "apache_beam/coders/coder_impl.py", line 499, in apache_beam.coders.coder_impl.BytesCoderImpl.encode
RuntimeError: AssertionError: (examples {
  features {
    feature {
      key: "example"
      value {
        int64_list {
          value: 1
        }
      }
    }
  }
}
context {
  features {
    feature {
      key: "context"
      value {
        bytes_list {
          value: "a"
        }
      }
    }
  }
}
, <class 'tensorflow_serving.apis.input_pb2.ExampleListWithContext'>) [while running 'WriteSplit[train]/Write/Write/WriteImpl/WriteBundles']
```

**Comment by 1025KB** [comment]
Did you set your Cloud project and bucket?

**Comment by manger719** [comment]
> Did you set your Cloud project and bucket?

I did

**Comment by casassg** [comment]
I believe #4433 should fix it.

**Comment by pindinagesh** [comment]
@manger719 

Could you please respond on @casassg's comment and take a look at above mentioned [PR](https://github.com/tensorflow/tfx/pull/4433). let us know if it's resolved your issue so that it can be closed. Thanks!
