### ISSUE TITLE
BigQueryExampleGen creates temporary dataset on a non-configurable Location (US)

### ISSUE THREAD

**Issue by axelborja** [tensorflow/tfx#3754]
**System information**

- Have I specified the code to reproduce the issue: Yes
- Environment in which the code is executed: GCP - Interactive Notebook
- TensorFlow version: 2.4
- TFX Version: 0.29.0 & 0.30.0
- Python version: 3.7

**Describe the current behavior**

In order to create TFRecord examples, BigQueryExampleGen must first run a job on BigQuery to materialize query results. A side effect of this process is the creation of a temp dataset and a temp table on `location=US`.

Unfortunately, It appears that we are not able to change the location of this temp resources.

This is definitely a blocker.

For example in my Company, we have restriction to only use resources on `location=EU`. 

So because of that, we are not able to use TFX with BigQuery.

**Describe the expected behavior**

We should be able to specify the `BigQueryExampleGen` temp resources location.

**Standalone code to reproduce the issue**

```python
import os
from typing import List, Text

from tfx.extensions.google_cloud_big_query.example_gen import component as big_query_example_gen_component
from tfx.orchestration import pipeline
from tfx.orchestration import metadata
from tfx.orchestration.beam.beam_dag_runner import BeamDagRunner


_pipeline_name = 'chicago_taxi_pipeline_bq'


_tfx_root = os.path.join(os.environ['HOME'], 'tfx_root')
_pipeline_root = os.path.join(_tfx_root, _pipeline_name)
_metadata_path = os.path.join(_tfx_root, 'metadata', _pipeline_name, 'metadata.db')


# TODO: Fill with a project_id with US restriction.
_project_id = 'XXX'
_gcp_region = 'eu-west1'


_beam_bq_pipeline_args = [
    '--runner=DirectRunner',
    '--direct_running_mode=multi_processing',
    '--direct_num_workers=0',
    '--project=' + _project_id,
    '--region=' + _gcp_region
]


_query_sample_rate = 0.001
_max_int64 = '0x7FFFFFFFFFFFFFFF'
_query = """
         SELECT
           IFNULL(pickup_community_area, 0) as pickup_community_area,
           fare,
           EXTRACT(MONTH FROM trip_start_timestamp) AS trip_start_month,
           EXTRACT(HOUR FROM trip_start_timestamp) AS trip_start_hour,
           EXTRACT(DAYOFWEEK FROM trip_start_timestamp) AS trip_start_day,
           UNIX_SECONDS(trip_start_timestamp) AS trip_start_timestamp,
           IFNULL(pickup_latitude, 0) as pickup_latitude,
           IFNULL(pickup_longitude, 0) as pickup_longitude,
           IFNULL(dropoff_latitude, 0) as dropoff_latitude,
           IFNULL(dropoff_longitude, 0) as dropoff_longitude,
           trip_miles,
           IFNULL(pickup_census_tract, 0) as pickup_census_tract,
           IFNULL(dropoff_census_tract, 0) as dropoff_census_tract,
           payment_type,
           IFNULL(company, 'NA') as company,
           IFNULL(trip_seconds, 0) as trip_seconds,
           IFNULL(dropoff_community_area, 0) as dropoff_community_area,
           tips
         FROM `bigquery-public-data.chicago_taxi_trips.taxi_trips`
         WHERE (ABS(FARM_FINGERPRINT(unique_key)) / {max_int64})
           < {query_sample_rate}""".format(
               max_int64=_max_int64, query_sample_rate=_query_sample_rate)


def _create_pipeline(pipeline_name: Text, 
                     pipeline_root: Text, 
                     query: Text, 
                     metadata_path: Text,
                     beam_pipeline_args: List[Text]) -> pipeline.Pipeline:

  example_gen = big_query_example_gen_component.BigQueryExampleGen(query=query)

  return pipeline.Pipeline(
          pipeline_name=pipeline_name,
          pipeline_root=pipeline_root,
          components=[example_gen],
          metadata_connection_config=metadata.sqlite_metadata_connection_config(metadata_path),
          beam_pipeline_args=beam_pipeline_args,
      )


if __name__ == '__main__':
    BeamDagRunner().run(
      _create_pipeline(
          pipeline_name=_pipeline_name,
          pipeline_root=_pipeline_root,
          query=_query,
          metadata_path=_metadata_path,
          beam_pipeline_args=_beam_bq_pipeline_args
      ))
```

**Other info / logs**

```
Traceback (most recent call last):
  File "/root/apache-beam-2.28.0/lib/python3.7/site-packages/apache_beam/runners/worker/sdk_worker.py", line 289, in _execute
    response = task()
  File "/root/apache-beam-2.28.0/lib/python3.7/site-packages/apache_beam/runners/worker/sdk_worker.py", line 362, in <lambda>
    lambda: self.create_worker().do_instruction(request), request)
  File "/root/apache-beam-2.28.0/lib/python3.7/site-packages/apache_beam/runners/worker/sdk_worker.py", line 607, in do_instruction
    getattr(request, request_type), request.instruction_id)
  File "/root/apache-beam-2.28.0/lib/python3.7/site-packages/apache_beam/runners/worker/sdk_worker.py", line 644, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/root/apache-beam-2.28.0/lib/python3.7/site-packages/apache_beam/runners/worker/bundle_processor.py", line 1000, in process_bundle
    element.data)
  File "/root/apache-beam-2.28.0/lib/python3.7/site-packages/apache_beam/runners/worker/bundle_processor.py", line 228, in process_encoded
    self.output(decoded_value)
  File "apache_beam/runners/worker/operations.py", line 357, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 359, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 221, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 718, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 719, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1241, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1306, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1239, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 587, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1401, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/worker/operations.py", line 221, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 718, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 719, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1241, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1306, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1239, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 587, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1401, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/worker/operations.py", line 221, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 718, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 719, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1241, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1321, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "/root/apache-beam-2.28.0/lib/python3.7/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "apache_beam/runners/common.py", line 1239, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 587, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1374, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "/root/apache-beam-2.28.0/lib/python3.7/site-packages/apache_beam/runners/worker/bundle_processor.py", line 1447, in process
    element, restriction):
  File "/root/apache-beam-2.28.0/lib/python3.7/site-packages/apache_beam/transforms/core.py", line 333, in split_and_size
    for part in self.split(element, restriction):
  File "/root/apache-beam-2.28.0/lib/python3.7/site-packages/apache_beam/io/iobase.py", line 1566, in split
    for source_bundle in source_bundles:
  File "/root/apache-beam-2.28.0/lib/python3.7/site-packages/apache_beam/io/gcp/bigquery.py", line 790, in split
    self._setup_temporary_dataset(bq)
  File "/root/apache-beam-2.28.0/lib/python3.7/site-packages/apache_beam/options/value_provider.py", line 200, in _f
    return fnc(self, *args, **kwargs)
  File "/root/apache-beam-2.28.0/lib/python3.7/site-packages/apache_beam/io/gcp/bigquery.py", line 826, in _setup_temporary_dataset
    bq.create_temporary_dataset(self._get_project(), location)
  File "/root/apache-beam-2.28.0/lib/python3.7/site-packages/apache_beam/utils/retry.py", line 260, in wrapper
    return fun(*args, **kwargs)
  File "/root/apache-beam-2.28.0/lib/python3.7/site-packages/apache_beam/io/gcp/bigquery_tools.py", line 766, in create_temporary_dataset
    project_id, self.temp_dataset_id, location=location)
  File "/root/apache-beam-2.28.0/lib/python3.7/site-packages/apache_beam/utils/retry.py", line 260, in wrapper
    return fun(*args, **kwargs)
  File "/root/apache-beam-2.28.0/lib/python3.7/site-packages/apache_beam/io/gcp/bigquery_tools.py", line 681, in get_or_create_dataset
    response = self.client.datasets.Insert(request)
  File "/root/apache-beam-2.28.0/lib/python3.7/site-packages/apache_beam/io/gcp/internal/clients/bigquery/bigquery_v2_client.py", line 143, in Insert
    config, request, global_params=global_params)
  File "/root/apache-beam-2.28.0/lib/python3.7/site-packages/apitools/base/py/base_api.py", line 731, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
  File "/root/apache-beam-2.28.0/lib/python3.7/site-packages/apitools/base/py/base_api.py", line 737, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
  File "/root/apache-beam-2.28.0/lib/python3.7/site-packages/apitools/base/py/base_api.py", line 604, in __ProcessHttpResponse
    http_response, method_config=method_config, request=request)
RuntimeError: apitools.base.py.exceptions.HttpForbiddenError: HttpError accessing <https://bigquery.googleapis.com/bigquery/v2/projects/XXX/datasets?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'date': 'Mon, 17 May 2021 16:05:55 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'status': '403', 'content-length': '525', '-content-encoding': 'gzip'}>, content <{
  "error": {
    "code": 403,
    "message": "US violates constraint constraints/gcp.resourceLocations on the resource projects/XXX/datasets/temp_dataset_c89d6f25014e40f4b6466ae14b0cbed1",
    "errors": [
      {
        "message": "US violates constraint constraints/gcp.resourceLocations on the resource projects/XXX/datasets/temp_dataset_c89d6f25014e40f4b6466ae14b0cbed1",
        "domain": "global",
        "reason": "policyViolation"
      }
    ],
    "status": "PERMISSION_DENIED"
  }
}
> [while running 'InputToRecord/QueryTable/ReadFromBigQuery/Read/SDFBoundedSourceReader/ParDo(SDFBoundedSourceDoFn)/SplitAndSizeRestriction']
 [while running 'Run[BigQueryExampleGen]']
​```

**Comment by charlesccychen** [comment]
CC: @aaltay @chamikaramj Do you happen to know where the BigQuery temporary location / region can be configured?  Is this by the `custom_gcs_temp_location` flag here (https://github.com/apache/beam/blob/e8d549852c2e3b665fbfd9710445ec29241ba36a/sdks/python/apache_beam/io/gcp/bigquery.py#L1794) or is there some other config or pipeline-level mechanism?

**Comment by axelborja** [comment]
FYI, I also tried to add `--temp_location` to the beam pipeline args:

```python
_beam_bq_pipeline_args = [
    '--runner=DirectRunner',
    '--direct_running_mode=multi_processing',
    '--direct_num_workers=0',
    '--temp_location=gs://XXX/tmp',
    '--project=' + _project_id,
    '--region=' + _gcp_region
]
```


I got exactly the same result.

**Comment by axelborja** [comment]
I also try with TFX 0.30.0. I encountered exactly the same issue.

**Comment by axelborja** [comment]
Ok, it appears that the problem is not related to `TFX` but to more to Apache Beam. 

The Temporary dataset is created [here](https://github.com/apache/beam/blob/v2.28.0/sdks/python/apache_beam/io/gcp/bigquery.py#L826) and the location used is determined by the [following implementation](https://github.com/apache/beam/blob/v2.28.0/sdks/python/apache_beam/io/gcp/bigquery_tools.py#L316).

The location will then be selected by the following rule:

```python
"""
    Get the location of tables referenced in a query.    

    This method returns the location of the first available referenced 
    table for user in the query and depends on the BigQuery service to
    provide error handling for queries that reference tables in multiple
    locations.
"""
```

**Comment by axelborja** [comment]
Because it is not a TFX issue I am closing it.

**Comment by chamikaramj** [comment]
Temporary dataset can be specified using following parameter.
https://github.com/apache/beam/blob/775e75f53f99493ccb5329cc25234a162e8c53e4/sdks/python/apache_beam/io/gcp/bigquery.py#L1901

If not specified, Beam will create one to store query results.

**Comment by orpzs** [comment]
@mxc601 Have you figured a work around for this?
