### ISSUE TITLE
AttributeError: module '__main__' has no attribute 'DummyExecutor' when running a custom component on Kubeflow

### ISSUE THREAD

**Issue by axelborja** [tensorflow/tfx#3900]
**System information**

- Have I specified the code to reproduce the issue: Yes
- Environment in which the code is executed: Interactive Notebook (beam) on Google Cloud that Trigger Pipelines in Kubeflow
- TensorFlow version: 2.4.1
- TFX Version: 0.30.0
- Python version: 3.7
- Python dependencies (from `pip freeze` output): 
```absl-py==0.11.0
apache-beam==2.28.0
argon2-cffi==20.1.0
astunparse==1.6.3
async-generator==1.10
attrs==20.3.0
avro-python3==1.8.2
backcall==0.2.0
bleach==3.3.0
cachetools==4.2.2
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
click==7.1.2
cloudpickle==1.6.0
colorama==0.4.4
crcmod==1.7
cycler==0.10.0
Cython==0.29.13
decorator==5.0.9
defusedxml==0.7.1
Deprecated==1.2.12
dill==0.3.1.1
docker==4.4.4
docopt==0.6.2
docstring-parser==0.8.1
entrypoints==0.3
facets-overview==1.0.0
fastavro==1.0.0.post1
fasteners==0.16
fire==0.4.0
flatbuffers==1.12
future==0.18.2
gast==0.3.3
google-api-core==1.28.0
google-api-python-client==1.12.8
google-apitools==0.5.31
google-auth==1.30.1
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.4.4
google-cloud-aiplatform==0.7.1
google-cloud-bigquery==1.28.0
google-cloud-bigtable==1.0.0
google-cloud-build==2.0.0
google-cloud-core==1.4.1
google-cloud-datastore==1.7.4
google-cloud-dlp==1.0.0
google-cloud-language==1.3.0
google-cloud-pubsub==1.0.2
google-cloud-spanner==1.19.1
google-cloud-storage==1.38.0
google-cloud-videointelligence==1.16.1
google-cloud-vision==1.0.0
google-crc32c==1.1.2
google-pasta==0.2.0
google-resumable-media==1.3.0
googleapis-common-protos==1.53.0
grpc-google-iam-v1==0.12.3
grpcio==1.32.0
grpcio-gcp==0.2.2
guppy3==3.0.9
h5py==2.10.0
hdfs==2.5.8
httplib2==0.17.4
idna==2.10
importlib-metadata==4.2.0
ipykernel==5.5.5
ipython==7.23.1
ipython-genutils==0.2.0
ipywidgets==7.6.3
jedi==0.18.0
Jinja2==2.11.3
joblib==0.14.1
jsonschema==3.2.0
jupyter-client==6.1.12
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
Keras-Preprocessing==1.1.2
keras-tuner==1.0.1
kfp==1.6.1
kfp-pipeline-spec==0.1.8
kfp-server-api==1.6.0
kiwisolver==1.3.1
kubernetes==11.0.0
libcst==0.3.19
Markdown==3.3.4
MarkupSafe==2.0.1
matplotlib==3.4.2
matplotlib-inline==0.1.2
mistune==0.8.4
ml-metadata==0.30.0
ml-pipelines-sdk==0.30.0
mmh3==2.5.1
mock==2.0.0
mypy-extensions==0.4.3
nbclient==0.5.3
nbconvert==6.0.7
nbformat==5.1.3
nest-asyncio==1.5.1
nose==1.3.7
notebook==6.4.0
numpy==1.19.5
oauth2client==4.1.3
oauthlib==3.1.0
opt-einsum==3.3.0
packaging==20.9
pandas==1.1.4
pandocfilters==1.4.3
parso==0.8.2
pbr==5.6.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.2.0
portpicker==1.4.0
prometheus-client==0.10.1
prompt-toolkit==3.0.18
proto-plus==1.18.1
protobuf==3.17.2
protorpc==0.12.0
ptyprocess==0.7.0
pyarrow==2.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pydot==1.4.1
Pygments==2.9.0
PyHamcrest==1.10.1
pymongo==3.9.0
pyparsing==2.4.7
pyrsistent==0.17.3
python-dateutil==2.8.1
python-gflags==3.0.6
pytz==2019.3
PyYAML==5.4.1
pyzmq==22.1.0
requests==2.25.1
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
rsa==4.7.2
scikit-learn==0.24.2
scipy==1.4.1
Send2Trash==1.5.0
six==1.15.0
sql==0.4.0
strip-hints==0.1.9
tabulate==0.8.9
tenacity==7.0.0
tensorboard==2.5.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.4.1
tensorflow-data-validation==0.30.0
tensorflow-estimator==2.4.0
tensorflow-hub==0.9.0
tensorflow-metadata==0.30.0
tensorflow-model-analysis==0.30.0
tensorflow-serving-api==2.4.1
tensorflow-transform==0.30.0
termcolor==1.1.0
terminado==0.10.0
terminaltables==3.1.0
testpath==0.5.0
tfx==0.30.0
tfx-bsl==0.30.0
threadpoolctl==2.1.0
timeloop==1.0.2
tornado==6.1
tqdm==4.61.0
traitlets==5.0.5
typing-extensions==3.7.4.3
typing-inspect==0.6.0
uritemplate==3.0.1
urllib3==1.26.5
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.0.1
Werkzeug==2.0.1
widgetsnbextension==3.5.1
wrapt==1.12.1
zipp==3.4.1
```

**Describe the current behavior**

I followed the following both guides [Building Fully Custom Components](https://www.tensorflow.org/tfx/guide/custom_component) && [Custom Python function components](https://www.tensorflow.org/tfx/guide/custom_function_component). 

Unfortunately, both approaches do not appear to work correctly when triggering a pipeline in kubeflow:

When I build a custom component by writing the code of the `Component`, the `ComponentSpec`, and the `ComponentExecutor` or by using the decorator `@component`, and publish a pipeline that uses this component to kubeflow, the component is in failure: `AttributeError: module '__main__' has no attribute 'DummyExecutor'`

![image](https://user-images.githubusercontent.com/14804124/121152907-e712ce00-c845-11eb-96cc-e6a069b971d9.png)

**Describe the expected behavior**

The use of a custom component should work when triggered on kubeflow.

**Standalone code to reproduce the issue**

**- Test 1 : Defining the `Component`, the `ComponentSpec`, and the `ComponentExecutor`**
```python
import os
import absl
import uuid

import kfp
import tfx

from typing import Dict, Any, Optional, List, Text

from kfp.v2.google import client

from tfx import dsl
from tfx import types
from tfx.dsl.components.base import executor_spec
from tfx.components import Transform
from tfx.orchestration import pipeline
from tfx.types import channel_utils, standard_artifacts


# VARIABLES TO FILL
_project_id = 'project-xxx'
_gcp_region = 'europe-west4'
_gcs_bucket_name = 'bucket-xxx'
_pipeline_name = 'test-xxx'


class DummyComponentSpec(types.ComponentSpec):
    PARAMETERS = {'name': types.component_spec.ExecutionParameter(type=Text)}
    INPUTS = {}
    OUTPUTS = {'examples': types.component_spec.ChannelParameter(type=standard_artifacts.Examples),
               'schema': types.component_spec.ChannelParameter(type=standard_artifacts.Schema)}

class DummyExecutor(tfx.dsl.components.base.base_executor.BaseExecutor):
    def Do(self, 
           input_dict: Dict[Text, List[types.Artifact]],
           output_dict: Dict[Text, List[types.Artifact]],
           exec_properties: Dict[Text, Any]) -> None:
      print("Do Dummy Executor !")

class DummyComponent(tfx.dsl.components.base.base_component.BaseComponent):
    
  SPEC_CLASS = DummyComponentSpec
  EXECUTOR_SPEC = executor_spec.ExecutorClassSpec(DummyExecutor)

  def __init__(self,
               examples: types.Channel = None,
               schema: types.Channel = None,
               name: Optional[Text] = None):
    if not examples:
        examples = standard_artifacts.Examples()
        examples.uri = 'gs://XXX'
        examples = channel_utils.as_channel([examples])
    if not schema:
        schema = standard_artifacts.Schema()
        schema.uri = 'gs://XXX'
        schema = channel_utils.as_channel([schema])
    if not name:
        name = "Dummy Component"
    spec = DummyComponentSpec(examples=examples, schema=schema, name=name)
    super(DummyComponent, self).__init__(spec=spec)
    

def _create_pipeline(pipeline_name: Text, 
                     pipeline_root: Text, 
                     beam_pipeline_args: List[Text]) -> pipeline.Pipeline:

    dummy_component = DummyComponent()
        
    return pipeline.Pipeline(
          pipeline_name=pipeline_name,
          pipeline_root=pipeline_root,
          components=[
              dummy_component,
          ],
          beam_pipeline_args=beam_pipeline_args,
      )


absl.logging.set_verbosity(absl.logging.WARNING)

# Path to various pipeline artifact.
_pipeline_root = 'gs://{}/pipeline_root/{}'.format(_gcs_bucket_name, _pipeline_name)

#Tmp Path
_temp_location = 'gs://{}/pipeline_tmp/{}'.format(_gcs_bucket_name, _pipeline_name)

_beam_pipeline_args = [
    '--runner=DirectRunner',
    '--direct_running_mode=multi_processing',
    '--direct_num_workers=0',
    '--temp_location=' + _temp_location,
    '--project=' + _project_id,
    '--region=' + _gcp_region
]


training_pipeline = _create_pipeline(
      pipeline_name=_pipeline_name,
      pipeline_root=_pipeline_root,
      beam_pipeline_args=_beam_pipeline_args
  )

PIPELINE_DEFINITION_FILE = 'training_pipeline.json'

from tfx.orchestration.kubeflow.v2.kubeflow_v2_dag_runner import KubeflowV2DagRunner, KubeflowV2DagRunnerConfig

runner = KubeflowV2DagRunner(
    config=KubeflowV2DagRunnerConfig(),
    output_filename=PIPELINE_DEFINITION_FILE)

_ = runner.run(training_pipeline)

pipelines_client = client.AIPlatformClient(
    project_id=_project_id,
    region=_gcp_region,
)

_ = pipelines_client.create_run_from_job_spec(PIPELINE_DEFINITION_FILE)
```

**- Test 2 : Using the decorator `@component`**
```python
import absl

import kfp
import tfx

from typing import Dict, Any, Optional, List, Text
from kfp.v2.google import client
from tfx.orchestration import pipeline


# VARIABLES TO FILL
_project_id = 'project-xxx'
_gcp_region = 'europe-west4'
_gcs_bucket_name = 'bucket-xxx'
_pipeline_name = 'test-xxx'


from tfx.dsl.component.experimental.decorators import component
@component
def DummyComponent(
    examples: tfx.dsl.component.experimental.annotations.OutputArtifact[tfx.types.standard_artifacts.Examples],
    schema: tfx.dsl.component.experimental.annotations.OutputArtifact[tfx.types.standard_artifacts.Schema],
) -> tfx.dsl.component.experimental.annotations.OutputDict(dummy_val=int):
    print("Do Dummy Function !")
    return {
        'dummy_val': 42
      }


def _create_pipeline(pipeline_name: Text, 
                     pipeline_root: Text, 
                     beam_pipeline_args: List[Text]) -> pipeline.Pipeline:

    dummy_component = DummyComponent()
        
    return pipeline.Pipeline(
          pipeline_name=pipeline_name,
          pipeline_root=pipeline_root,
          components=[
              dummy_component,
          ],
          beam_pipeline_args=beam_pipeline_args,
      )


absl.logging.set_verbosity(absl.logging.WARNING)

# Path to various pipeline artifact.
_pipeline_root = 'gs://{}/pipeline_root/{}'.format(_gcs_bucket_name, _pipeline_name)

#Tmp Path
_temp_location = 'gs://{}/pipeline_tmp/{}'.format(_gcs_bucket_name, _pipeline_name)

_beam_pipeline_args = [
    '--runner=DirectRunner',
    '--direct_running_mode=multi_processing',
    '--direct_num_workers=0',
    '--temp_location=' + _temp_location,
    '--project=' + _project_id,
    '--region=' + _gcp_region
]

training_pipeline = _create_pipeline(
      pipeline_name=_pipeline_name,
      pipeline_root=_pipeline_root,
      beam_pipeline_args=_beam_pipeline_args
  )

PIPELINE_DEFINITION_FILE = 'training_pipeline.json'

from tfx.orchestration.kubeflow.v2.kubeflow_v2_dag_runner import KubeflowV2DagRunner, KubeflowV2DagRunnerConfig

runner = KubeflowV2DagRunner(
    config=KubeflowV2DagRunnerConfig(),
    output_filename=PIPELINE_DEFINITION_FILE)

_ = runner.run(training_pipeline)

pipelines_client = client.AIPlatformClient(
    project_id=_project_id,
    region=_gcp_region,
)

_ = pipelines_client.create_run_from_job_spec(PIPELINE_DEFINITION_FILE)
```

When running the same pipeline with the BeamDagRunner, the pipeline succeeds.
```
from tfx.orchestration.beam.beam_dag_runner import BeamDagRunner

BeamDagRunner().run(training_pipeline)
```

**Other info / logs**
```
2021-06-08T08:17:11.900068475ZTraceback (most recent call last):
Error
2021-06-08T08:17:11.900072937Z File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
Error
2021-06-08T08:17:11.900267812Z "__main__", mod_spec)
Error
2021-06-08T08:17:11.900279822Z File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
Error
2021-06-08T08:17:11.900404681Z exec(code, run_globals)
Error
2021-06-08T08:17:11.900412318Z File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/kubeflow/v2/container/kubeflow_v2_run_executor.py", line 156, in <module>
Error
2021-06-08T08:17:11.900561187Z app.run(main, flags_parser=_parse_flags)
Error
2021-06-08T08:17:11.900571816Z File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 300, in run
Error
2021-06-08T08:17:11.900763477Z _run_main(main, args)
Error
2021-06-08T08:17:11.900786468Z File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
Error
2021-06-08T08:17:11.900945832Z sys.exit(main(argv))
Error
2021-06-08T08:17:11.900956366Z File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/kubeflow/v2/container/kubeflow_v2_run_executor.py", line 152, in main
Error
2021-06-08T08:17:11.901057551Z _run_executor(args, beam_args)
Error
2021-06-08T08:17:11.901066778Z File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/kubeflow/v2/container/kubeflow_v2_run_executor.py", line 77, in _run_executor
Error
2021-06-08T08:17:11.901200376Z executor_cls = import_utils.import_class_by_path(args.executor_class_path)
Error
2021-06-08T08:17:11.901211928Z File "/opt/conda/lib/python3.7/site-packages/tfx/utils/import_utils.py", line 41, in import_class_by_path
Error
2021-06-08T08:17:11.901334753Z return getattr(mod, classname)
Error
2021-06-08T08:17:11.901343083ZAttributeError: module '__main__' has no attribute 'DummyComponent_Executor'
```

**Comment by axelborja** [comment]
To make the custom component work, you should:
1 - Create your own docker image based on the TFX image
2 - Install your python package this image
3 - Store this image on GCR
4 - Replace the default TFX image with this image

**Comment by sayakpaul** [comment]
@axelborja how are specifying the updated image? Also, how are you accessing the `custom_components` module from your pipeline code? I am currently facing https://github.com/tensorflow/tfx/issues/4104 and a minimal overview of how you addressing the above-mentioned things will be tremendously helpful.
