### ISSUE TITLE
Unable to use BulkInferrer with model + examples

### ISSUE THREAD

**Issue by chrispankow** [tensorflow/tfx#3927]
If the bug is related to a specific library below, please raise an issue in the
respective repo directly:

[TensorFlow Data Validation Repo](https://github.com/tensorflow/data-validation/issues)

[TensorFlow Model Analysis Repo](https://github.com/tensorflow/model-analysis/issues)

[TensorFlow Transform Repo](https://github.com/tensorflow/transform/issues)

[TensorFlow Serving Repo](https://github.com/tensorflow/serving/issues)

**System information**

- Have I specified the code to reproduce the issue (Yes, No): No
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows),
  Interactive Notebook, Google Cloud, etc): kubernetes dataflow pipeline
- TensorFlow version: N/A (probably 2.1 or 2.2)
- TFX Version: 0.23
- Python version: N/A (probably 3.7 or 3.8)
- Python dependencies (from `pip freeze` output): N/A

**Describe the current behavior**

Inference with `BulkInferrer` is unsuccessful in a kubernetes pipeline DAG with two dependencies: `BigQueryExampleGen` (to generate some samples to provide as `Example`s) and `ImporterNode` (to retrieve a trained model from another run). The two dependencies complete without problem. The `BulkInferrer` instance, initialized as the following in the pipeline:

```python
bulk_inferrer = BulkInferrer(
        # This is the 'examples' key of the of the BigQueryExampleGen output dict
        examples=evaluator_examples,
        # This is the 'result' key of the ImporterNode
        model=ref_model,
        data_spec=bulk_inferrer_pb2.DataSpec(),
        model_spec=bulk_inferrer_pb2.ModelSpec()
)
```

starts up and then crashes with the traceback appended at the end of the report. I traced this locally (through a different pipeline, since I don't really have access to the innards of the kubernetes run) to `tfx-bsl/run_inference.py` on or about [here](https://github.com/tensorflow/tfx-bsl/blob/925bf2bcbf536c2fd5af62e16c141ad2ce7622e2/tfx_bsl/beam/run_inference.py#L758). The issue is here:

```python
      for output_alias, output in outputs.items():
          # Mimic tensor::Split
          values = output[i]
```

where the dimension of `output` is 1. Therefore, when it is indexed, it retrieves the scalar value held inside, which does not have a `dtype` since it is not an array type. I think all members of `output` are expected to have dimension 2, based on the dimensionality of other items in `output`. This is a classification model which outputs four probabilities, over which the argmax is taken. The former has the correct dimensionality, the latter does not. I suspect this is further related to the `batch_size` being set to 1. I do not know why this happens, and I don't know of any controls that the user has to specify this in advance.

**Describe the expected behavior**

`BulkInferrer` produces actual inference output.

**Standalone code to reproduce the issue**

Providing a bare minimum test case or step(s) to reproduce the problem will
greatly help us to debug the issue. If possible, please share a link to
Colab/Jupyter/any notebook.

Since this requires access to models and data which are not publicly available, I cannot provide this beyond what I have already shown. If there are specific questions as to inputs or configurations, or about the pipeline itself, I can probably answer those.

**Name of your Organization (Optional)**

OpenX

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

Abridged traceback (this is repeated several times, so I deduplicated it):
```
INFO:apache_beam.runners.dataflow.dataflow_runner:2021-06-15T22:26:10.455Z: JOB_MESSAGE_BASIC: Finished operation ReadData[eval]/Read+ParseExamples+RunInference/RunInferenceImpl/BatchExamples/ParDo(_GlobalWindowsBatchingDoFn)+RunInference/RunInferenceImpl/Predict/Predict+RunInference/RunInferenceImpl/Predict/BuildPredictionLogForPredictions+WritePredictionLogs/Write/WriteImpl/WindowInto(WindowIntoFn)+WritePredictionLogs/Write/WriteImpl/WriteBundles/WriteBundles+WritePredictionLogs/Write/WriteImpl/Pair+WritePredictionLogs/Write/WriteImpl/GroupByKey/Reify+WritePredictionLogs/Write/WriteImpl/GroupByKey/Write
INFO:apache_beam.runners.dataflow.dataflow_runner:2021-06-15T22:26:10.525Z: JOB_MESSAGE_DETAILED: Cleaning up.
INFO:apache_beam.runners.dataflow.dataflow_runner:2021-06-15T22:26:10.812Z: JOB_MESSAGE_DEBUG: Starting worker pool teardown.
INFO:apache_beam.runners.dataflow.dataflow_runner:2021-06-15T22:26:10.833Z: JOB_MESSAGE_BASIC: Stopping worker pool...
INFO:apache_beam.runners.dataflow.dataflow_runner:2021-06-15T22:28:53.816Z: JOB_MESSAGE_DETAILED: Autoscaling: Resized worker pool from 20 to 0.
INFO:apache_beam.runners.dataflow.dataflow_runner:2021-06-15T22:28:53.866Z: JOB_MESSAGE_BASIC: Worker pool stopped.
INFO:apache_beam.runners.dataflow.dataflow_runner:2021-06-15T22:28:53.904Z: JOB_MESSAGE_DEBUG: Tearing down pending resources...
INFO:apache_beam.runners.dataflow.dataflow_runner:Job 2021-06-15_15_21_50-5109917968726207331 is in state JOB_STATE_FAILED
Traceback (most recent call last):
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 360, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 353, in main
    execution_info = launcher.launch()
  File "/tfx-src/tfx/orchestration/launcher/base_component_launcher.py", line 205, in launch
    execution_decision.exec_properties)
  File "/tfx-src/tfx/orchestration/launcher/in_process_component_launcher.py", line 67, in _run_executor
    executor.Do(input_dict, output_dict, exec_properties)
  File "/tfx-src/tfx/components/bulk_inferrer/executor.py", line 107, in Do
    model_spec)
  File "/tfx-src/tfx/components/bulk_inferrer/executor.py", line 159, in _run_model_inference
    coder=beam.coders.ProtoCoder(prediction_log_pb2.PredictionLog)))
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/pipeline.py", line 556, in __exit__
    self.result.wait_until_finish()
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/runners/dataflow/dataflow_runner.py", line 1633, in wait_until_finish
    self)
apache_beam.runners.dataflow.dataflow_runner.DataflowRuntimeException: Dataflow pipeline failed. State: FAILED, Error:
Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 1213, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 570, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "/usr/local/lib/python3.7/site-packages/tfx_bsl/beam/run_inference.py", line 287, in process
    result = self._post_process(elements, outputs)
  File "/usr/local/lib/python3.7/site-packages/tfx_bsl/beam/run_inference.py", line 737, in _post_process
    dtype=tf.as_dtype(output[i].dtype).as_datatype_enum,
AttributeError: 'bytes' object has no attribute 'dtype'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/dataflow_worker/batchworker.py", line 649, in do_work
    work_executor.execute()
  File "/usr/local/lib/python3.7/site-packages/dataflow_worker/executor.py", line 179, in execute
    op.start()
  File "dataflow_worker/native_operations.py", line 38, in dataflow_worker.native_operations.NativeReadOperation.start
  File "dataflow_worker/native_operations.py", line 39, in dataflow_worker.native_operations.NativeReadOperation.start
  File "dataflow_worker/native_operations.py", line 44, in dataflow_worker.native_operations.NativeReadOperation.start
  File "dataflow_worker/native_operations.py", line 54, in dataflow_worker.native_operations.NativeReadOperation.start
  File "apache_beam/runners/worker/operations.py", line 332, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 195, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 670, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 671, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1215, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1279, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1213, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 569, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1371, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/worker/operations.py", line 195, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 670, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 671, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1215, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1279, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1213, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 569, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1371, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/worker/operations.py", line 195, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 670, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 671, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1215, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1294, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "/usr/local/lib/python3.7/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "apache_beam/runners/common.py", line 1213, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 570, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "/usr/local/lib/python3.7/site-packages/tfx_bsl/beam/run_inference.py", line 287, in process
    result = self._post_process(elements, outputs)
  File "/usr/local/lib/python3.7/site-packages/tfx_bsl/beam/run_inference.py", line 737, in _post_process
    dtype=tf.as_dtype(output[i].dtype).as_datatype_enum,
AttributeError: 'bytes' object has no attribute 'dtype' [while running 'RunInference/RunInferenceImpl/Predict/Predict']
```

**Comment by chrispankow** [comment]
To append an update to this, I am no longer sure that my suggested reasoning is the issue. On a hunch, we modified the model serving outputs to emit labels with a batch x 1 dimensionality. However, we're still getting the same error, so this might be arising from somewhere else.

For the sake of completeness we went from:

```
  outputs['predict_label'] tensor_info:
      dtype: DT_INT64
      shape: (-1)
      name: ArgMax:0
```

to

```
  outputs['predict_label'] tensor_info:
      dtype: DT_INT64
      shape: (-1, 1)
      name: ExpandDims:0
```

with no progress.

**Comment by singhniraj08** [comment]
@chrispankow,

I was not able to replicate the issue on latest release of TFX and BulkInferrer works as expected for me. Ref: [gist](https://colab.sandbox.google.com/gist/singhniraj08/1ef5cea02b3d262b0a18d6ae5f6e619a/components_keras.ipynb)

Please try with the below version of TFX and Tensorflow and let us know if the issue persists. Thank you!
TensorFlow version: 2.10.1
TFX version: 1.11.0

**Comment by singhniraj08** [comment]
Closing this due to inactivity. Please take a look into the answers provided above, feel free to reopen and post your comments(if you still have queries on this). Thank you!
