### ISSUE TITLE
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py" keep throws "get_losses_for" Not Implemented Error when doing save model with signatures for keras model

### ISSUE THREAD

**Issue by axelning** [tensorflow/tfx#3962]
If the bug is related to a specific library below, please raise an issue in the
respective repo directly:

[TensorFlow Data Validation Repo](https://github.com/tensorflow/data-validation/issues)

[TensorFlow Model Analysis Repo](https://github.com/tensorflow/model-analysis/issues)

[TensorFlow Transform Repo](https://github.com/tensorflow/transform/issues)

[TensorFlow Serving Repo](https://github.com/tensorflow/serving/issues)

**System information**

- Have I specified the code to reproduce the issue (Yes, No): Yes
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows),
  Interactive Notebook, Google Cloud, etc):
- TensorFlow version:2.5.0
- TFX Version:0.30.0
- Python version:3.6.7
- Python dependencies (from `pip freeze` output):

**Describe the current behavior**
When defined a transform_features_layer  the save model tries to extract the loss for this layer by calling the get_losses_for function.

Still from the api doc, https://www.tensorflow.org/tfx/transform/api_docs/python/tft/TransformFeaturesLayer
There's no function defined as get_losses_for

Which causing the exception mentioned in title.

**Describe the expected behavior**

**Standalone code to reproduce the issue**

Providing a bare minimum test case or step(s) to reproduce the problem will
greatly help us to debug the issue. If possible, please share a link to
Colab/Jupyter/any notebook.

**Name of your Organization (Optional)**

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by arghyaganguly** [comment]
@axelning , please provide a snippet of your code and full error stack trace to help us debug this issue.

**Comment by axelning** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/tfx/utils/telemetry_utils.py", line 51, in scoped_labels
    yield
  File "/usr/local/lib/python3.6/dist-packages/tfx/orchestration/beam/beam_dag_runner.py", line 277, in run
    logging.info('Node %s is scheduled.', node_id)
  File "/home/luban/.local/lib/python3.6/site-packages/apache_beam/pipeline.py", line 585, in __exit__
    self.result = self.run()
  File "/home/luban/.local/lib/python3.6/site-packages/apache_beam/pipeline.py", line 564, in run
    return self.runner.run_pipeline(self, self._options)
  File "/home/luban/.local/lib/python3.6/site-packages/apache_beam/runners/direct/direct_runner.py", line 131, in run_pipeline
    return runner.run_pipeline(pipeline, options)
  File "/home/luban/.local/lib/python3.6/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 190, in run_pipeline
    pipeline.to_runner_api(default_environment=self._default_environment))
  File "/home/luban/.local/lib/python3.6/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 200, in run_via_runner_api
    return self.run_stages(stage_context, stages)
  File "/home/luban/.local/lib/python3.6/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 366, in run_stages
    bundle_context_manager,
  File "/home/luban/.local/lib/python3.6/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 562, in _run_stage
    bundle_manager)
  File "/home/luban/.local/lib/python3.6/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 602, in _run_bundle
    data_input, data_output, input_timers, expected_timer_output)
  File "/home/luban/.local/lib/python3.6/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 903, in process_bundle
    result_future = self._worker_handler.control_conn.push(process_bundle_req)
  File "/home/luban/.local/lib/python3.6/site-packages/apache_beam/runners/portability/fn_api_runner/worker_handlers.py", line 378, in push
    response = self.worker.do_instruction(request)
  File "/home/luban/.local/lib/python3.6/site-packages/apache_beam/runners/worker/sdk_worker.py", line 610, in do_instruction
    getattr(request, request_type), request.instruction_id)
  File "/home/luban/.local/lib/python3.6/site-packages/apache_beam/runners/worker/sdk_worker.py", line 647, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/home/luban/.local/lib/python3.6/site-packages/apache_beam/runners/worker/bundle_processor.py", line 1001, in process_bundle
    element.data)
  File "/home/luban/.local/lib/python3.6/site-packages/apache_beam/runners/worker/bundle_processor.py", line 229, in process_encoded
    self.output(decoded_value)
  File "apache_beam/runners/worker/operations.py", line 356, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 358, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 220, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 717, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 718, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1235, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1315, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "/home/luban/.local/lib/python3.6/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "apache_beam/runners/common.py", line 1233, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 762, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 887, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
  File "/usr/local/lib/python3.6/dist-packages/tfx/orchestration/beam/beam_dag_runner.py", line 90, in process
    self._run_node()
  File "/usr/local/lib/python3.6/dist-packages/tfx/orchestration/beam/beam_dag_runner.py", line 103, in _run_node
    custom_driver_spec=self._custom_driver_spec).launch()
  File "/usr/local/lib/python3.6/dist-packages/tfx/orchestration/portable/launcher.py", line 431, in launch
    executor_output = self._run_executor(execution_info)
  File "/usr/local/lib/python3.6/dist-packages/tfx/orchestration/portable/launcher.py", line 325, in _run_executor
    executor_output = self._executor_operator.run_executor(execution_info)
  File "/usr/local/lib/python3.6/dist-packages/tfx/orchestration/portable/python_executor_operator.py", line 141, in run_executor
    return run_with_executor(execution_info, executor)
  File "/usr/local/lib/python3.6/dist-packages/tfx/orchestration/portable/python_executor_operator.py", line 66, in run_with_executor
    execution_info.exec_properties)
  File "/usr/local/lib/python3.6/dist-packages/tfx/components/trainer/executor.py", line 194, in Do
    run_fn(fn_args)
  File "/usr/local/lib/python3.6/dist-packages/tfx/components/example_gen/json_example_gen/imlog_proxy_trainer.py", line 246, in run_fn
    signatures=signatures
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 2002, in save
    signatures, options, save_traces)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/save.py", line 157, in save_model
    signatures, options, save_traces)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save.py", line 89, in save
    save_lib.save(model, filepath, signatures, options)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 1033, in save
    obj, signatures, options, meta_graph_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 1198, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 1137, in _build_meta_graph_impl
    signature_serialization.validate_saveable_view(checkpoint_graph_view)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/signature_serialization.py", line 267, in validate_saveable_view
    saveable_view.root):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 116, in list_dependencies
    extra_dependencies = self.list_extra_dependencies(obj)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 145, in list_extra_dependencies
    self._serialization_cache)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 2387, in _list_extra_dependencies_for_serialization
    .list_extra_dependencies_for_serialization(serialization_cache))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/base_serialization.py", line 78, in list_extra_dependencies_for_serialization
    return self.objects_to_serialize(serialization_cache)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 75, in objects_to_serialize
    serialization_cache).objects_to_serialize)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 95, in _get_serialized_attributes
    serialization_cache)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/model_serialization.py", line 57, in _get_serialized_attributes_internal
    serialization_cache))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 104, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 155, in wrap_layer_functions
    original_fns = _replace_child_layer_functions(layer, serialization_cache)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 274, in _replace_child_layer_functions
    serialization_cache).functions)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 95, in _get_serialized_attributes
    serialization_cache)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/model_serialization.py", line 57, in _get_serialized_attributes_internal
    serialization_cache))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 104, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 193, in wrap_layer_functions
    fn.get_concrete_function()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 549, in get_concrete_function
    self.call_collection.add_trace(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 423, in add_trace
    fn.get_concrete_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 550, in get_concrete_function
    return super(LayerCall, self).get_concrete_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 1299, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 1205, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 726, in _initialize
    *args, **kwds))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 3206, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 527, in wrapper
    ret = method(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 572, in call_and_return_conditional_losses
    conditional_losses = layer.get_losses_for(inputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_transform/output_wrapper.py", line 515, in method_override
    raise NotImplementedError(name)
NotImplementedError: get_losses_for [while running 'Run[Trainer]']

**Comment by axelning** [comment]
`def _get_serve_tf_examples_fn(model, tf_transform_output):
	#Returns a function that parses a serialized tf.Example and applies TFT.

	model.tft_layer = tf_transform_output.transform_features_layer()

	@tf.function
	def serve_tf_examples_fn(serialized_tf_examples):
		# Returns the output to be used in the serving signature.
		feature_spec = tf_transform_output.raw_feature_spec()
		feature_spec.pop(_LABEL_KEY)
		parsed_features = tf.io.parse_example(serialized_tf_examples, feature_spec)
		transformed_features = model.tft_layer(parsed_features)
		return model(transformed_features)

	return serve_tf_examples_fn`

**Comment by axelning** [comment]
`signatures = {
		  'serving_default':
			  _get_serve_tf_examples_fn(model,
										tf_transform_output).get_concrete_function(
											tf.TensorSpec(
												shape=[None],
												dtype=tf.string,
												name='examples')),
		
		}
		
		
		#tf.keras.models.save_model(model=model,filepath=fn_args.serving_model_dir, save_format='tf',include_optimizer=False,
		#                           overwrite=True
		#                           #signatures=signatures
		 #)
		model.save(fn_args.serving_model_dir,
				   save_format='tf',
				   signatures=signatures
				   )`

**Comment by axelning** [comment]
@arghyaganguly i  listed the trace back and piece of code above

**Comment by axelning** [comment]
I just improvised a patch to fix this problem.
`  def call_and_return_conditional_losses(inputs, *args, **kwargs):
    """Returns layer (call_output, conditional losses) tuple."""
    call_output = layer_call(inputs, *args, **kwargs)
    if version_utils.is_v1_layer_or_model(layer):
        if hasattr(layer, "losses"):
            if len(getattr(layer, "losses")) == 0:
                conditional_losses = []
        else:conditional_losses = layer.get_losses_for(inputs)
    else:
      conditional_losses = [
          l for l in layer.losses if not hasattr(l, '_unconditional_loss')
      ]
    return call_output, conditional_losses`

**Comment by axelning** [comment]
any updates so far？
