### ISSUE TITLE
ImportError: No module named tfx.examples.chicago_taxi.trainer on Dataflow

### ISSUE THREAD

**Issue by mwalenia** [tensorflow/tfx#47]
I'm trying to run the Chicago Taxi Example on Google Dataflow and I ran into a problem with imports. After setting `PYTHONPATH` env in order to make the python files run on my environment, the pipelines fail with 

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/dataflow_worker/batchworker.py", line 766, in run
  self._load_main_session(self.local_staging_directory)
  File "/usr/local/lib/python2.7/dist-packages/dataflow_worker/batchworker.py", line 482, in _load_main_session
 pickler.load_session(session_file)
 File "/usr/local/lib/python2.7/dist-packages/apache_beam/internal/pickler.py", line 269, in load_session
 return dill.load_session(file_path)
File "/usr/local/lib/python2.7/dist-packages/dill/_dill.py", line 410, in load_session
   module = unpickler.load()
File "/usr/lib/python2.7/pickle.py", line 864, in load
   dispatch[key](self)
 File "/usr/lib/python2.7/pickle.py", line 1139, in load_reduce
value = func(*args)
 File "/usr/local/lib/python2.7/dist-packages/dill/_dill.py", line 828, in _import_module
return getattr(__import__(module, None, None, [obj]), obj)
ImportError: No module named tfx.examples.chicago_taxi.trainer
```

I don't know how to remedy this - is it possible to set an environmental variable in a Dataflow pipeline?

**Comment by krazyhaas** [comment]
Quick update: I've been able to recreate the problem but haven't yet found the fix.

**Comment by krazyhaas** [comment]
Thanks for the PR!  I’ll check it out tomorrow.

**Comment by ChethanUK** [comment]
@mwalenia Line: https://github.com/tensorflow/tfx/blob/942358f5b24dea49e8bde8691507c8cbc508b427/tfx/examples/chicago_taxi/trainer/task.py#L26 is giving 
```
Traceback (most recent call last):
  File "trainer/task.py", line 25, in <module>
    from tfx.examples.chicago_taxi.trainer import model
ImportError: No module named tfx.examples.chicago_taxi.trainer
```
