### ISSUE TITLE
Problem trying to run a simple example. KeyError: 'HOME'

### ISSUE THREAD

**Issue by ianloron00** [tensorflow/tfx#4732]
Hi! I am trying to run a simple tutorial for running tfx locally [tfx tutorial for beginners](https://kirenz.github.io/codelabs/codelabs/tfx-pipeline/#5). 

I followed the tutorial step-by-step since the installations. However, I am receiving the following error when I run the local_runner.py file:

`
2022-03-10 13:30:33.578547: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found                                                                             a GPU set up on your machine.     
2022-03-10 13:30:33.581403: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
CLI
Creating pipeline
Detected Local.
Use --engine flag if you intend to use a different orchestrator.
Traceback (most recent call last):
  File "D:\Users\ian.almeida\.conda\envs\tfx\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Users\ian.almeida\.conda\envs\tfx\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Users\ian.almeida\.conda\envs\tfx\Scripts\tfx.exe\__main__.py", line 7, in <module>
  File "D:\Users\ian.almeida\.conda\envs\tfx\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "D:\Users\ian.almeida\.conda\envs\tfx\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "D:\Users\ian.almeida\.conda\envs\tfx\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Users\ian.almeida\.conda\envs\tfx\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Users\ian.almeida\.conda\envs\tfx\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Users\ian.almeida\.conda\envs\tfx\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:\Users\ian.almeida\.conda\envs\tfx\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "D:\Users\ian.almeida\.conda\envs\tfx\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:\Users\ian.almeida\.conda\envs\tfx\lib\site-packages\tfx\tools\cli\commands\pipeline.py", line 150, in create_pipeline
    handler_factory.create_handler(ctx.flags_dict).create_pipeline()
  File "D:\Users\ian.almeida\.conda\envs\tfx\lib\site-packages\tfx\tools\cli\handler\handler_factory.py", line 106, in create_handler
    return detect_handler(flags_dict)
  File "D:\Users\ian.almeida\.conda\envs\tfx\lib\site-packages\tfx\tools\cli\handler\handler_factory.py", line 67, in detect_handler
    return local_handler.LocalHandler(flags_dict)
  File "D:\Users\ian.almeida\.conda\envs\tfx\lib\site-packages\tfx\tools\cli\handler\base_handler.py", line 43, in __init__    
    self._handler_home_dir = self._get_handler_home()
  File "D:\Users\ian.almeida\.conda\envs\tfx\lib\site-packages\tfx\tools\cli\handler\base_handler.py", line 143, in _get_handler_home
    return os.path.join(os.environ['HOME'], 'tfx', engine_flag, '')
  File "D:\Users\ian.almeida\.conda\envs\tfx\lib\os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'
`

My OS is Windows 10 Pro. Windows don't have the variable "HOME", but "USERPROFILE" instead. Is there an easy way to run in windows without needing to rename all "HOME"s to "USERPROFILE"s?  

Thank you for your support

**Comment by pindinagesh** [comment]
@ianloron00 

Since TFX is not supported on windows, try using docker container for the same and please have a  look at this [issue](https://github.com/tensorflow/tfx/issues/1229) for tracking

**Comment by ianloron00** [comment]
@pindinagesh 
Thank you very much for your response. I haven't found this information in documentation. Anyways, closing issue.

**Comment by jaymon0703** [comment]
Is TFX still not supported in Windows? I am able to run tfx commands such as tfx template copy but run into the issue mentioned here with tfx pipeline create when using Windows. I see no mention of OS constraints in the docs.

**Comment by azizderbel** [comment]
@jaymon0703 the issue with 'tfx pipeline create' command is you need to define a HOME environment variable where a TFX folder will be saved.However, when you run 'tfx run create --pipeline_name' command,you will encounter a Windows related issue in terms of path interpertation. I don't know exactly what is probleme but from what I read in most blogs its related to forward and backslashes interpretation.

**Comment by jaymon0703** [comment]
Thank you. You are correct and I have encountered the error, and ended up using Debian Python 3.8 container.

**Comment by azizderbel** [comment]
Thank you @jaymon0703
