### ISSUE TITLE
`mlmd.errors.InternalError` raised when duplicate entries found in metadata store.

### ISSUE THREAD

**Issue by 0xleowang** [tensorflow/tfx#4970]
**System information**

- Have I specified the code to reproduce the issue (Yes, No): No
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows),
  Interactive Notebook, Google Cloud, etc): AWS with Amazon RDS as the metadata store
- TensorFlow version: 2.5.2
- TFX Version: 1.2.0
- Python version: 3.8
- Python dependencies (from `pip freeze` output): 

```
...
ml-metadata==1.2.0
tensorboard==2.8.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.5.2
tensorflow-data-validation==1.2.0
tensorflow-estimator==2.5.0
tensorflow-hub==0.12.0
tensorflow-metadata==1.2.0
tensorflow-model-analysis==0.33.0
tensorflow-probability==0.13.0
tensorflow-recommenders==0.5.2
tensorflow-serving-api==2.5.3
tensorflow-transform==1.2.0
tfx==1.2.0
tfx-bsl==1.2.0
...
```

**Describe the current behavior**

This issue happens when a Transform component tires to insert an entry to the ML Metadata Store (Amazon RDS), if the entry exists, a `mlmd.errors.InternalError` is raised with `errno: 1062`, and the error failed to be caught by the code below, which leads to a failure for the Transform component.
https://github.com/tensorflow/tfx/blob/d8b226c4c13deec668f60825e3b2d14efdf7ef77/tfx/orchestration/metadata.py#L696

Error: 
```
mlmd.errors.InternalError: mysql_query failed: errno: 1062, error: Duplicate entry '136887-tfx_version-1' for key 'PRIMARY'"
```

**Describe the expected behavior**

When Transform component tires to insert an entry to the ML Metadata Store (Amazon RDS), if the entry exists, a `mlmd.errors.AlreadyExistsError` error should be raised and caught handled by TFX.

**Standalone code to reproduce the issue**

**Name of your Organization (Optional)**

**Other info / logs**

Our current workaround is using the following patch:
```
701c701,703
<     except mlmd.errors.AlreadyExistsError:
---
>     except (mlmd.errors.AlreadyExistsError, mlmd.errors.InternalError) as e:
>       if isinstance(e, mlmd.errors.InternalError) and "errno: 1062" not in e.message:
>         raise e
```

**Comment by jiyongjung0** [comment]
This seems like an issue in MLMD side although the version is a bit outdated. @briansong Could you take a look?

**Comment by BrianSong** [comment]
Thanks for bringing this up.

MLMD raised this as `InternalError` as the query execution failed. I can add another layer on top of the query executor and let it return `AlreadyExistsError`. May I know for "Transform component tires to insert an entry", which domain entity of MLMD(e.g., `Execution`, `Context`, ..) is actually inserted?

**Comment by jiyongjung0** [comment]
Thanks! The code linked by @0xleowang was the place inserting an "Execution". Please correct me if it is not the case @0xleowang !

**Comment by 0xleowang** [comment]
Thanks for looking into this. This is indeed the case. @jiyongjung0 @BrianSong

**Comment by BrianSong** [comment]
I did some investigations, it seems that for inserting an `Execution`, MLMD 1.2.0 already has a wrapper(`IsUniqueConstraintViolated `) to return `InternalError` with `Duplicate` message as `AlreadyExistsError` shown in [1] and [2].

Thus, I wonder for `136887-tfx_version-1`, is this an `Execution`? The code linked is calling [`put_execution()`](https://github.com/tensorflow/tfx/blob/d8b226c4c13deec668f60825e3b2d14efdf7ef77/tfx/orchestration/metadata.py#L690-L693) which can insert not only `Execution`, but also `Artifact`, `Context`, `Event`, `Attribution` and `Association`.

Also, is there a way for me to reproduce this error? Some logs inside the MLMD codebase would help a lot. 

[1] https://github.com/google/ml-metadata/blob/v1.2.0/ml_metadata/metadata_store/rdbms_metadata_access_object.cc#L336-L343
[2] https://github.com/google/ml-metadata/blob/v1.2.0/ml_metadata/metadata_store/rdbms_metadata_access_object.cc#L1226-L1236

**Comment by 0xleowang** [comment]
Here are some additional logs. Hope these can help to identify the issue.
```
[2022-06-20T06:53:49.930Z] File "/venv/lib/python3.8/site-packages/grpc/_channel.py", line 923, in __call__
[2022-06-20T06:53:49.930Z] response.CopyFrom(grpc_method(request, timeout=self._grpc_timeout_sec))
[2022-06-20T06:53:49.930Z] File "/venv/lib/python3.8/site-packages/ml_metadata/metadata_store/metadata_store.py", line 209, in _call_method
[2022-06-20T06:53:49.930Z] ml_metadata.errors.InternalError: mysql_query failed: errno: 1062, error: Duplicate entry '136887-tfx_version-1' for key 'PRIMARY'
[2022-06-20T06:53:49.930Z] Traceback (most recent call last):
[2022-06-20T06:53:49.930Z] File "/venv/lib/python3.8/site-packages/tfx/orchestration/launcher/base_component_launcher.py", line 196, in launch
[2022-06-20T06:53:49.930Z] return launcher.launch()
[2022-06-20T06:53:49.930Z] WARNING:absl:mlmd client InternalError: mysql_query failed: errno: 1062, error: Duplicate entry '136887-tfx_version-1' for key 'PRIMARY'
[2022-06-20T06:53:49.930Z] raise _make_exception(e.details(), e.code().value[0]) # pytype: disable=attribute-error
[2022-06-20T06:53:49.930Z] File "/venv/lib/python3.8/site-packages/ml_metadata/metadata_store/metadata_store.py", line 214, in _call_method
[2022-06-20T06:53:49.930Z] return self._call_method(method_name, request, response)
[2022-06-20T06:53:49.930Z] execution_info = run_beam_component(transform, args.pipeline_config, args.beam_runner_config)
[2022-06-20T06:53:49.930Z] File "/venv/lib/python3.8/site-packages/ml_metadata/metadata_store/metadata_store.py", line 184, in _call
[2022-06-20T06:53:49.930Z] Traceback (most recent call last):
[2022-06-20T06:53:49.930Z] execution_id, a_ids, context_ids = self.store.put_execution(
[2022-06-20T06:53:49.930Z] File "/venv/lib/python3.8/site-packages/tfx/orchestration/metadata.py", line 695, in register_execution
[2022-06-20T06:53:49.930Z] During handling of the above exception, another exception occurred:
[2022-06-20T06:53:49.930Z] >
[2022-06-20T06:53:49.930Z] execution = self._metadata_handler.register_execution(
[2022-06-20T06:53:49.930Z] debug_error_string = "{"created":"@1655708029.424900953","description":"Error received from peer ipv4:***.**.**.***:8080","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"mysql_query failed: errno: 1062, error: Duplicate entry '136887-tfx_version-1' for key 'PRIMARY'","grpc_status":13}"
[2022-06-20T06:53:49.930Z] File "/venv/lib/python3.8/site-packages/tfx/dsl/components/base/base_driver.py", line 272, in pre_execution
[2022-06-20T06:53:49.930Z] execution_decision = driver.pre_execution(
[2022-06-20T06:53:49.930Z] details = "mysql_query failed: errno: 1062, error: Duplicate entry '136887-tfx_version-1' for key 'PRIMARY'"
[2022-06-20T06:53:49.930Z] status = StatusCode.INTERNAL
[2022-06-20T06:53:49.930Z] File "/venv/lib/python3.8/site-packages/tfx/orchestration/launcher/base_component_launcher.py", line 160, in _run_driver
[2022-06-20T06:53:49.930Z] execution_decision = self._run_driver(self._input_dict, self._output_dict,
[2022-06-20T06:53:49.930Z] grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
[2022-06-20T06:53:49.930Z] raise _InactiveRpcError(state)
[2022-06-20T06:53:49.930Z] File "/venv/lib/python3.8/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
[2022-06-20T06:53:49.930Z] return _end_unary_response_blocking(state, call, False, None)
[2022-06-20T06:53:49.930Z] self._call('PutExecution', request, response)
[2022-06-20T06:53:49.930Z] main()
[2022-06-20T06:53:49.930Z] File "/venv/lib/python3.8/site-packages/ml_metadata/metadata_store/metadata_store.py", line 587, in put_execution
```

**Comment by parham12** [comment]
Hi there,
With Apache **Airflow** as the orchestrator, I have the same problem when using **[MLMD]** 1.8.0. A log file related to this issue is attached.
[dag_id=consumer_complaint_pipeline_airflow_run_id=manual__2022-07-12T10_25_40.659461+00_00_task_id=Transform_attempt=1.log](https://github.com/tensorflow/tfx/files/9095522/dag_id.consumer_complaint_pipeline_airflow_run_id.manual__2022-07-12T10_25_40.659461%2B00_00_task_id.Transform_attempt.1.log)

**Comment by BrianSong** [comment]
Thanks for the log, I think I might need to log more details in order to figure out the problem. Is there a way for me to reproduce this error? @0xleowang @jiyongjung0

**Comment by 0xleowang** [comment]
Unfortunately, we only encountered this error a few times, didn't find a way to reproduce it.

**Comment by singhniraj08** [comment]
@0xleowang,

Please provide more log details to reproduce the error on our end if the issue persists. Thanks!
