### ISSUE TITLE
User module not found although it's properly specified

### ISSUE THREAD

**Issue by JakeTheWise** [tensorflow/tfx#500]
My Transform component fails with the following error. Not sure if I'm doing something wrong or if it's a bug...

Local TFX build: https://github.com/tensorflow/tfx/commit/ef9b28b53af7d1c99bdde9dfbaab79a790429e69
TFX image used in pipeline: 0.14.0.dev20190818 from https://hub.docker.com/r/tensorflow/tfx/tags
Kubeflow: v0.5.0
Running on GKE

EDIT: The TFX image used is the release image on TFX DockerHub tagged `0.14.0.dev20190818`, which should be in sync with https://github.com/tensorflow/tfx/commit/ef9b28b53af7d1c99bdde9dfbaab79a790429e69. I'm not using `DataflowRunner` in my pipeline. The pipeline is a custom one, it's not the taxi example. I've confirmed that my module file is properly stored in GCP and that the pipeline can access it — the Transform component is successfully calling my module file's `preprocessing_fn` (confirmed by print statements), so the `KeyError: 'user_module'` error seems to be happening in the Transform component but downstream of `preprocessing_fn`.

```
Traceback (most recent call last):
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 106, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 102, in main
    executor.run()
  File "/opt/venv/lib/python3.5/site-packages/tfx/orchestration/kubeflow/executor_wrappers.py", line 123, in run
    self._exec_properties)
  File "/opt/venv/lib/python3.5/site-packages/tfx/components/transform/executor.py", line 285, in Do
    self.Transform(label_inputs, label_outputs, status_file)
  File "/opt/venv/lib/python3.5/site-packages/tfx/components/transform/executor.py", line 752, in Transform
    compute_statistics, materialize_output_paths)
  File "/opt/venv/lib/python3.5/site-packages/tfx/components/transform/executor.py", line 1042, in _RunBeamImpl
    raw_examples_file_format, output_path))
  File "/opt/venv/lib/python3.5/site-packages/apache_beam/pipeline.py", line 426, in __exit__
    self.run().wait_until_finish()
  File "/opt/venv/lib/python3.5/site-packages/apache_beam/pipeline.py", line 404, in run
    self.to_runner_api(use_fake_coders=True),
  File "/opt/venv/lib/python3.5/site-packages/apache_beam/pipeline.py", line 656, in to_runner_api
    root_transform_id = context.transforms.get_id(self._root_transform())
  File "/opt/venv/lib/python3.5/site-packages/apache_beam/runners/pipeline_context.py", line 84, in get_id
    self._id_to_proto[id] = obj.to_runner_api(self._pipeline_context)
  File "/opt/venv/lib/python3.5/site-packages/apache_beam/pipeline.py", line 877, in to_runner_api
    for part in self.parts],
  File "/opt/venv/lib/python3.5/site-packages/apache_beam/pipeline.py", line 877, in <listcomp>
    for part in self.parts],
  File "/opt/venv/lib/python3.5/site-packages/apache_beam/runners/pipeline_context.py", line 84, in get_id
    self._id_to_proto[id] = obj.to_runner_api(self._pipeline_context)
  File "/opt/venv/lib/python3.5/site-packages/apache_beam/pipeline.py", line 875, in to_runner_api
    spec=transform_to_runner_api(self.transform, context),
  File "/opt/venv/lib/python3.5/site-packages/apache_beam/pipeline.py", line 870, in transform_to_runner_api
    return transform.to_runner_api(context, has_parts=bool(self.parts))
  File "/opt/venv/lib/python3.5/site-packages/apache_beam/transforms/ptransform.py", line 591, in to_runner_api
    urn, typed_param = self.to_runner_api_pickled(context)
  File "/opt/venv/lib/python3.5/site-packages/apache_beam/transforms/ptransform.py", line 624, in to_runner_api_pickled
    pickler.dumps(self))
  File "/opt/venv/lib/python3.5/site-packages/apache_beam/internal/pickler.py", line 230, in dumps
    s = dill.dumps(o)
  File "/opt/venv/lib/python3.5/site-packages/dill/_dill.py", line 294, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "/opt/venv/lib/python3.5/site-packages/dill/_dill.py", line 287, in dump
    pik.dump(obj)
  File "/usr/lib/python3.5/pickle.py", line 408, in dump
    self.save(obj)
  File "/usr/lib/python3.5/pickle.py", line 520, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.5/pickle.py", line 627, in save_reduce
    save(state)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/venv/lib/python3.5/site-packages/apache_beam/internal/pickler.py", line 198, in new_save_module_dict
    return old_save_module_dict(pickler, obj)
  File "/opt/venv/lib/python3.5/site-packages/dill/_dill.py", line 902, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.5/pickle.py", line 814, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.5/pickle.py", line 840, in _batch_setitems
    save(v)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.5/pickle.py", line 744, in save_tuple
    save(element)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/venv/lib/python3.5/site-packages/dill/_dill.py", line 1386, in save_function
    obj.__dict__), obj=obj)
  File "/usr/lib/python3.5/pickle.py", line 603, in save_reduce
    save(args)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.5/pickle.py", line 744, in save_tuple
    save(element)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/venv/lib/python3.5/site-packages/apache_beam/internal/pickler.py", line 198, in new_save_module_dict
    return old_save_module_dict(pickler, obj)
  File "/opt/venv/lib/python3.5/site-packages/dill/_dill.py", line 902, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.5/pickle.py", line 814, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.5/pickle.py", line 840, in _batch_setitems
    save(v)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/venv/lib/python3.5/site-packages/apache_beam/internal/pickler.py", line 101, in wrapper
    if _is_nested_class(obj) and obj.__module__ != '__main__':
  File "/opt/venv/lib/python3.5/site-packages/apache_beam/internal/pickler.py", line 60, in _is_nested_class
    and cls.__name__ not in sys.modules[cls.__module__].__dict__)
KeyError: 'user_module'
```

**Comment by neuromage** [comment]
@JakeTheWise thanks for the report. A few quick questions: 
- were you using DataflowRunner for this? 
- were you running the example chicago taxi pipeline or something else? 
- did you build the image yourself from the commit, and have the pipeline point to this image? Or were you using release image on Dockerhub?

**Comment by JakeTheWise** [comment]
- were you using DataflowRunner for this? No, I had trouble enabling the
   dataflow API so I was using whatever the default is. I can try dataflow
   again, though!
   - were you running the example chicago taxi pipeline or something else?
   No, I'm running a custom pipeline starting from some tfrecords with a
   custom tf.estimator.
   - did you build the image yourself from the commit, and have the
   pipeline point to this image? Or were you using release image on Dockerhub?
   Sorry I didn't clarify this - I used the release image on dockerhub.

**Comment by 1025KB** [comment]
Hi, It seems your transform can't access the module file (taxi_utils.py for taxi example), could you check if your module file is stored in gcp and setup correctly in python dsl

**Comment by JakeTheWise** [comment]
The module file is correctly stored in GCP and is correctly getting accessed by my kubeflow pipeline. I've confirmed this by adding print statements to my `preprocessing_fn` in the module file, and I confirm these print statements appear in the kubeflow pipeline logs for the Transform component.

**Comment by neuromage** [comment]
The code at a given commit is only guaranteed to be compatible with the image built from that commit. The image on dockerhub is pointing to version 0.13, and the commit you specified is nearly at HEAD, so many things have changed since. Hence I recommend building and using an image from the commit version you used. Can you try that and let us know if this problem still occurs?

**Comment by JakeTheWise** [comment]
I'm using the `0.14.0.dev20190818` from DockerHub, which should be in sync with the TFX commit (https://github.com/tensorflow/tfx/commit/ef9b28b53af7d1c99bdde9dfbaab79a790429e69) I used to build the pipeline file, right? I'm still getting this KeyError.

**Comment by neuromage** [comment]
I'm not sure they're in sync. Would you mind trying the same pipeline using a later image? Say `0.14.0.dev20190819` instead?

**Comment by JakeTheWise** [comment]
Ok, I tried using `0.14.0.dev20190820` with 10586eff821ea972397d53461068884532917d5f (the latest commit to master on Aug 20) and got the same error.

**Comment by JakeTheWise** [comment]
@neuromage any update on this?

**Comment by JakeTheWise** [comment]
It appears that this bug is due to using a tf.keras.Model subclass in the pipeline. This is now tracked by https://github.com/tensorflow/tfx/issues/584. Closing.

**Comment by neuromage** [comment]
Thanks for figuring this out! I never could reproduce it, and I did suspect it may have something to do with the utils.py file hierarchy and importing getting confused. Can you paste your module file, exactly as is, but without the code (i.e., just replace code with `pass` or something)?

**Comment by JakeTheWise** [comment]
```
from __future__ import division
from __future__ import print_function

import tensorflow as tf
import tensorflow_model_analysis as tfma
import tensorflow_transform as tft
from tensorflow_transform.tf_metadata import schema_utils


_LABEL_KEY = '...'
SEQUENCE_FEATURES = [...]


def _gzip_reader_fn(filenames):
    """Small utility returning a record reader that can read gzip'ed files."""
    return tf.data.TFRecordDataset(
        filenames,
        compression_type='GZIP')


def _get_raw_feature_spec(schema):
    return schema_utils.schema_as_feature_spec(schema).feature_spec


def preprocessing_fn(inputs):
    ...
    return outputs


def _example_serving_receiver_fn(tf_transform_output, schema):
    """Build the serving in inputs.

    Args:
      tf_transform_output: A TFTransformOutput.
      schema: the schema of the input data.

    Returns:
      Tensorflow graph which parses examples, applying tf-transform to them.
    """
    def fn():
        raw_feature_spec = _get_raw_feature_spec(schema)
        raw_feature_spec.pop(_LABEL_KEY)

        raw_input_fn = tf.estimator.export.build_parsing_serving_input_receiver_fn(
            raw_feature_spec, default_batch_size=None)
        serving_input_receiver = raw_input_fn()

        transformed_features = tf_transform_output.transform_raw_features(
            serving_input_receiver.features)

        return tf.estimator.export.ServingInputReceiver(
            transformed_features, serving_input_receiver.receiver_tensors)
    return fn


def _eval_input_receiver_fn(tf_transform_output, schema):
    """Build everything needed for the tf-model-analysis to run the model.

    Args:
      tf_transform_output: A TFTransformOutput.
      schema: the schema of the input data.

    Returns:
      EvalInputReceiver function, which contains:
        - Tensorflow graph which parses raw untransformed features, applies the
          tf-transform preprocessing operators.
        - Set of raw, untransformed features.
        - Label against which predictions will be compared.
    """
    def fn():
        # Notice that the inputs are raw features, not transformed features here.
        raw_feature_spec = _get_raw_feature_spec(schema)

        serialized_tf_example = tf.placeholder(
            dtype=tf.string, shape=[None], name='input_example_tensor')

        # Add a parse_example operator to the tensorflow graph, which will parse
        # raw, untransformed, tf examples.
        features = tf.parse_example(serialized_tf_example, raw_feature_spec)

        # Now that we have our raw examples, process them through the tf-transform
        # function computed during the preprocessing step.
        transformed_features = tf_transform_output.transform_raw_features(
            features)

        # The key name MUST be 'examples'.
        receiver_tensors = {'examples': serialized_tf_example}

        # NOTE: Model is driven by transformed features (since training works on the
        # materialized output of TFT, but slicing will happen on raw features.
        features.update(transformed_features)

        return tfma.export.EvalInputReceiver(
            features=features,
            receiver_tensors=receiver_tensors,
            labels=transformed_features[_LABEL_KEY])
    return fn


def build_input_fn(filenames, tf_transform_output, batch_size=200):
    print('BUILD_INPUT_FN')
    print(filenames)

    def input_fn(params, mode):
        training = mode == tf.estimator.ModeKeys.TRAIN
        transformed_feature_spec = tf_transform_output.transformed_feature_spec().copy()

        dataset = tf.data.experimental.make_batched_features_dataset(
            file_pattern=filenames,
            batch_size=128,
            features=transformed_feature_spec,
            label_key=_LABEL_KEY, reader=_gzip_reader_fn)

        return dataset
    return input_fn


def model_fn(features, labels, mode, params, config):
    model = MY_RNN(params)
    logits = model(
        tf.stack([features[k+'_xf'] for k in SEQUENCE_FEATURES], axis=-1))
    if mode in [tf.estimator.ModeKeys.TRAIN, tf.estimator.ModeKeys.EVAL]:
        loss = tf.losses.sigmoid_cross_entropy(labels, logits)
    if mode == tf.estimator.ModeKeys.TRAIN:
        return tf.estimator.EstimatorSpec(
            mode=mode,
            loss=loss,
            train_op=tf.train.AdamOptimizer().minimize(loss, tf.train.get_global_step())
        )
    elif mode == tf.estimator.ModeKeys.EVAL:
        return tf.estimator.EstimatorSpec(
            mode=mode,
            loss=loss,
            eval_metric_ops={}
        )
    elif mode == tf.estimator.ModeKeys.PREDICT:
        return tf.estimator.EstimatorSpec(
            mode=mode,
            predictions=logits
        )


def trainer_fn(hparams, schema):

    tf_transform_output = tft.TFTransformOutput(hparams.transform_output)

    train_spec = tf.estimator.TrainSpec(  # pylint: disable=g-long-lambda
        build_input_fn(hparams.train_files,
                       tf_transform_output, batch_size=128),
        max_steps=hparams.train_steps)

    exporter = tf.estimator.FinalExporter('final_export',
                                          _example_serving_receiver_fn(tf_transform_output, schema))
    eval_spec = tf.estimator.EvalSpec(
        build_input_fn(hparams.eval_files,
                       tf_transform_output, batch_size=4096),
        steps=hparams.eval_steps,
        exporters=[exporter],
        name='eval')

    config = tf.estimator.RunConfig(
        model_dir=hparams.serving_model_dir,
        save_checkpoints_steps=100,
        keep_checkpoint_max=1)

    estimator = tf.estimator.Estimator(
        model_fn, params=hparams, config=config)

    return {
        'estimator': estimator,
        'train_spec': train_spec,
        'eval_spec': eval_spec,
        'eval_input_receiver_fn': _eval_input_receiver_fn(tf_transform_output, schema)
    }
```
