### ISSUE TITLE
Error in StatisticsGen using Dataflow — Shuffle key too large

### ISSUE THREAD

**Issue by JakeTheWise** [tensorflow/tfx#505]
My TFX pipeline on kubeflow fails at the StatisticsGen component with the following error. One of my features contains long strings potentially over 2MB, which could be the cause of the error according to StackOverflow (https://stackoverflow.com/a/49101242).

TFX docker image used: tensorflow/tfx:0.14.0.dev20190819 from https://hub.docker.com/r/tensorflow/tfx/tags
Kubeflow version: v0.5.0 on GKE
TFX built from 5e01e6a905ec240c60f040ef6953a685081df3a8
```
Traceback (most recent call last):
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 106, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 102, in main
    executor.run()
  File "/opt/venv/lib/python3.5/site-packages/tfx/orchestration/kubeflow/executor_wrappers.py", line 123, in run
    self._exec_properties)
  File "/opt/venv/lib/python3.5/site-packages/tfx/components/statistics_gen/executor.py", line 89, in Do
    split, output_uri))
  File "/opt/venv/lib/python3.5/site-packages/apache_beam/pipeline.py", line 426, in __exit__
    self.run().wait_until_finish()
  File "/opt/venv/lib/python3.5/site-packages/apache_beam/runners/dataflow/dataflow_runner.py", line 1338, in wait_until_finish
    (self.state, getattr(self._runner, 'last_error_msg', None)), self)
apache_beam.runners.dataflow.dataflow_runner.DataflowRuntimeException: Dataflow pipeline failed. State: FAILED, Error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/dataflow_worker/batchworker.py", line 649, in do_work
    work_executor.execute()
  File "/usr/local/lib/python3.5/site-packages/dataflow_worker/executor.py", line 178, in execute
    op.finish()
  File "apache_beam/runners/worker/operations.py", line 874, in apache_beam.runners.worker.operations.PGBKCVOperation.finish
  File "apache_beam/runners/worker/operations.py", line 876, in apache_beam.runners.worker.operations.PGBKCVOperation.finish
  File "apache_beam/runners/worker/operations.py", line 887, in apache_beam.runners.worker.operations.PGBKCVOperation.output_key
  File "apache_beam/runners/worker/operations.py", line 256, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 143, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "dataflow_worker/shuffle_operations.py", line 188, in dataflow_worker.shuffle_operations.ReifyTimestampAndWindowsOperation.process
  File "dataflow_worker/shuffle_operations.py", line 192, in dataflow_worker.shuffle_operations.ReifyTimestampAndWindowsOperation.process
  File "apache_beam/runners/worker/operations.py", line 256, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 143, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "dataflow_worker/shuffle_operations.py", line 151, in dataflow_worker.shuffle_operations.ShuffleWriteOperation.process
  File "dataflow_worker/shuffle_operations.py", line 171, in dataflow_worker.shuffle_operations.ShuffleWriteOperation.process
  File "/usr/local/lib/python3.5/site-packages/dataflow_worker/shuffle.py", line 620, in Write
    self.writer.Write(self.stream.getvalue())
  File "third_party/windmill/shuffle/python/shuffle_client.pyx", line 176, in shuffle_client.PyShuffleWriter.Write
OSError: Shuffle write failed: b'INVALID_ARGUMENT: Shuffle key too large:1745410 > 1572864'
```

**Comment by rmothukuru** [comment]
Please provide details about what platform you are using (operating system, architecture). 

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by JakeTheWise** [comment]
@rmothukuru sure thing, sorry. So I just used a cloud kubeflow deployment using http://deploy.kubeflow.cloud so it runs on those defaults: k8s v1.11 on a two node cluster. I've listed the specific builds/images above. Is there something else you would find useful to help solve this bug?

**Comment by 1025KB** [comment]
Is chicago taxi example works fine?

seems the feature are used as key and Dataflow doesn't allow a 2M size key.
I feel the feature that contain so many bits many not be good for training even you make it work with StatisticsGen, could you explain a little bit about the use case here?

**Comment by JakeTheWise** [comment]
I'm doing document classification, which is why the strings are so big. I thought I could use TFX/tf-transform to tokenize them, apply/compute vocabulary, and do TFIDF... maybe you can you think of a better way to accomplish this?

I tried running the chicago taxi example on the latest builds but it fails on the StatisticsGen component with the following error:
```
Traceback (most recent call last):
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 106, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 102, in main
    executor.run()
  File "/opt/venv/lib/python3.5/site-packages/tfx/orchestration/kubeflow/executor_wrappers.py", line 123, in run
    self._exec_properties)
  File "/opt/venv/lib/python3.5/site-packages/tfx/components/statistics_gen/executor.py", line 89, in Do
    split, output_uri))
  File "/opt/venv/lib/python3.5/site-packages/apache_beam/pipeline.py", line 426, in __exit__
    self.run().wait_until_finish()
  File "/opt/venv/lib/python3.5/site-packages/apache_beam/runners/dataflow/dataflow_runner.py", line 1338, in wait_until_finish
    (self.state, getattr(self._runner, 'last_error_msg', None)), self)
apache_beam.runners.dataflow.dataflow_runner.DataflowRuntimeException: Dataflow pipeline failed. State: FAILED, Error:
Workflow failed. Causes: S12:GenerateStatistics.train/RunStatsGenerators/GenerateSlicedStatisticsImpl/RunCombinerStatsGenerators/CombinePerKey(PostCombineFn)/GroupByKey/Read+GenerateStatistics.train/RunStatsGenerators/GenerateSlicedStatisticsImpl/RunCombinerStatsGenerators/CombinePerKey(PostCombineFn)/Combine+GenerateStatistics.train/RunStatsGenerators/GenerateSlicedStatisticsImpl/RunCombinerStatsGenerators/CombinePerKey(PostCombineFn)/Combine/Extract+GenerateStatistics.train/RunStatsGenerators/GenerateSlicedStatisticsImpl/MergeDatasetFeatureStatisticsProtos/GroupByKey+GenerateStatistics.train/RunStatsGenerators/GenerateSlicedStatisticsImpl/MergeDatasetFeatureStatisticsProtos/Combine/Partial+GenerateStatistics.train/RunStatsGenerators/GenerateSlicedStatisticsImpl/MergeDatasetFeatureStatisticsProtos/GroupByKey/Reify+GenerateStatistics.train/RunStatsGenerators/GenerateSlicedStatisticsImpl/MergeDatasetFeatureStatisticsProtos/GroupByKey/Write failed., The job failed because a work item has failed 4 times. Look in previous log entries for the cause of each one of the 4 failures. For more information, see 
https://cloud.google.com/dataflow/docs/guides/common-errors
. The work item was attempted on these workers: 
  beamapp-root-0821152812-9-08210828-7lki-harness-th7z,
  beamapp-root-0821152812-9-08210828-7lki-harness-th7z,
  beamapp-root-0821152812-9-08210828-7lki-harness-th7z,
  beamapp-root-0821152812-9-08210828-7lki-harness-th7z
```

**Comment by 1025KB** [comment]
This is due to in stats gen, we are trying to calculate the distribution and topK, what you can do is whitelist certain feature by using the [stats_options](https://github.com/tensorflow/data-validation/blob/master/tensorflow_data_validation/statistics/stats_options.py#L42) [here](https://github.com/tensorflow/tfx/blob/master/tfx/components/statistics_gen/executor.py#L70)

can this 2M string be bucketized or it's just a the doc itself and the doc contents are various?

**Comment by JakeTheWise** [comment]
It's just the doc itself. I'm looking at your links to StatsOptions and the StatisticsGen Executor class. So you're saying if I pass the string column (or "doc" column rather) to `feature_whitelist`, it will solve the issue? I thought all features were whitelisted already by default.

**Comment by 1025KB** [comment]
I think you need to pass everything else to feature_whitelist to make it work based on the comment in the code.
