### ISSUE TITLE
Chicago taxi pipeline fails for KFP

### ISSUE THREAD

**Issue by gaoning777** [tensorflow/tfx#518]
I pulled the example from the 0.13.0 version and install the 0.13.0 SDK.
When I run it in the KFP(deployed Kubeflow 0.6.1), it failed with the following messages:
```
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
Traceback (most recent call last):
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 95, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 91, in main
    runner.run()
  File "/tfx-src/tfx/orchestration/kubeflow/container_runners.py", line 108, in run
    self._exec_properties)
  File "/tfx-src/tfx/components/transform/executor.py", line 247, in Do
    self.Transform(label_inputs, label_outputs, status_file)
  File "/tfx-src/tfx/components/transform/executor.py", line 611, in Transform
    compute_statistics, materialize_output_paths)
  File "/tfx-src/tfx/components/transform/executor.py", line 727, in _RunBeamImpl
    | 'AnalyzeDataset' >> tft_beam.AnalyzeDataset(preprocessing_fn))
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/transforms/ptransform.py", line 882, in __ror__
    return self.transform.__ror__(pvalueish, self.label)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/transforms/ptransform.py", line 509, in __ror__
    result = p.apply(self, pvalueish, label)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/pipeline.py", line 480, in apply
    return self.apply(transform, pvalueish)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/pipeline.py", line 516, in apply
    pvalueish_result = self.runner.apply(transform, pvalueish, self._options)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/runners/runner.py", line 193, in apply
    return m(transform, input, options)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/runners/runner.py", line 199, in apply_PTransform
    return transform.expand(input)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_transform/beam/impl.py", line 825, in expand
    input_metadata))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_transform/beam/impl.py", line 716, in expand
    output_signature = self._preprocessing_fn(copied_inputs)
  File "taxi_utils.py", line 131, in preprocessing_fn
    always_return_num_quantiles=False)
TypeError: bucketize() got an unexpected keyword argument 'always_return_num_quantiles'
```

Looks like the e2e tests do not cover the chicago taxi pipeline for KFP.

**Comment by neuromage** [comment]
@gaoning777 did you use taxi_utils.py from HEAD or from 0.13? That looks like an issue caused by taxi_utils.py version mismatch.

**Comment by gaoning777** [comment]
After using the taxi_utils from 0.13, it works.
