### ISSUE TITLE
`Evaluator` fails when orchestrated by Airflow due to no attributes for `component_run_context`

### ISSUE THREAD

**Issue by rseeto** [tensorflow/tfx#5193]
### System information
- Ubuntu version: 20
- TensorFlow version: 2.9.2
- TFX Version: 1.9.1
- Python version: 3.8
- Airflow version: 2.3.4

### Describe the current behaviour
I've run a pipeline with Airflow once without issue. I've rerun the pipeline (incorporating a blessed model from the first run) but the `Evaluator` component fails due to issues with the `component_run_context`. 

I believe this issue may be associated with recently patched [artifact naming issue](https://github.com/tensorflow/tfx/issues/4977).

### Logs
```
Traceback (most recent call last):
  File "/home/ryan/Documents/GitHub/dog_classifier/.venv/lib/python3.8/site-packages/tfx/orchestration/metadata.py", line 690, in register_execution
    execution_id, a_ids, context_ids = self.store.put_execution(
  File "/home/ryan/Documents/GitHub/dog_classifier/.venv/lib/python3.8/site-packages/ml_metadata/metadata_store/metadata_store.py", line 591, in put_execution
    self._call('PutExecution', request, response)
  File "/home/ryan/Documents/GitHub/dog_classifier/.venv/lib/python3.8/site-packages/ml_metadata/metadata_store/metadata_store.py", line 188, in _call
    return self._call_method(method_name, request, response)
  File "/home/ryan/Documents/GitHub/dog_classifier/.venv/lib/python3.8/site-packages/ml_metadata/metadata_store/metadata_store.py", line 209, in _call_method
    self._pywrap_cc_call(cc_method, request, response)
  File "/home/ryan/Documents/GitHub/dog_classifier/.venv/lib/python3.8/site-packages/ml_metadata/metadata_store/metadata_store.py", line 240, in _pywrap_cc_call
    raise _make_exception(error_message.decode('utf-8'), status_code)
ml_metadata.errors.AlreadyExistsError: Given event already exists: artifact_id: 13
execution_id: 17
path {
  steps {
    key: "baseline_model"
  }
  steps {
    index: 0
  }
}
type: INPUT
INTERNAL: Error when executing query: UNIQUE constraint failed: Event.artifact_id, Event.execution_id, Event.type query:  INSERT INTO `Event`(    `artifact_id`, `execution_id`, `type`,    `milliseconds_since_epoch` ) VALUES(13, 17, 3, 1662487357393);

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ryan/Documents/GitHub/dog_classifier/.venv/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/ryan/Documents/GitHub/dog_classifier/.venv/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ryan/Documents/GitHub/dog_classifier/.venv/lib/python3.8/site-packages/tfx/orchestration/airflow/airflow_component.py", line 76, in _airflow_component_launcher
    launcher.launch()
  File "/home/ryan/Documents/GitHub/dog_classifier/.venv/lib/python3.8/site-packages/tfx/orchestration/launcher/base_component_launcher.py", line 191, in launch
    execution_decision = self._run_driver(self._input_dict, self._output_dict,
  File "/home/ryan/Documents/GitHub/dog_classifier/.venv/lib/python3.8/site-packages/tfx/orchestration/launcher/base_component_launcher.py", line 155, in _run_driver
    execution_decision = driver.pre_execution(
  File "/home/ryan/Documents/GitHub/dog_classifier/.venv/lib/python3.8/site-packages/tfx/dsl/components/base/base_driver.py", line 279, in pre_execution
    execution = self._metadata_handler.register_execution(
  File "/home/ryan/Documents/GitHub/dog_classifier/.venv/lib/python3.8/site-packages/tfx/orchestration/metadata.py", line 700, in register_execution
    component_run_context.name)
AttributeError: 'NoneType' object has no attribute 'name'
```

If this is not a bug, any help is appreciated as there does not seem to be a lot of info on the `Evaluator` component, especially with evaluating a previously blessed model.

**Comment by singhniraj08** [comment]
@rseeto,

This issue is already been reported #4977 and a [PR](https://github.com/tensorflow/tfx/pull/5039) is created for the same. Requesting you to close this issue and follow #4977 thread. Thank you!
