### ISSUE TITLE
'.system' directory is not created in s3 path

### ISSUE THREAD

**Issue by navie-bp** [tensorflow/tfx#5212]
**System information**

- Have I specified the code to reproduce the issue (Yes, No):
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows),
  Interactive Notebook, Google Cloud, etc): Linux, Amazon EC2
- TensorFlow version: 2.7.0
- TFX Version: 1.6.0
- Python version: 3.7
- Python dependencies (from `pip freeze` output):
absl-py                         1.2.0
aiobotocore                     2.1.2
aiohttp                         3.8.1
aioitertools                    0.10.0
aiosignal                       1.2.0
alembic                         1.4.1
apache-beam                     2.35.0
argon2-cffi                     21.3.0
argon2-cffi-bindings            21.2.0
astunparse                      1.6.3
async-timeout                   4.0.2
asynctest                       0.13.0
attrs                           20.3.0
backcall                        0.2.0
beautifulsoup4                  4.11.1
bleach                          5.0.1
boto3                           1.20.23
botocore                        1.23.24
cachetools                      4.2.4
certifi                         2022.6.15
cffi                            1.15.1
charset-normalizer              2.1.0
click                           7.1.2
cloudpickle                     2.1.0
crcmod                          1.7
databricks-cli                  0.17.0
debugpy                         1.6.3
decorator                       5.1.1
defusedxml                      0.7.1
Deprecated                      1.2.13
dill                            0.3.1.1
docker                          4.4.4
docopt                          0.6.2
entrypoints                     0.4
faiss-cpu                       1.7.2
fastavro                        1.6.0
fasteners                       0.17.3
fastjsonschema                  2.16.1
Flask                           1.1.2
flatbuffers                     2.0
frozenlist                      1.3.1
fsspec                          2022.2.0
gast                            0.4.0
gitdb                           4.0.9
GitPython                       3.1.27
google-api-core                 2.8.1
google-api-python-client        1.12.11
google-apitools                 0.5.31
google-auth                     2.10.0
google-auth-httplib2            0.1.0
google-auth-oauthlib            0.4.6
google-cloud-aiplatform         1.16.1
google-cloud-bigquery           2.34.4
google-cloud-bigquery-storage   2.13.2
google-cloud-bigtable           1.7.2
google-cloud-core               2.3.2
google-cloud-datastore          1.15.5
google-cloud-dlp                3.8.1
google-cloud-language           1.3.2
google-cloud-pubsub             2.13.6
google-cloud-pubsublite         1.4.3
google-cloud-recommendations-ai 0.7.1
google-cloud-resource-manager   1.6.1
google-cloud-spanner            1.19.3
google-cloud-storage            2.5.0
google-cloud-videointelligence  1.16.3
google-cloud-vision             1.0.2
google-crc32c                   1.3.0
google-pasta                    0.2.0
google-resumable-media          2.3.3
googleapis-common-protos        1.56.4
greenlet                        1.1.2
grpc-google-iam-v1              0.12.4
grpcio                          1.47.0
grpcio-gcp                      0.2.2
grpcio-status                   1.47.0
gunicorn                        20.1.0
h5py                            3.7.0
hdfs                            2.7.0
httplib2                        0.19.1
idna                            3.3
importlib-metadata              4.12.0
importlib-resources             5.9.0
ipykernel                       6.15.2
ipython                         7.34.0
ipython-genutils                0.2.0
ipywidgets                      7.7.2
itsdangerous                    2.1.2
jedi                            0.18.1
Jinja2                          3.1.2
jmespath                        0.10.0
joblib                          0.14.1
jsonpickle                      2.2.0
jsonschema                      4.14.0
jupyter_client                  7.3.5
jupyter-core                    4.11.1
jupyterlab-pygments             0.2.2
jupyterlab-widgets              1.1.1
keras                           2.7.0
Keras-Preprocessing             1.1.2
keras-tuner                     1.1.3
kt-legacy                       1.0.4
kubernetes                      12.0.1
libclang                        14.0.6
lxml                            4.9.1
Mako                            1.2.1
Markdown                        3.4.1
MarkupSafe                      2.1.1
matplotlib-inline               0.1.3
mistune                         2.0.4
ml-metadata                     1.6.0
ml-pipelines-sdk                1.6.0
mlflow                          1.22.0
multidict                       6.0.2
nbclient                        0.6.7
nbconvert                       7.0.0
nbformat                        5.4.0
nest-asyncio                    1.5.5
networkx                        2.6.3
notebook                        6.4.12
numpy                           1.20.3
oauth2client                    4.1.3
oauthlib                        3.2.0
opt-einsum                      3.3.0
orjson                          3.8.0
overrides                       6.2.0
packaging                       20.9
pandas                          1.1.5
pandocfilters                   1.5.0
parso                           0.8.3
pexpect                         4.8.0
pickleshare                     0.7.5
Pillow                          9.2.0
pip                             22.1.2
pkgutil_resolve_name            1.3.10
portpicker                      1.5.2
prometheus-client               0.14.1
prometheus-flask-exporter       0.20.3
prompt-toolkit                  3.0.30
proto-plus                      1.22.0
protobuf                        3.19.4
psutil                          5.9.1
ptyprocess                      0.7.0
py4j                            0.10.9.2
pyarrow                         5.0.0
pyasn1                          0.4.8
pyasn1-modules                  0.2.8
pycparser                       2.21
pydot                           1.4.2
Pygments                        2.12.0
PyJWT                           2.4.0
pymongo                         3.12.3
pyparsing                       2.4.7
pyrsistent                      0.18.1
pyspark                         3.2.0
python-dateutil                 2.8.2
python-editor                   1.0.4
python-snappy                   0.6.1
pytz                            2022.1
pyvis                           0.1.9
PyYAML                          5.4.1
pyzmq                           23.2.1
querystring-parser              1.2.4
redis                           4.0.0
requests                        2.28.1
requests-oauthlib               1.3.1
rsa                             4.9
s3fs                            2022.2.0
s3transfer                      0.5.2
scipy                           1.7.3
Send2Trash                      1.8.0
setuptools                      61.2.0
six                             1.16.0
smmap                           5.0.0
soupsieve                       2.3.2.post1
sql-metadata                    2.6.0
SQLAlchemy                      1.4.39
sqlparse                        0.4.2
tabulate                        0.8.10
tensorboard                     2.9.1
tensorboard-data-server         0.6.1
tensorboard-plugin-wit          1.8.1
tensorflow                      2.7.0
tensorflow-data-validation      1.6.0
tensorflow-estimator            2.7.0
tensorflow-gpu                  2.7.0
tensorflow-hub                  0.12.0
tensorflow-io                   0.23.1
tensorflow-io-gcs-filesystem    0.23.1
tensorflow-metadata             1.6.0
tensorflow-model-analysis       0.37.0
tensorflow-serving-api          2.7.0
tensorflow-transform            1.6.1
termcolor                       1.1.0
terminado                       0.15.0
tfx                             1.6.0
tfx-bsl                         1.6.0
tinycss2                        1.1.1
torch                           1.12.0
torchvision                     0.13.0
tornado                         6.2
traitlets                       5.3.0
typing-extensions               3.10.0.2
uritemplate                     3.0.1
urllib3                         1.26.11
wcwidth                         0.2.5
webencodings                    0.5.1
websocket-client                1.3.3
Werkzeug                        2.2.1
wheel                           0.37.1
widgetsnbextension              3.6.1
wrapt                           1.14.1
yarl                            1.8.1
zipp                            3.8.1

**Describe the current behavior**
If I run ImportExampleGen, an error occurs in the clean up step.
```
INFO:absl:Cleaning up stateless execution info.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tfx/dsl/io/plugins/tensorflow_gfile.py", line 102, in rmtree
    tf.io.gfile.rmtree(path)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 678, in delete_recursively_v2
    _pywrap_file_io.DeleteRecursively(compat.path_to_bytes(path))
tensorflow.python.framework.errors_impl.NotFoundError: Object s3://bucket/output/tfx_test/ImportExampleGen/.system/executor_execution/49/.temp/ does not exist
```

The problem seems to be that the '.system' directory is not created.
`fileio.makedirs` function is used to create the '.system' directory.
So I tested that function as simply as below, but the directory is not created and no error generated.
```
from tfx.dsl.io import fileio
fileio.makedirs("s3://bucket/test/gfile_test/")
```

When I tested the deletion, I got a NotFoundError.
```
from tfx.dsl.io import fileio
fileio.rmtree("s3://bucket/test/gfile_test/")
```

**Describe the expected behavior**
- '.system' directory should be created in S3 or
- NotFoundError should not occur when deleting.

**Standalone code to reproduce the issue**

Providing a bare minimum test case or step(s) to reproduce the problem will
greatly help us to debug the issue. If possible, please share a link to
Colab/Jupyter/any notebook.

**Name of your Organization (Optional)**

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by navie-bp** [comment]
I confirmed that it was fixed in tfx 1.9.1 version.
Close this issue.
