### ISSUE TITLE
Need help configuring `default_kubeflow_metadata_config` for GKE

### ISSUE THREAD

**Issue by JakeTheWise** [tensorflow/tfx#590]
I'm still new to the world of kubernetes, kubeflow and TFX so sorry for this dumdum question — I'm running TFX on a GCP/GKE deployment of kubernetes (using http://deploy.kubeflow.cloud), and I'm getting the following error in my `ImportExampleGen` component:
```
Traceback (most recent call last):
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 200, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 171, in main
    connection_config = _get_metadata_connection_config(kubeflow_metadata_config)
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 68, in _get_metadata_connection_config
    kubeflow_metadata_config.mysql_db_service_host)
TypeError: None has type NoneType, but expected one of: bytes, unicode
```

I assume I need to override the `default_kubeflow_metadata_config` in my `pipeline.py` but I don't know how exactly:
```python
...

if __name__ == '__main__':
    # Metadata config. The defaults works work with the installation of
    # KF Pipelines using Kubeflow. If installing KF Pipelines using the
    # lightweight deployment option, you may need to override the defaults.
    metadata_config = kubeflow_dag_runner.get_default_kubeflow_metadata_config()

    # Do something here maybe???

    runner_config = kubeflow_dag_runner.KubeflowDagRunnerConfig(
        kubeflow_metadata_config=metadata_config,
        tfx_image='tensorflow/tfx:0.14.0rc1'
    )

    kubeflow_dag_runner.KubeflowDagRunner(
        config=runner_config
    ).run(
        _create_pipeline(
            pipeline_name=_pipeline_name,
            pipeline_root=_pipeline_root,
            module_file=_module_file,
            data_root=_data_root,
            serving_model_dir=_serving_model_dir,
            beam_pipeline_args=_beam_pipeline_args,
            ai_platform_training_args=_ai_platform_training_args,
            ai_platform_serving_args=_ai_platform_serving_args,
        ))
```

**Comment by ruoyu90** [comment]
@JakeTheWise thanks for the question!
What you got by `metadata_config = kubeflow_dag_runner.get_default_kubeflow_metadata_config()` is a python instance of `KubeflowMetadataConfig` proto. You can modify its value by referring to [this](https://github.com/tensorflow/tfx/blob/master/tfx/orchestration/kubeflow/proto/kubeflow.proto) proto definition.

**Comment by neuromage** [comment]
@JakeTheWise is this Kubeflow version at least 0.6? It does appear like the environment variable for the metadata db host isn't being set right. Can you kubectl ssh into a pod and see if the environment variable `METADATA_DB_SERVICE_HOST` is defined?

**Comment by JakeTheWise** [comment]
@neuromage it's kubeflow v0.5.0 built from http://deploy.kubeflow.cloud. Do you happen to know which pod I should look in? There's a lot. Idk if there's a way to grep for environment variables throughout all the pods in a cluster?

**Comment by neuromage** [comment]
@JakeTheWise Metadata support in Kubeflow is only available from v0.6 onwards. This version deploys a KF Metadata server with a UI, and the default pipeline settings are pointing to this deployed DB. Can you deploy a later version to try this out?

You can still run the pipeline with 0.5, and point to the existing mysql service, but you won't be able to access the metadata with any UI. If you want to do this, you need to modify the settings as follows:

```
config = kubeflow_pb2.KubeflowMetadataConfig()
config.mysql_db_service_host.environment_variable = 'MYSQL_SERVICE_HOST'
config.mysql_db_service_port.environment_variable = 'MYSQL_SERVICE_PORT'
config.mysql_db_name.value = self._get_mlmd_db_name(pipeline_name)
config.mysql_db_user.value = 'root'
config.mysql_db_password.value = ''
```

Hope this helps. I highly recommend using 0.6 though.
