### ISSUE TITLE
Unable to install tfx in local

### ISSUE THREAD

**Issue by Aditya-171** [tensorflow/tfx#6123]
- Environment in which the code is executed : Local

- Python version: 3.8.10

I created a virtual environment in my local and installed python 3.8.10.

Facing the following issue while installing tfx( pip install tfx )

ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Aditya Soni\anaconda3\envs\tfx\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\Aditya Soni\anaconda3\envs\tfx\lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "C:\Users\Aditya Soni\anaconda3\envs\tfx\lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "C:\Users\Aditya Soni\anaconda3\envs\tfx\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\Aditya Soni\anaconda3\envs\tfx\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\Aditya Soni\anaconda3\envs\tfx\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 457, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000
PS C:\Users\Aditya Soni\PycharmProjects\tfx>

**Comment by singhniraj08** [comment]
@Aditya-171,

I am unable to reproduce the issue on my side. Could you try to create a new conda environment with Python 3.9 and upgrade pip as shown in this [guide](https://kirenz.github.io/codelabs/codelabs/tfx-install/#0). Let us know if you encounter any issues. Thank you!

**Comment by csttsn** [comment]
I'm having the same issue. I decided to update Miniconda to the latest version and reinstall TFX, and now the installation fails with the same error for some reason (_pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000_). I tried creating both Python 3.9 and 3.8 envs, no difference. I use Windows 11.

Can someone suggest me how to install TFX now? It was installing perfectly before on a W11 machine.

**Comment by singhniraj08** [comment]
@csttsn,

Unfortunately there is currently no plan to support Windows. However, you can install WSL on windows following this [guide](https://learn.microsoft.com/en-us/windows/wsl/install) and set up a virtual Python environment inside your WSL instance. Then you can install TFX in your virtual environment and it should work without any issues. 

Please refer https://github.com/tensorflow/tfx/issues/5665#issuecomment-1401637945 to setup TFX on windows WSL. Thank you!

**Comment by csttsn** [comment]
Thanks for the information! BTW, I've just managed to install TFX 1.11, so looks like currently this is the latest version that can be installed on W11.
