### ISSUE TITLE
Error importing ‘CsvExampleGen’ on Python 3.5.2 and tfx 0.14.0

### ISSUE THREAD

**Issue by hustwzqgit** [tensorflow/tfx#631]
Importing ‘CsvExampleGen’ got the following error on 0.14.0 while it worked on 0.13.1

```
Traceback (most recent call last):

  File "<ipython-input-6-37fca75bd645>", line 1, in <module>
    from tfx.components.example_gen.csv_example_gen.component import CsvExampleGen

  File "/home/mt/Environments/rd1_114/lib/python3.5/site-packages/tfx/components/example_gen/csv_example_gen/component.py", line 22, in <module>
    from tfx import types

  File "/home/mt/Environments/rd1_114/lib/python3.5/site-packages/tfx/types/__init__.py", line 17, in <module>
    from tfx.types.channel import Channel

  File "/home/mt/Environments/rd1_114/lib/python3.5/site-packages/tfx/types/channel.py", line 25, in <module>
    class Channel(object):

  File "/home/mt/Environments/rd1_114/lib/python3.5/site-packages/tfx/types/channel.py", line 42, in Channel
    artifacts: Optional[Iterable[Artifact]] = None):

  File "/usr/lib/python3.5/typing.py", line 649, in __getitem__
    return Union[arg, type(None)]

  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)

  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):

  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):

  File "/usr/lib/python3.5/typing.py", line 1077, in __subclasscheck__
    if super().__subclasscheck__(cls):

  File "/home/mt/Environments/rd1_114/lib/python3.5/abc.py", line 225, in __subclasscheck__
    for scls in cls.__subclasses__():

TypeError: descriptor '__subclasses__' of 'type' object needs an argument
```

**Comment by gowthamkpr** [comment]
@hustwzqgit I am not able to reproduce this issue on google colab and the colab uses Python 3.6.8 version. Please find the github gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/a54c1606dd42bfdba0f6be2877c37606/untitled143.ipynb). Can you please try using Python 3.6 and let me know if the issue still persists. Thanks!

**Comment by charlesccychen** [comment]
This is a bug in Python 3.5.2 (see https://github.com/python/typing/issues/266).  Please update your Python version and let us know if it persists.

**Comment by hustwzqgit** [comment]
> @hustwzqgit I am not able to reproduce this issue on google colab which uses Python 3.6.8 version. Please find the github gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/a54c1606dd42bfdba0f6be2877c37606/untitled143.ipynb). Can you please try using Python 3.6 and let me know if the issue still persists. Thanks!

It works well on Python 3.6.8. Thanks!
