### ISSUE TITLE
no module named 'tfx.executors'

### ISSUE THREAD

**Issue by JerryKurata** [tensorflow/tfx#76]
Attempting to run tfx==0.13rc1 on Ubuntu 18.04

Install threw this error:
pip install tfx==0.13rc1
c-google-iam-v1 googleapis-common-protos backcall tornado prometheus-client pandocfilters pyrsistent
ERROR: apache-beam 2.12.0 has requirement httplib2<=0.11.3,>=0.8, but you'll have httplib2 0.12.3 which is incompatible.

Continuing on Airflow ran into:
Initializing Airflow database
/home/jerry/tfx-env/lib/python3.5/site-packages/airflow/configuration.py:214: FutureWarning: The task_runner setting in [core] has the old default value of 'BashTaskRunner'. This value has been changed to 'StandardTaskRunner' in the running config, but please update your config before Apache Airflow 2.0.
  FutureWarning,
/home/jerry/tfx-env/lib/python3.5/site-packages/airflow/configuration.py:575: DeprecationWarning: Specifying airflow_home in the config file is deprecated. As you have left it at the default value you should remove the setting from your airflow.cfg and suffer no change in behaviour.
  category=DeprecationWarning,
/home/jerry/tfx-env/lib/python3.5/site-packages/apache_beam/__init__.py:84: UserWarning: Running the Apache Beam SDK on Python 3 is not yet fully supported. You may encounter buggy behavior or missing features.
  'Running the Apache Beam SDK on Python 3 is not yet fully supported. '
[2019-04-30 17:46:19,679] {plugins_manager.py:143} ERROR - No module named 'tfx.executors'
Traceback (most recent call last):
  File "/home/jerry/tfx-env/lib/python3.5/site-packages/airflow/plugins_manager.py", line 137, in <module>
    m = imp.load_source(namespace, filepath)
  File "/home/jerry/tfx-env/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/jerry/airflow/plugins/tfx_example/model.py", line 27, in <module>
    from tfx.executors.trainer import TrainingSpec
ImportError: No module named 'tfx.executors'
[2019-04-30 17:46:19,679] {plugins_manager.py:144} ERROR - Failed to import plugin /home/jerry/airflow/plugins/tfx_example/model.py
[2019-04-30 17:46:19,695] {plugins_manager.py:143} ERROR - No module named 'tfx.executors'

Error repeats over and over.  
Eventually server crashes.

**Comment by ruoyu90** [comment]
@JerryKurata What example are you running? We actually don't have the import mentioned in the error message `from tfx.executors.trainer import TrainingSpec`. Can you point us to a codepiece?

**Comment by JerryKurata** [comment]
Sure.  I am a GDE and am executing the workshop tutorial, https://www.tensorflow.org/tfx/tutorials/tfx/workshop using tfx 0.13.rc1 and Python 3.5

**Comment by ruoyu90** [comment]
@JerryKurata I checked the tutorial examples and there is no code referring to `tfx.executors.trainer import TrainingSpec`. Looking at your filepath, it seems to be some developing version even before 0.12 release. Can you clean up your machine, especially ~/airflow folder and do the setup again from beginning?

**Comment by JerryKurata** [comment]
Thanks for looking at this I cleaned before installing, but will try again.

**Comment by JerryKurata** [comment]
Going to close this for now and will re-open when I can trace it down further.
