### ISSUE TITLE
cannot import name 'object_identity' from 'tensorflow.python.util'

### ISSUE THREAD

**Issue by JakubSido** [tensorflow/tfx#949]
Hello i'm trying to rin iris example from tfx.examples 

What am I doing wrong? 

Traceback (most recent call last):
  File "/opt/project/tfx_demo/main.py", line 27, in <module>
    from tfx.components import CsvExampleGen
  File "/usr/local/lib/python3.7/dist-packages/tfx/components/__init__.py", line 27, in <module>
    from tfx.components.example_validator.component import ExampleValidator
  File "/usr/local/lib/python3.7/dist-packages/tfx/components/example_validator/component.py", line 24, in <module>
    from tfx.components.example_validator import executor
  File "/usr/local/lib/python3.7/dist-packages/tfx/components/example_validator/executor.py", line 22, in <module>
    import tensorflow_data_validation as tfdv
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_data_validation/__init__.py", line 24, in <module>
    from tensorflow_data_validation.api.stats_api import GenerateStatistics
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_data_validation/api/stats_api.py", line 52, in <module>
    from tensorflow_data_validation.statistics import stats_impl
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_data_validation/statistics/stats_impl.py", line 35, in <module>
    from tensorflow_data_validation.statistics.generators import basic_stats_generator
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_data_validation/statistics/generators/basic_stats_generator.py", line 57, in <module>
    from tensorflow_data_validation.utils import quantiles_util
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_data_validation/utils/quantiles_util.py", line 27, in <module>
    import tensorflow_transform as tft
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_transform/__init__.py", line 19, in <module>
    from tensorflow_transform.analyzers import *
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_transform/analyzers.py", line 43, in <module>
    from tensorflow_transform import tf_utils
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_transform/tf_utils.py", line 25, in <module>
    from tensorflow.python.util import object_identity  # pylint: disable=g-direct-tensorflow-import
ImportError: cannot import name 'object_identity' from 'tensorflow.python.util' (/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/__init__.py)

[Dockerfile.txt](https://github.com/tensorflow/tfx/files/3864373/Dockerfile.txt)
[requirements.txt](https://github.com/tensorflow/tfx/files/3864375/requirements.txt)

**Comment by gowthamkpr** [comment]
@JakubSido You have to upgrade the version of Tensorflow you are using as Tensorflow 1.14 doesn't has object_identity.py([here](https://github.com/tensorflow/tensorflow/tree/r1.14/tensorflow/python/util)) but Tensorflow 1.15 has object_identity.py file as you can see [here](https://github.com/tensorflow/tensorflow/blob/r1.15/tensorflow/python/util/object_identity.py). Thanks!

**Comment by JakubSido** [comment]
That's it. Thank you.

**Comment by gowthamkpr** [comment]
I am gonna close this issue as it has been resolved @JakubSido
